import type { Discovery } from "./pocket-content.ts";
import type {
  MissionActionType,
  MissionDirection,
  MissionEnvironmentSuitability,
  MissionRole,
  ObservationConcept,
} from "./pocket-mission-grammar.ts";

type Variant = {
  id: string;
  title: string;
  hint?: string;
};

type Family = {
  prefix: string;
  emoji: string;
  difficulty: "easy" | "medium" | "hard";
  kind: "object" | "feature" | "detail";
  direction: MissionDirection;
  actionType: MissionActionType;
  concept: ObservationConcept;
  role: MissionRole;
  environmentSuitability?: MissionEnvironmentSuitability;
  hint?: string;
  tags?: string[];
  variants: Variant[];
};

function family(spec: Family): Discovery[] {
  return spec.variants.map((variant) => ({
    id: `grammar-${spec.prefix}-${variant.id}`,
    emoji: spec.emoji,
    title: variant.title,
    hint: variant.hint ?? spec.hint,
    difficulty: spec.difficulty,
    kind: spec.kind,
    direction: spec.direction,
    actionType: spec.actionType,
    concept: spec.concept,
    role: spec.role,
    environmentSuitability: spec.environmentSuitability ?? {},
    tags: spec.tags,
  }));
}

/**
 * Reviewed production expansion.
 *
 * These strings are fixed curated content, not runtime-generated text. Families
 * only remove repeated metadata boilerplate so the pool can grow without
 * becoming impossible to review.
 */
export const CURATED_CORE_EXPANSION: Discovery[] = [
  ...family({
    prefix: "color",
    emoji: "🎨",
    difficulty: "easy",
    kind: "feature",
    direction: "around",
    actionType: "find_one",
    concept: "color",
    role: "quick",
    tags: ["color"],
    variants: [
      { id: "blue", title: "找一個藍色的東西。" },
      { id: "yellow", title: "找一個黃色的東西。" },
      { id: "green", title: "找一個綠色的東西。" },
      { id: "orange", title: "找一個橘色的東西。" },
      { id: "white", title: "找一個白色的東西。" },
      { id: "black", title: "找一個黑色的東西。" },
      { id: "two-tone", title: "找一個有兩種顏色的東西。" },
      { id: "stripe", title: "找一個有色帶的東西。" },
    ],
  }),
  ...family({
    prefix: "shape",
    emoji: "◻️",
    difficulty: "easy",
    kind: "feature",
    direction: "around",
    actionType: "find_one",
    concept: "shape",
    role: "quick",
    tags: ["shape"],
    variants: [
      { id: "rectangle", title: "找一個長方形。" },
      { id: "square", title: "找一個正方形。" },
      { id: "arc", title: "找一個弧形。" },
      { id: "cross", title: "找一個交叉的線。" },
      { id: "parallel", title: "找一組平行線。" },
      { id: "grid", title: "找一個格子。" },
      { id: "symmetric", title: "找一個對稱的形狀。" },
      { id: "diamond", title: "找一個菱形。" },
    ],
  }),
  ...family({
    prefix: "text",
    emoji: "🔤",
    difficulty: "easy",
    kind: "feature",
    direction: "eye_level",
    actionType: "find_one",
    concept: "text",
    role: "quick",
    tags: ["text", "signage"],
    variants: [
      { id: "two-digit", title: "找一個兩位數。" },
      { id: "three-digit", title: "找一個三位數。" },
      { id: "repeat-char", title: "找一個重複的字。" },
      { id: "direction", title: "找一個方向標記。" },
      { id: "boxed", title: "找一個被框住的字。" },
      { id: "covered", title: "找一個被遮住的字。" },
      { id: "vertical", title: "找一排直著寫的字。" },
      { id: "handwritten", title: "找一個手寫的字。" },
    ],
  }),
  ...family({
    prefix: "ground",
    emoji: "⬇️",
    difficulty: "medium",
    kind: "detail",
    direction: "down",
    actionType: "find_one",
    concept: "boundary",
    role: "observation",
    hint: "只看安全能走的地方。",
    tags: ["ground"],
    variants: [
      { id: "joint", title: "找一條地面接縫。" },
      { id: "material", title: "找一塊不同材質的地面。" },
      { id: "worn-mark", title: "找一個磨損的地面標記。" },
      { id: "dot", title: "找一個地面圓點。" },
      { id: "square", title: "找一個地上的方形。" },
      { id: "height-change", title: "找一處地面高低差。" },
      { id: "curb-corner", title: "找一個路緣轉角。" },
      { id: "number", title: "找一個地面上的數字。" },
      { id: "color-line", title: "找一條不同顏色的地線。" },
      { id: "patch", title: "找一個地面補丁。" },
    ],
  }),
  ...family({
    prefix: "up",
    emoji: "⬆️",
    difficulty: "medium",
    kind: "detail",
    direction: "up",
    actionType: "find_one",
    concept: "height",
    role: "observation",
    tags: ["height", "architecture"],
    variants: [
      { id: "eave", title: "找一個屋簷。" },
      { id: "upper-sign", title: "找一個二樓以上的招牌。" },
      { id: "balcony", title: "找一個陽台。" },
      { id: "pipe", title: "找一條高處的管線。" },
      { id: "circle", title: "找一個高處的圓形。" },
      { id: "windows", title: "找一排樓上的窗。" },
      { id: "roof-edge", title: "找一條屋頂邊緣。" },
      { id: "light", title: "找一盞高處的燈。" },
    ],
  }),
  ...family({
    prefix: "material",
    emoji: "◫",
    difficulty: "medium",
    kind: "detail",
    direction: "eye_level",
    actionType: "find_one",
    concept: "material",
    role: "observation",
    tags: ["material", "surface"],
    variants: [
      { id: "metal", title: "找一個金屬表面。" },
      { id: "tile", title: "找一塊磁磚。" },
      { id: "transparent", title: "找一個透明材質。" },
      { id: "wood", title: "找一個木頭表面。" },
      { id: "plastic", title: "找一個塑膠表面。" },
      { id: "rough", title: "找一個粗糙的表面。" },
      { id: "smooth", title: "找一個光滑的表面。" },
      { id: "mesh", title: "找一個網狀材質。" },
    ],
  }),
  ...family({
    prefix: "wear",
    emoji: "🩹",
    difficulty: "medium",
    kind: "detail",
    direction: "eye_level",
    actionType: "find_one",
    concept: "wear",
    role: "observation",
    tags: ["wear", "repair"],
    variants: [
      { id: "paint", title: "找一個掉漆的地方。" },
      { id: "polished-edge", title: "找一個被磨亮的邊。" },
      { id: "crack", title: "找一條裂痕。" },
      { id: "covered-hole", title: "找一個被補住的洞。" },
      { id: "filled-seam", title: "找一條補過的縫。" },
      { id: "color-patch", title: "找一塊不同色的補丁。" },
      { id: "new-fastener", title: "找一個新加的固定點。" },
      { id: "bent-edge", title: "找一個彎掉的邊角。" },
      { id: "faded-mark", title: "找一個褪色的標記。" },
      { id: "scratched", title: "找一個被刮花的表面。" },
    ],
  }),
  ...family({
    prefix: "pattern",
    emoji: "🔁",
    difficulty: "medium",
    kind: "feature",
    direction: "around",
    actionType: "find_pattern",
    concept: "repetition",
    role: "observation",
    tags: ["pattern", "repetition"],
    variants: [
      { id: "row", title: "找一排一樣的東西。" },
      { id: "three-patterns", title: "找三個一樣的圖案。" },
      { id: "parallel-three", title: "找三條平行線。" },
      { id: "circles", title: "找一組重複的圓。" },
      { id: "grid", title: "找一組重複的方格。" },
      { id: "symbols", title: "找兩個一樣的符號。" },
      { id: "spacing", title: "找三個等距的東西。" },
      { id: "colors", title: "找一串重複的顏色。" },
    ],
  }),
  ...family({
    prefix: "compare",
    emoji: "↔️",
    difficulty: "medium",
    kind: "feature",
    direction: "around",
    actionType: "compare",
    concept: "boundary",
    role: "observation",
    tags: ["compare"],
    variants: [
      { id: "big-small", title: "找一個大和一個小的東西。" },
      { id: "high-low", title: "找一個高和一個低的東西。" },
      { id: "light-dark", title: "找一個亮和一個暗的表面。" },
      { id: "new-old", title: "找一個新和一個舊的表面。" },
      { id: "thick-thin", title: "找一條粗線和一條細線。" },
      { id: "materials", title: "找兩種不同材質放在一起。" },
      { id: "whole-worn", title: "找一個完整和一個磨損的東西。" },
      { id: "color-gap", title: "找兩個顏色差很多的東西。" },
    ],
  }),
  ...family({
    prefix: "light",
    emoji: "✨",
    difficulty: "medium",
    kind: "feature",
    direction: "around",
    actionType: "find_one",
    concept: "light",
    role: "observation",
    tags: ["light", "reflection", "shadow"],
    variants: [
      { id: "mirror", title: "找一個能看到倒影的表面。" },
      { id: "sparkle", title: "找一個會閃光的表面。" },
      { id: "translucent", title: "找一個半透明的東西。" },
      { id: "bright-spot", title: "找一個特別亮的點。" },
      { id: "shadow-edge", title: "找一道影子的邊。" },
      { id: "split-light", title: "找一個一半亮一半暗的表面。" },
      { id: "metal-highlight", title: "找一個金屬上的亮點。" },
      { id: "light-shape", title: "找一塊有形狀的光。" },
    ],
  }),
  ...family({
    prefix: "opening",
    emoji: "🪟",
    difficulty: "medium",
    kind: "object",
    direction: "eye_level",
    actionType: "find_one",
    concept: "opening",
    role: "observation",
    tags: ["opening", "architecture"],
    variants: [
      { id: "half-door", title: "找一扇半開的門。" },
      { id: "closed-window", title: "找一扇關著的窗。" },
      { id: "door-frame", title: "找一個門框。" },
      { id: "window-frame", title: "找一個窗框。" },
      { id: "rail-gap", title: "找一個欄杆的缺口。" },
      { id: "entrance-mark", title: "找一個入口標記。" },
      { id: "double-frame", title: "找一個有兩層框的開口。" },
      { id: "sealed", title: "找一個被封住的開口。" },
    ],
  }),
  ...family({
    prefix: "greenery",
    emoji: "🌿",
    difficulty: "medium",
    kind: "object",
    direction: "eye_level",
    actionType: "find_one",
    concept: "greenery",
    role: "observation",
    environmentSuitability: {
      preferred: ["green", "residential", "mixed"],
    },
    tags: ["nature", "greenery"],
    variants: [
      { id: "big-leaf", title: "找一片大葉子。" },
      { id: "small-leaf", title: "找一片小葉子。" },
      { id: "crack-plant", title: "找一個從縫裡長出的植物。" },
      { id: "low-branch", title: "找一棵有低枝的樹。" },
      { id: "thick-trunk", title: "找一棵粗樹幹的樹。" },
      { id: "high-pot", title: "找一盆放在高處的植物。" },
    ],
  }),
  ...family({
    prefix: "distance",
    emoji: "🔭",
    difficulty: "medium",
    kind: "feature",
    direction: "distance",
    actionType: "find_one",
    concept: "height",
    role: "observation",
    hint: "站在原本安全的位置看。",
    tags: ["distance"],
    variants: [
      { id: "circle", title: "找遠處一個圓形。" },
      { id: "bright", title: "找遠處一個亮色的東西。" },
      { id: "windows", title: "找遠處一排窗。" },
      { id: "sign", title: "找遠處一個高招牌。" },
      { id: "number", title: "找一個隔街看得到的數字。" },
      { id: "heights", title: "找遠處兩個高度不同的東西。" },
    ],
  }),
  ...family({
    prefix: "view",
    emoji: "👀",
    difficulty: "easy",
    kind: "feature",
    direction: "distance",
    actionType: "choose_viewpoint",
    concept: "boundary",
    role: "rhythm_change",
    hint: "留在安全、不擋路的位置。",
    tags: ["viewpoint"],
    variants: [
      { id: "intersection", title: "找一個看得到路口的位置。" },
      { id: "store-row", title: "找一個看得到一排店面的位置。" },
      { id: "layers", title: "找一個看得到遠近兩層的位置。" },
      { id: "gaps", title: "找一個能看穿兩個空隙的位置。" },
    ],
  }),
  ...family({
    prefix: "flow",
    emoji: "⏱️",
    difficulty: "easy",
    kind: "feature",
    direction: "stop_and_watch",
    actionType: "stop_and_observe",
    concept: "flow",
    role: "rhythm_change",
    hint: "找安全、不擋路的位置。",
    environmentSuitability: {
      preferred: ["commercial", "plaza", "pedestrian", "transit"],
    },
    tags: ["flow", "movement"],
    variants: [
      { id: "people-side", title: "停 20 秒，看哪邊人比較多。" },
      { id: "cars-side", title: "停 20 秒，看哪邊車比較多。" },
      { id: "movement", title: "停 20 秒，看東西怎麼移動。" },
      { id: "crossing", title: "停 30 秒，看人怎麼穿過這裡。" },
    ],
  }),
  ...family({
    prefix: "rest",
    emoji: "⏸️",
    difficulty: "easy",
    kind: "feature",
    direction: "stop_and_watch",
    actionType: "rest",
    concept: "seat",
    role: "rhythm_change",
    hint: "不用特地繞遠。",
    tags: ["rest"],
    variants: [
      { id: "twenty", title: "找個能停 20 秒的位置。" },
      { id: "edge", title: "找個靠邊能停一下的位置。" },
      { id: "shade", title: "找個有遮蔭能停一下的地方。" },
      { id: "short-seat", title: "找個能短暫坐一下的位置。" },
    ],
  }),
];
