import { Platform, StyleSheet } from 'react-native';
import { ABSOLUTE_FILL, BONE, INK, LINE, MUTED, SIGNAL, SOFT } from '../../theme/detour-theme';

export const baseStyles = StyleSheet.create({
  app: { flex: 1 },
  appLight: { backgroundColor: BONE },
  appDark: { backgroundColor: INK },
  animatedRoot: { flex: 1 },
  pressedLight: { opacity: 0.4 },
  bootScreen: {
    flex: 1,
    backgroundColor: BONE,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bootBrand: {
    fontSize: 15,
    fontWeight: '800',
    letterSpacing: 5,
    color: INK,
  },
  ticketFlowTop: {
    minHeight: 46,
    flexDirection: 'row',
    alignItems: 'center',
  },
  ticketFlowBack: {
    width: 34,
    height: 38,
    justifyContent: 'center',
  },
  ticketFlowBackText: {
    fontSize: 26,
    color: INK,
  },
  ticketFlowBrand: {
    marginLeft: 14,
    fontSize: 14,
    fontWeight: '800',
    letterSpacing: 4.2,
    color: INK,
  },
  ticketFlowEyebrow: {
    fontSize: 9,
    fontWeight: '800',
    letterSpacing: 2,
    color: SIGNAL,
  },
  detourTicketShell: {
    marginTop: 34,
    minHeight: 332,
    paddingTop: 20,
    paddingHorizontal: 22,
    paddingBottom: 18,
    backgroundColor: '#FAF7EE',
    borderWidth: 1,
    borderColor: '#D3CEC1',
    position: 'relative',
    overflow: 'hidden',
  },
  detourTicketPunchLeftTop: {
    position: 'absolute',
    left: -10,
    top: 74,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: BONE,
    borderWidth: 1,
    borderColor: '#D3CEC1',
  },
  detourTicketPunchRightTop: {
    position: 'absolute',
    right: -10,
    top: 74,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: BONE,
    borderWidth: 1,
    borderColor: '#D3CEC1',
  },
  detourTicketPunchLeftBottom: {
    position: 'absolute',
    left: -10,
    bottom: 52,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: BONE,
    borderWidth: 1,
    borderColor: '#D3CEC1',
  },
  detourTicketPunchRightBottom: {
    position: 'absolute',
    right: -10,
    bottom: 52,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: BONE,
    borderWidth: 1,
    borderColor: '#D3CEC1',
  },
  detourTicketHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  detourTicketBrand: {
    fontSize: 16,
    fontWeight: '900',
    letterSpacing: 3.3,
    color: INK,
  },
  detourTicketMicro: {
    marginTop: 5,
    fontSize: 7,
    fontWeight: '800',
    letterSpacing: 1.5,
    color: MUTED,
  },
  detourTicketSerial: {
    marginTop: 2,
    fontSize: 8,
    fontWeight: '800',
    letterSpacing: 1.2,
    color: MUTED,
  },
  detourTicketDash: {
    height: 1,
    marginVertical: 18,
    borderTopWidth: 1,
    borderTopColor: '#BDB7AA',
    borderStyle: 'dashed',
  },
  detourTicketFacts: {
    flexDirection: 'row',
    gap: 44,
  },
  detourTicketFact: {
    minWidth: 112,
  },
  detourTicketFactLabel: {
    fontSize: 7,
    fontWeight: '800',
    letterSpacing: 1.3,
    color: MUTED,
  },
  detourTicketFactValue: {
    marginTop: 7,
    fontSize: 17,
    fontWeight: '800',
    color: INK,
  },
  detourTicketGenerating: {
    marginTop: -2,
    fontSize: 8,
    fontWeight: '800',
    letterSpacing: 1.5,
    color: SIGNAL,
  },
  ticketBarcode: {
    height: 34,
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: 3,
  },
  ticketBarcodeBar: {
    height: 34,
    backgroundColor: INK,
  },
  detourTicketFootnote: {
    marginTop: 9,
    fontSize: 7,
    fontWeight: '800',
    letterSpacing: 1.7,
    color: MUTED,
  },
  detourTicketHighlightLabel: {
    fontSize: 7,
    fontWeight: '800',
    letterSpacing: 1.4,
    color: MUTED,
  },
  detourTicketHighlights: {
    marginTop: 10,
    gap: 7,
  },
  detourTicketHighlight: {
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '600',
    color: INK,
  },
  lightScreen: {
    flex: 1,
    backgroundColor: BONE,
    paddingTop: 62,
    paddingHorizontal: 22,
    paddingBottom: 34,
    justifyContent: 'space-between',
  },
  darkScreen: {
    flex: 1,
    backgroundColor: INK,
    paddingTop: 62,
    paddingHorizontal: 22,
    paddingBottom: 34,
    justifyContent: 'space-between',
  },
  brandRow: {
    minHeight: 46,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  darkBrandRow: {
    minHeight: 42,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  brand: {
    fontSize: 14,
    fontWeight: '800',
    letterSpacing: 3.2,
    color: INK,
  },
  brandLight: {
    fontSize: 14,
    fontWeight: '800',
    letterSpacing: 3.2,
    color: BONE,
  },
  meta: {
    marginLeft: 'auto',
    fontSize: 9,
    letterSpacing: 1.8,
    color: MUTED,
  },
  metaLight: {
    marginLeft: 'auto',
    fontSize: 9,
    letterSpacing: 1.8,
    color: '#9A968E',
  },
  backInline: {
    width: 30,
    height: 34,
    justifyContent: 'center',
  },
  backArrow: {
    fontSize: 25,
    lineHeight: 28,
    color: INK,
  },
  signalDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: SIGNAL,
    marginBottom: 18,
  },
  signalDotSmall: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: SIGNAL,
  },
  kicker: {
    maxWidth: 332,
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '600',
    color: '#5A5750',
    marginBottom: 16,
  },
  bottomNote: {
    fontSize: 12,
    lineHeight: 19,
    fontWeight: '600',
    color: '#5A5750',
    maxWidth: '72%',
  },
  sectionTitle: {
    fontSize: 45,
    lineHeight: 50,
    fontWeight: '600',
    letterSpacing: -2.4,
    color: INK,
  },
  randomButton: {
    marginTop: 14,
    height: 52,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: INK,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  randomButtonText: { fontSize: 12, fontWeight: '700', color: INK },
  ticket: {
    minHeight: 88,
    borderTopWidth: 1,
    borderTopColor: LINE,
    flexDirection: 'row',
    alignItems: 'stretch',
  },
  ticketColumn: { flex: 1, paddingTop: 16, paddingRight: 8 },
  ticketDivider: { width: 1, backgroundColor: LINE, marginHorizontal: 8 },
  ticketLabel: { fontSize: 7, letterSpacing: 1.1, color: MUTED },
  ticketValue: { marginTop: 8, fontSize: 11, fontWeight: '700', color: INK },
  primaryButton: {
    height: 68,
    marginTop: 18,
    paddingHorizontal: 20,
    backgroundColor: INK,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  primaryButtonPressed: { opacity: 0.8, transform: [{ scale: 0.985 }] },
  primaryButtonText: { fontSize: 17, fontWeight: '700', color: BONE },
  primaryButtonArrow: { fontSize: 24, color: SIGNAL },
  darkBack: { width: 32, height: 36, justifyContent: 'center' },
  darkBackText: { fontSize: 24, color: BONE },
  contextBadge: {
    marginLeft: 'auto',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  contextBadgeText: { fontSize: 8, letterSpacing: 1.4, color: '#9A968E' },
  threadRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  threadDot: { width: 9, height: 9, borderRadius: 5 },
  threadText: { fontSize: 8, letterSpacing: 1.4, color: '#8E8A82' },
  devPanel: { marginTop: 2, padding: 14, borderWidth: 1, borderColor: '#363430' },
  devPanelTop: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 12 },
  devLabel: { fontSize: 8, letterSpacing: 1.4, color: SIGNAL },
  devValue: { fontSize: 9, color: '#8E8A82' },
  devButton: {
    height: 44,
    paddingHorizontal: 13,
    backgroundColor: '#23221F',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  devButtonPressed: { backgroundColor: '#33312D' },
  devButtonText: { fontSize: 11, color: BONE },
  headingMeta: {
    marginTop: 11,
    fontSize: 7,
    letterSpacing: 1.25,
    color: '#68655E',
  },
  cleanCloseButton: {
    width: 34,
    height: 38,
    justifyContent: 'center',
  },
  cleanCloseText: {
    fontSize: 28,
    lineHeight: 30,
    color: INK,
  },
  cleanBrand: {
    marginLeft: 28,
    fontSize: 14,
    fontWeight: '800',
    letterSpacing: 4,
    color: INK,
  },
  cleanContext: {
    marginLeft: 'auto',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  cleanContextText: {
    fontSize: 9,
    fontWeight: '700',
    letterSpacing: 2,
    color: MUTED,
  },
  cleanArrowButton: {
    width: 154,
    height: 154,
    borderRadius: 77,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 22,
  },
  cleanArrowButtonPressed: {
    backgroundColor: '#E9E5DA',
  },
  cleanArrowRotator: {
    width: 126,
    height: 126,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cleanArrow: {
    fontSize: 94,
    lineHeight: 104,
    color: SIGNAL,
    fontWeight: '300',
  },
  cleanInstruction: {
    marginTop: 30,
    fontSize: 34,
    lineHeight: 42,
    fontWeight: '700',
    letterSpacing: -1.6,
    textAlign: 'center',
    color: INK,
  },
  cleanHint: {
    marginTop: 14,
    maxWidth: 326,
    fontSize: 14,
    lineHeight: 22,
    fontWeight: '500',
    textAlign: 'center',
    color: '#69645C',
  },
  cleanArrowButtonNear: {
    borderWidth: 1,
    borderColor: 'rgba(255,90,54,0.30)',
    backgroundColor: 'rgba(255,90,54,0.05)',
  },
  cleanArrowNear: {
    color: SIGNAL,
  },
  cleanDevBar: {
    height: 58,
    borderTopWidth: 1,
    borderColor: LINE,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  cleanDevLabel: {
    fontSize: 7,
    letterSpacing: 1.6,
    color: SIGNAL,
  },
  cleanDevMeta: {
    marginTop: 4,
    fontSize: 8,
    letterSpacing: 1.1,
    color: MUTED,
  },
  cleanDevButton: {
    minWidth: 126,
    height: 38,
    paddingHorizontal: 12,
    backgroundColor: INK,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  cleanDevButtonPressed: {
    opacity: 0.55,
  },
  cleanDevButtonText: {
    fontSize: 10,
    color: BONE,
  },
  fieldEventScreen: {
    flex: 1,
    backgroundColor: BONE,
    paddingTop: 62,
    paddingHorizontal: 22,
    paddingBottom: 34,
  },
  fieldEventTop: {
    minHeight: 42,
    flexDirection: 'row',
    alignItems: 'center',
  },
  fieldEventBack: {
    width: 34,
    height: 38,
    justifyContent: 'center',
  },
  fieldEventBackText: {
    fontSize: 26,
    color: INK,
  },
  fieldEventBrand: {
    marginLeft: 28,
    fontSize: 14,
    fontWeight: '800',
    letterSpacing: 4,
    color: INK,
  },
  fieldEventMeta: {
    marginLeft: 'auto',
    fontSize: 8,
    fontWeight: '700',
    letterSpacing: 1.7,
    color: MUTED,
  },
  fieldEventScroll: {
    flex: 1,
  },
  fieldEventScrollContent: {
    paddingTop: 38,
    paddingBottom: 24,
  },
  fieldEventEyebrow: {
    fontSize: 9,
    fontWeight: '800',
    letterSpacing: 1.8,
    color: SIGNAL,
  },
  fieldEventTitle: {
    marginTop: 16,
    maxWidth: 350,
    fontSize: 42,
    lineHeight: 48,
    fontWeight: '700',
    letterSpacing: -2.2,
    color: INK,
  },
  fieldEventInstruction: {
    marginTop: 24,
    maxWidth: 345,
    fontSize: 17,
    lineHeight: 28,
    fontWeight: '500',
    color: '#5A5750',
  },
  fieldEventRule: {
    marginTop: 28,
    paddingTop: 17,
    borderTopWidth: 1,
    borderTopColor: LINE,
  },
  fieldEventRuleLabel: {
    fontSize: 8,
    fontWeight: '800',
    letterSpacing: 1.6,
    color: MUTED,
  },
  fieldEventRuleText: {
    marginTop: 9,
    maxWidth: 340,
    fontSize: 14,
    lineHeight: 22,
    fontWeight: '700',
    color: INK,
  },
  fieldEventContextNote: {
    marginTop: 18,
    maxWidth: 330,
    fontSize: 11,
    lineHeight: 18,
    color: MUTED,
  },
  fieldEventBottom: {
    gap: 9,
  },
  fieldEventActions: {
    flexDirection: 'row',
    gap: 10,
  },
  fieldEventPrimary: {
    minHeight: 64,
    paddingHorizontal: 18,
    backgroundColor: BONE,
    borderWidth: 1,
    borderColor: INK,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  fieldEventPrimaryFlexible: {
    flex: 1,
  },
  fieldEventPrimaryText: {
    fontSize: 15,
    fontWeight: '700',
    color: INK,
  },
  fieldEventPrimaryArrow: {
    fontSize: 22,
    color: SIGNAL,
  },
  fieldEventSkip: {
    minHeight: 36,
    alignItems: 'center',
    justifyContent: 'center',
  },
  fieldEventSkipText: {
    fontSize: 10,
    color: MUTED,
  },
  contextNote: { fontSize: 10, lineHeight: 17, color: '#77736B' },
  shutterInner: { width: 62, height: 62, borderRadius: 31, backgroundColor: BONE },
  shutterDisabled: { opacity: 0.35 },
  shutterPressed: { transform: [{ scale: 0.94 }] },
  reviewScreen: { flex: 1, backgroundColor: '#000' },
  reviewImage: { ...ABSOLUTE_FILL },
  reviewShade: { ...ABSOLUTE_FILL, backgroundColor: 'rgba(0,0,0,0.18)' },
  reviewTop: {
    position: 'absolute',
    top: 60,
    left: 20,
    right: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  reviewBrand: { fontSize: 13, fontWeight: '800', letterSpacing: 2.8, color: '#fff' },
  reviewMeta: { fontSize: 8, letterSpacing: 1.5, color: '#fff' },
  reviewBottom: {
    position: 'absolute',
    left: 16,
    right: 16,
    bottom: 28,
    padding: 18,
    backgroundColor: 'rgba(17,17,15,0.86)',
  },
  reviewTitle: { marginTop: 9, fontSize: 27, fontWeight: '700', color: BONE },
  reviewLibraryHint: {
    marginTop: 8,
    maxWidth: 300,
    fontSize: 10,
    lineHeight: 16,
    color: '#BDB8AE',
  },
  reviewActions: { marginTop: 18, flexDirection: 'row', gap: 10 },
  reviewSecondary: {
    flex: 1,
    height: 54,
    borderWidth: 1,
    borderColor: '#625F58',
    alignItems: 'center',
    justifyContent: 'center',
  },
  reviewPrimary: {
    flex: 1.5,
    height: 54,
    paddingHorizontal: 14,
    backgroundColor: BONE,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  reviewSecondaryText: { fontSize: 13, fontWeight: '700', color: BONE },
  reviewPrimaryText: { fontSize: 13, fontWeight: '700', color: INK },
  reviewPressed: { opacity: 0.75 },
  reissueScreen: {
    flex: 1,
    backgroundColor: BONE,
    paddingTop: 58,
    paddingHorizontal: 22,
  },
  reissueScreenDark: {
    backgroundColor: '#050505',
  },
  reissueTop: {
    minHeight: 46,
    flexDirection: 'row',
    alignItems: 'center',
  },
  reissueBack: {
    width: 34,
    height: 38,
    justifyContent: 'center',
  },
  reissueBackText: {
    fontSize: 26,
    color: INK,
  },
  reissueBackTextDark: {
    color: BONE,
  },
  reissueBrand: {
    marginLeft: 14,
    fontSize: 14,
    fontWeight: '800',
    letterSpacing: 4.2,
    color: INK,
  },
  reissueBrandDark: {
    color: BONE,
  },
  reissueMeta: {
    marginLeft: 'auto',
    fontSize: 8,
    fontWeight: '800',
    letterSpacing: 1.6,
    color: SIGNAL,
  },
  reissueScroll: {
    paddingTop: 28,
    paddingBottom: 42,
  },
  reissueEyebrow: {
    fontSize: 9,
    fontWeight: '800',
    letterSpacing: 1.8,
    color: SIGNAL,
  },
  reissueTitle: {
    marginTop: 12,
    fontSize: 40,
    lineHeight: 45,
    fontWeight: '700',
    letterSpacing: -2.2,
    color: INK,
  },
  reissueTitleDark: {
    color: BONE,
  },
  reissueBody: {
    marginTop: 16,
    maxWidth: 342,
    fontSize: 14,
    lineHeight: 22,
    color: '#67625A',
  },
  reissueBodyDark: {
    color: '#B2ACA2',
  },
  reissueChoiceLabel: {
    marginTop: 30,
    marginBottom: 12,
    fontSize: 12,
    fontWeight: '800',
    color: INK,
  },
  reissueChoiceLabelDark: {
    color: BONE,
  },
  reissueGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  reissueChoice: {
    width: '48.5%',
    minHeight: 132,
    padding: 14,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: LINE,
    backgroundColor: '#F7F4EB',
  },
  reissueChoiceDark: {
    borderColor: '#3B3731',
    backgroundColor: '#131210',
  },
  reissueChoicePressed: {
    opacity: 0.6,
    transform: [{ translateY: 2 }],
  },
  reissueChoiceTop: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  reissueChoiceMark: {
    fontSize: 22,
    lineHeight: 24,
    color: SIGNAL,
  },
  reissueChoiceIndex: {
    fontSize: 8,
    fontWeight: '800',
    letterSpacing: 1,
    color: MUTED,
  },
  reissueChoiceIndexDark: {
    color: '#989289',
  },
  reissueChoiceTitle: {
    marginTop: 24,
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '700',
    color: INK,
  },
  reissueChoiceTitleDark: {
    color: BONE,
  },
  reissueChoiceNote: {
    marginTop: 6,
    fontSize: 10,
    lineHeight: 15,
    color: MUTED,
  },
  reissueChoiceNoteDark: {
    color: '#AAA49B',
  },
  reissueLoadingCard: {
    marginTop: 14,
    padding: 14,
    borderRadius: 14,
    backgroundColor: '#FFF0E9',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  reissueLoadingCardDark: {
    backgroundColor: 'rgba(255,90,54,0.13)',
  },
  reissueLoadingDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: SIGNAL,
  },
  reissueLoadingText: {
    flex: 1,
    fontSize: 11,
    lineHeight: 17,
    color: INK,
  },
  reissueLoadingTextDark: {
    color: BONE,
  },
  ticketFlowBackTextDark: {
    color: BONE,
  },
  ticketFlowBrandDark: {
    color: BONE,
  },
  photoStripSectionDark: {
    borderTopColor: '#35312C',
  },
  photoStripLabelDark: {
    color: BONE,
  },
  photoStripMetaDark: {
    color: '#A19C92',
  },
  photoThumbCodeDark: {
    color: '#C1BBB1',
  }
});
