import { Platform, StyleSheet } from 'react-native';
import { ABSOLUTE_FILL, BONE, INK, LINE, MUTED, SIGNAL, SOFT } from '../../theme/detour-theme';

export const collectionStyles = StyleSheet.create({
  routePassportButton: {
    minWidth: 54,
    height: 42,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  routePassportRing: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: SIGNAL,
    alignItems: 'center',
    justifyContent: 'center',
  },
  routePassportRingInner: {
    width: 17,
    height: 17,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: SIGNAL,
  },
  routePassportBadge: {
    minWidth: 24,
    height: 20,
    paddingHorizontal: 5,
    borderRadius: 10,
    backgroundColor: SOFT,
    alignItems: 'center',
    justifyContent: 'center',
  },
  routePassportBadgeText: {
    fontSize: 9,
    fontWeight: '800',
    color: INK,
  },
  homePassportButton: {
    minHeight: 46,
    paddingLeft: 11,
    paddingRight: 13,
    borderWidth: 1,
    borderColor: INK,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
  },
  homePassportStamp: {
    fontSize: 21,
    lineHeight: 24,
    color: SIGNAL,
  },
  homePassportLabel: {
    fontSize: 9,
    fontWeight: '800',
    letterSpacing: 1.4,
    color: INK,
  },
  homePassportMeta: {
    marginTop: 3,
    fontSize: 7,
    fontWeight: '600',
    letterSpacing: 0.8,
    color: MUTED,
  },
  postcardFacts: {
    marginTop: 22,
    marginBottom: 26,
    paddingTop: 16,
    paddingBottom: 16,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: LINE,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  postcardFact: {
    minWidth: 82,
  },
  postcardFactLabel: {
    fontSize: 7,
    letterSpacing: 1.4,
    color: MUTED,
  },
  postcardFactValue: {
    marginTop: 6,
    fontSize: 14,
    fontWeight: '700',
    color: INK,
  },
  postcardMapLegend: {
    marginTop: 10,
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  postcardLegendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  postcardLegendPlanned: {
    width: 18,
    height: 2,
    backgroundColor: '#9D998F',
  },
  postcardLegendActual: {
    width: 18,
    height: 3,
    backgroundColor: SIGNAL,
  },
  postcardLegendText: {
    fontSize: 7,
    letterSpacing: 1.1,
    color: MUTED,
  },
  postcardRerouteMeta: {
    marginLeft: 'auto',
    fontSize: 7,
    letterSpacing: 1,
    color: MUTED,
  },
  completeRule: {
    marginTop: 28,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: '#34332F',
  },
  completeRuleLabel: { fontSize: 8, letterSpacing: 1.4, color: '#77736B' },
  completeRuleText: { marginTop: 9, fontSize: 13, lineHeight: 21, color: BONE },
  missionCompleteButton: {
    height: 66,
    paddingHorizontal: 18,
    backgroundColor: BONE,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  missionCompleteButtonPressed: { opacity: 0.82 },
  missionCompleteText: { fontSize: 15, fontWeight: '700', color: INK },
  missionCompleteArrow: { fontSize: 22, color: SIGNAL },
  optionalCompleteButton: {
    flex: 1,
    minHeight: 70,
    paddingHorizontal: 18,
    backgroundColor: BONE,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  optionalCompleteText: {
    fontSize: 16,
    fontWeight: '700',
    color: INK,
  },
  optionalCompleteArrow: { fontSize: 22, color: SIGNAL },
  passportCardScene: {
    marginTop: 8,
    fontSize: 10,
    lineHeight: 16,
    color: MUTED,
  },
  postcardDetailScene: {
    marginTop: 12,
    fontSize: 9,
    letterSpacing: 1.2,
    color: SIGNAL,
  },
  postcardRecoverySection: {
    marginTop: 26,
    paddingTop: 18,
    borderTopWidth: 1,
    borderColor: LINE,
  },
  postcardRecoveryText: {
    marginTop: 10,
    fontSize: 12,
    lineHeight: 20,
    color: MUTED,
  },
  completeScreen: {
    flex: 1,
    backgroundColor: BONE,
    paddingTop: 58,
    paddingHorizontal: 22,
  },
  completeScreenDark: {
    backgroundColor: '#050505',
  },
  completeTop: {
    minHeight: 46,
    flexDirection: 'row',
    alignItems: 'center',
  },
  completeBrand: {
    fontSize: 14,
    fontWeight: '800',
    letterSpacing: 4.2,
    color: INK,
  },
  completeBrandDark: {
    color: BONE,
  },
  completeMeta: {
    marginLeft: 'auto',
    fontSize: 8,
    fontWeight: '800',
    letterSpacing: 1.6,
    color: SIGNAL,
  },
  completeScroll: {
    paddingTop: 30,
    paddingBottom: 44,
  },
  completeHero: {
    paddingBottom: 26,
  },
  completeEyebrow: {
    fontSize: 9,
    fontWeight: '800',
    letterSpacing: 1.8,
    color: SIGNAL,
  },
  completeTitle: {
    marginTop: 12,
    fontSize: 43,
    lineHeight: 48,
    fontWeight: '700',
    letterSpacing: -2.4,
    color: INK,
  },
  completeTitleDark: {
    color: BONE,
  },
  completeBody: {
    marginTop: 16,
    maxWidth: 344,
    fontSize: 14,
    lineHeight: 23,
    color: '#67625A',
  },
  completeBodyDark: {
    color: '#B2ACA2',
  },
  completeTicket: {
    minHeight: 362,
    padding: 20,
    borderWidth: 1,
    borderColor: '#D3CEC1',
    backgroundColor: '#FAF7EE',
    position: 'relative',
    overflow: 'hidden',
  },
  completeTicketDark: {
    borderColor: '#3B3731',
    backgroundColor: '#12110F',
  },
  completeTicketPunchLeftTop: {
    position: 'absolute',
    left: -10,
    top: 72,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: BONE,
    borderWidth: 1,
    borderColor: '#D3CEC1',
  },
  completeTicketPunchRightTop: {
    position: 'absolute',
    right: -10,
    top: 72,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: BONE,
    borderWidth: 1,
    borderColor: '#D3CEC1',
  },
  completeTicketPunchLeftBottom: {
    position: 'absolute',
    left: -10,
    bottom: 52,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: BONE,
    borderWidth: 1,
    borderColor: '#D3CEC1',
  },
  completeTicketPunchRightBottom: {
    position: 'absolute',
    right: -10,
    bottom: 52,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: BONE,
    borderWidth: 1,
    borderColor: '#D3CEC1',
  },
  completeTicketPunchDark: {
    backgroundColor: '#050505',
    borderColor: '#3B3731',
  },
  completeTicketHead: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  completeTicketBrand: {
    fontSize: 17,
    fontWeight: '900',
    letterSpacing: 3.5,
    color: INK,
  },
  completeTicketBrandDark: {
    color: BONE,
  },
  completeTicketStatus: {
    marginTop: 5,
    fontSize: 7,
    fontWeight: '900',
    letterSpacing: 1.5,
    color: SIGNAL,
  },
  completeStamp: {
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderWidth: 2,
    borderColor: SIGNAL,
    transform: [{ rotate: '-5deg' }],
  },
  completeStampText: {
    fontSize: 8,
    fontWeight: '900',
    letterSpacing: 1.4,
    color: SIGNAL,
  },
  completeDash: {
    height: 1,
    marginVertical: 18,
    borderTopWidth: 1,
    borderTopColor: '#BDB7AA',
    borderStyle: 'dashed',
  },
  completeDashDark: {
    borderTopColor: '#454038',
  },
  completeRouteGraphic: {
    height: 44,
    flexDirection: 'row',
    alignItems: 'center',
  },
  completeRouteStart: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: SIGNAL,
  },
  completeRouteLineOne: {
    width: '38%',
    height: 3,
    backgroundColor: SIGNAL,
    transform: [{ rotate: '4deg' }],
  },
  completeRouteNode: {
    width: 15,
    height: 15,
    borderRadius: 8,
    borderWidth: 3,
    borderColor: SIGNAL,
  },
  completeRouteLineTwo: {
    flex: 1,
    height: 3,
    backgroundColor: SIGNAL,
    transform: [{ rotate: '-5deg' }],
  },
  completeRouteFinish: {
    width: 26,
    height: 26,
    borderRadius: 13,
    borderWidth: 2,
    borderColor: SIGNAL,
    alignItems: 'center',
    justifyContent: 'center',
  },
  completeRouteFinishCore: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: SIGNAL,
  },
  completeDestinationLabel: {
    marginTop: 8,
    fontSize: 7,
    fontWeight: '800',
    letterSpacing: 1.4,
    color: MUTED,
  },
  completeDestinationLabelDark: {
    color: '#979188',
  },
  completeDestination: {
    marginTop: 6,
    fontSize: 21,
    lineHeight: 26,
    fontWeight: '800',
    color: INK,
  },
  completeDestinationDark: {
    color: BONE,
  },
  completeFacts: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  completeFact: {
    width: '31%',
  },
  completeFactLabel: {
    fontSize: 7,
    fontWeight: '800',
    letterSpacing: 1.2,
    color: MUTED,
  },
  completeFactLabelDark: {
    color: '#979188',
  },
  completeFactValue: {
    marginTop: 7,
    fontSize: 13,
    fontWeight: '800',
    color: INK,
  },
  completeFactValueDark: {
    color: BONE,
  },
  completeBarcodeRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
  },
  completeBarcode: {
    height: 28,
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: 3,
  },
  completeBarcodeBar: {
    height: 28,
    backgroundColor: INK,
  },
  completeBarcodeBarDark: {
    backgroundColor: BONE,
  },
  completeSerial: {
    fontSize: 7,
    fontWeight: '800',
    letterSpacing: 1.1,
    color: MUTED,
  },
  completeSerialDark: {
    color: '#979188',
  },
  completeFramesSection: {
    marginTop: 26,
  },
  completeSectionHead: {
    marginBottom: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  completeSectionLabel: {
    fontSize: 8,
    fontWeight: '800',
    letterSpacing: 1.4,
    color: INK,
  },
  completeSectionLabelDark: {
    color: BONE,
  },
  completeSectionMeta: {
    fontSize: 8,
    letterSpacing: 1.1,
    color: MUTED,
  },
  completeSectionMetaDark: {
    color: '#979188',
  },
  completeFrames: {
    gap: 10,
    paddingRight: 20,
  },
  completeFrameWrap: {
    width: 118,
  },
  completeFrame: {
    width: 118,
    height: 154,
    backgroundColor: SOFT,
  },
  completeFrameCode: {
    marginTop: 6,
    fontSize: 7,
    letterSpacing: 1.1,
    color: INK,
  },
  completeFrameCodeDark: {
    color: '#B5AFA5',
  },
  playtestFeedbackPanel: {
    marginTop: 28,
    paddingVertical: 24,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: LINE,
  },
  playtestFeedbackCode: {
    fontSize: 8,
    fontWeight: '800',
    letterSpacing: 1.6,
    color: SIGNAL,
  },
  playtestFeedbackTitle: {
    marginTop: 10,
    fontSize: 27,
    lineHeight: 32,
    fontWeight: '800',
    letterSpacing: -1.1,
    color: INK,
  },
  playtestFeedbackBody: {
    marginTop: 7,
    fontSize: 12,
    lineHeight: 19,
    color: MUTED,
  },
  playtestRatingRow: {
    marginTop: 17,
    flexDirection: 'row',
    gap: 8,
  },
  playtestRatingButton: {
    flex: 1,
    minHeight: 48,
    borderWidth: 1,
    borderColor: LINE,
    alignItems: 'center',
    justifyContent: 'center',
  },
  playtestRatingButtonActive: {
    borderColor: SIGNAL,
    backgroundColor:
      'rgba(255,90,54,0.07)',
  },
  playtestRatingText: {
    fontSize: 12,
    fontWeight: '700',
    color: INK,
  },
  playtestRatingTextActive: {
    color: SIGNAL,
  },
  playtestReasonBlock: {
    marginTop: 20,
  },
  playtestReasonLabel: {
    marginBottom: 10,
    fontSize: 8,
    fontWeight: '800',
    letterSpacing: 1.1,
    color: MUTED,
  },
  playtestReasonRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  playtestReasonChip: {
    minHeight: 38,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: LINE,
    alignItems: 'center',
    justifyContent: 'center',
  },
  playtestReasonChipActive: {
    borderColor: SIGNAL,
  },
  playtestReasonText: {
    fontSize: 11,
    fontWeight: '600',
    color: MUTED,
  },
  playtestReasonTextActive: {
    color: SIGNAL,
  },
  completeActions: {
    gap: 10,
    marginTop: 22,
  },
  completePostcardButton: {
    minHeight: 58,
    paddingHorizontal: 18,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: INK,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  completePostcardButtonDark: {
    borderColor: '#4A453E',
  },
  completePostcardText: {
    fontSize: 14,
    fontWeight: '700',
    color: INK,
  },
  completePostcardTextDark: {
    color: BONE,
  },
  completePostcardArrow: {
    fontSize: 19,
    color: SIGNAL,
  },
  completeHomeButton: {
    minHeight: 66,
    paddingHorizontal: 19,
    borderRadius: 16,
    backgroundColor: SIGNAL,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  completeHomeText: {
    fontSize: 17,
    fontWeight: '800',
    color: '#130F0B',
  },
  completeHomeArrow: {
    fontSize: 23,
    color: '#130F0B',
  },
  completePressed: {
    opacity: 0.76,
    transform: [{ translateY: 2 }],
  },
  passportScreen: {
    flex: 1,
    backgroundColor: BONE,
    paddingTop: 62,
    paddingHorizontal: 22,
  },
  passportScroll: { paddingTop: 34, paddingBottom: 54 },
  passportHero: { paddingBottom: 42 },
  passportKicker: { fontSize: 11, letterSpacing: 1.3, color: MUTED, marginBottom: 18 },
  passportTitle: {
    fontSize: 43,
    lineHeight: 49,
    fontWeight: '600',
    letterSpacing: -2.4,
    color: INK,
  },
  passportStats: {
    minHeight: 106,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: LINE,
    flexDirection: 'row',
  },
  passportStat: { flex: 1, justifyContent: 'center' },
  passportStatValue: { fontSize: 28, fontWeight: '700', color: INK },
  passportStatLabel: { marginTop: 6, fontSize: 7, letterSpacing: 1.2, color: MUTED },
  passportSectionHeader: {
    marginTop: 40,
    marginBottom: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  passportSectionTitle: { fontSize: 9, fontWeight: '800', letterSpacing: 1.7, color: INK },
  passportSectionMeta: { fontSize: 7, letterSpacing: 1.2, color: MUTED },
  emptyPassport: {
    minHeight: 220,
    borderTopWidth: 1,
    borderTopColor: LINE,
    paddingTop: 26,
  },
  emptyPassportNumber: { fontSize: 86, fontWeight: '800', color: '#DEDBD0' },
  emptyPassportTitle: { marginTop: 20, fontSize: 24, fontWeight: '600', color: INK },
  passportList: { borderTopWidth: 1, borderTopColor: LINE },
  passportCard: {
    minHeight: 165,
    paddingVertical: 20,
    borderBottomWidth: 1,
    borderBottomColor: LINE,
  },
  passportCardTop: { flexDirection: 'row', justifyContent: 'space-between' },
  passportCardNumber: { fontSize: 10, letterSpacing: 1.4, color: SIGNAL, fontWeight: '700' },
  passportCardDate: { fontSize: 8, letterSpacing: 1.1, color: MUTED },
  passportCardMode: { marginTop: 22, fontSize: 31, fontWeight: '800', color: INK },
  passportCardTitle: { marginTop: 4, fontSize: 13, color: INK },
  passportCardBottom: { marginTop: 22, flexDirection: 'row', justifyContent: 'space-between' },
  passportCardMeta: { fontSize: 8, letterSpacing: 1, color: MUTED },
  passportCardPressed: {
    opacity: 0.5,
    transform: [{ scale: 0.992 }],
  },
  passportOpenRow: {
    marginTop: 18,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: LINE,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  passportOpenText: {
    fontSize: 7,
    fontWeight: '800',
    letterSpacing: 1.4,
    color: SIGNAL,
  },
  passportOpenArrow: {
    fontSize: 15,
    color: SIGNAL,
  },
  postcardDetailScreen: {
    flex: 1,
    backgroundColor: BONE,
    paddingTop: 62,
    paddingHorizontal: 22,
  },
  postcardDetailScroll: {
    paddingTop: 34,
    paddingBottom: 60,
  },
  postcardDetailHero: {
    paddingBottom: 34,
    borderBottomWidth: 1,
    borderBottomColor: LINE,
  },
  postcardDetailKicker: {
    fontSize: 9,
    letterSpacing: 1.4,
    color: MUTED,
    marginBottom: 16,
  },
  postcardDetailTitle: {
    fontSize: 50,
    lineHeight: 54,
    fontWeight: '800',
    letterSpacing: -2.8,
    color: INK,
  },
  postcardDetailMeta: {
    marginTop: 10,
    fontSize: 12,
    lineHeight: 19,
    color: MUTED,
  },
  postcardSectionHeader: {
    marginBottom: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  postcardSectionLabel: {
    fontSize: 8,
    fontWeight: '800',
    letterSpacing: 1.6,
    color: INK,
  },
  postcardSectionMeta: {
    fontSize: 7,
    letterSpacing: 1.2,
    color: MUTED,
  },
  postcardPhotoSection: {
    marginTop: 34,
  },
  postcardHeroPhoto: {
    width: '100%',
    aspectRatio: 4 / 5,
    backgroundColor: SOFT,
  },
  postcardPhotoStrip: {
    gap: 10,
    paddingTop: 12,
    paddingRight: 22,
  },
  postcardPhotoItem: {
    width: 116,
  },
  postcardPhotoThumb: {
    width: 116,
    height: 145,
    backgroundColor: SOFT,
  },
  postcardPhotoCode: {
    marginTop: 6,
    fontSize: 7,
    letterSpacing: 1.1,
    color: MUTED,
  },
  postcardLegacyBlock: {
    marginTop: 34,
    padding: 18,
    borderWidth: 1,
    borderColor: LINE,
  },
  postcardLegacyText: {
    marginTop: 12,
    fontSize: 12,
    lineHeight: 20,
    color: MUTED,
  },
  postcardMapSection: {
    marginTop: 38,
  },
  postcardMapShell: {
    height: 230,
    overflow: 'hidden',
    backgroundColor: SOFT,
  },
  postcardMap: {
    ...ABSOLUTE_FILL,
  },
  postcardMissionSection: {
    marginTop: 38,
    borderTopWidth: 1,
    borderTopColor: LINE,
    paddingTop: 16,
  },
  postcardMissionRow: {
    minHeight: 86,
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: LINE,
    flexDirection: 'row',
  },
  postcardMissionNumber: {
    width: 38,
    fontSize: 8,
    letterSpacing: 1.2,
    color: SIGNAL,
  },
  postcardMissionCopy: {
    flex: 1,
  },
  postcardMissionCodeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
  },
  postcardMissionCode: {
    fontSize: 7,
    fontWeight: '800',
    letterSpacing: 1.4,
    color: MUTED,
  },
  postcardMissionResult: {
    fontSize: 7,
    letterSpacing: 1.1,
    color: MUTED,
  },
  postcardMissionResultSkipped: { color: '#9B4B36' },
  postcardMissionTitle: {
    marginTop: 7,
    fontSize: 17,
    lineHeight: 24,
    fontWeight: '600',
    color: INK,
  },
  clearPassportButton: {
    marginTop: 30,
    paddingVertical: 16,
    borderTopWidth: 1,
    borderTopColor: LINE,
  },
  clearPassportText: { fontSize: 8, letterSpacing: 1.2, color: SIGNAL },
  routePassportButtonDark: {
    borderRadius: 22,
  },
  routePassportBadgeDark: {
    backgroundColor: '#26221D',
  },
  routePassportBadgeTextDark: {
    color: BONE,
  },
  finishScreenDark: {
    backgroundColor: '#050505',
  },
  finishBrandDark: {
    color: BONE,
  },
  finishMetaDark: {
    color: '#A19C92',
  },
  finishTitleDark: {
    color: BONE,
  },
  finishBodyDark: {
    color: '#AFA99F',
  },
  finishTicketDark: {
    borderColor: '#35312C',
  },
  finishTicketLabelDark: {
    color: '#9B968D',
  },
  finishTicketValueDark: {
    color: BONE,
  },
  finishPassportButtonDark: {
    borderColor: '#4A453E',
  },
  finishPassportTextDark: {
    color: BONE,
  },
  finishButtonDark: {
    backgroundColor: SIGNAL,
  },
  finishButtonTextDark: {
    color: '#130F0B',
  }
});
