import { StyleSheet } from 'react-native';

import { INK, MUTED, SIGNAL } from '../../theme/detour-theme';

const SCREEN = '#F5F1E8';
const PAPER = '#FBF7EE';
const PAPER_ALT = '#EAE4D9';
const LINE = '#CFC6B9';

export const journeySummaryStyles = StyleSheet.create({
  v56SummaryCard: {
    width: '100%',
    overflow: 'hidden',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: LINE,
    borderLeftWidth: 4,
    borderLeftColor: SIGNAL,
    backgroundColor: PAPER,
    shadowColor: '#000',
    shadowOpacity: 0.07,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
  },
  v56SummaryHeader: {
    minHeight: 54,
    paddingHorizontal: 15,
    flexDirection: 'row',
    alignItems: 'center',
  },
  v56SummaryBrand: {
    flex: 1.1,
    fontSize: 16,
    fontWeight: '900',
    letterSpacing: 1.6,
    color: INK,
  },
  v56SummaryStatus: {
    flex: 0.9,
    textAlign: 'center',
    fontSize: 13,
    fontWeight: '900',
    color: SIGNAL,
  },
  v56SummaryDate: {
    flex: 1.2,
    textAlign: 'right',
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '800',
    color: MUTED,
  },
  v56SummaryRule: {
    marginHorizontal: 14,
    borderTopWidth: 1,
    borderColor: '#BEB5A8',
  },
  v56SummaryHero: {
    marginHorizontal: 14,
    marginTop: 14,
    aspectRatio: 1.72,
    borderRadius: 10,
    overflow: 'hidden',
    backgroundColor: PAPER_ALT,
  },
  v56ZoomScroll: {
    width: '100%',
    height: '100%',
    backgroundColor: PAPER_ALT,
  },
  v56ZoomContent: {
    flexGrow: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  v56HeroPhoto: {
    width: '100%',
    height: '100%',
    backgroundColor: PAPER_ALT,
  },
  v56ThumbScroller: {
    marginTop: 10,
    marginHorizontal: 14,
  },
  v56ThumbContent: {
    gap: 8,
    paddingBottom: 2,
  },
  v56ThumbPress: {
    width: 66,
    height: 52,
    borderRadius: 7,
    overflow: 'hidden',
  },
  v56ThumbPhoto: {
    width: '100%',
    height: '100%',
    borderRadius: 7,
    borderWidth: 1,
    borderColor: '#C9C0B3',
    opacity: 0.58,
    backgroundColor: PAPER_ALT,
  },
  v56ThumbPhotoActive: {
    borderWidth: 2,
    borderColor: SIGNAL,
    opacity: 1,
  },
  v56SummaryCopy: {
    paddingHorizontal: 18,
    paddingTop: 16,
  },
  v56SummaryMood: {
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderWidth: 1,
    borderColor: SIGNAL,
    borderRadius: 4,
    fontSize: 13,
    lineHeight: 17,
    fontWeight: '900',
    color: SIGNAL,
  },
  v56SummaryDestination: {
    marginTop: 8,
    fontSize: 31,
    lineHeight: 36,
    fontWeight: '900',
    letterSpacing: -1.1,
    color: INK,
  },
  v56SummaryFacts: {
    minHeight: 52,
    marginTop: 14,
    flexDirection: 'row',
    alignItems: 'stretch',
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: '#C8BFB2',
  },
  v56SummaryFactCell: {
    flex: 1,
    minHeight: 52,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  v56SummaryFactDivider: {
    position: 'absolute',
    left: 0,
    top: 11,
    bottom: 11,
    width: 1,
    backgroundColor: SIGNAL,
  },
  v56SummaryFactText: {
    fontSize: 14,
    lineHeight: 18,
    fontWeight: '900',
    color: INK,
  },
  v56SummaryRoutePanel: {
    marginHorizontal: 18,
    marginTop: 12,
    marginBottom: 16,
    height: 94,
    borderRadius: 9,
    overflow: 'hidden',
    backgroundColor: PAPER_ALT,
    position: 'relative',
  },
  v56SummaryRouteLabel: {
    position: 'absolute',
    left: 11,
    top: 10,
    zIndex: 2,
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: 'rgba(251,247,238,0.94)',
    fontSize: 11,
    fontWeight: '900',
    color: INK,
  },
  v56SummaryRouteGraphic: {
    flex: 1,
  },
  v56RouteMissing: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
    backgroundColor: PAPER_ALT,
  },
  v56RouteMissingText: {
    fontSize: 15,
    fontWeight: '800',
    color: MUTED,
    textAlign: 'center',
  },
  v56RouteMissingCompact: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  v56RouteMissingCompactText: {
    fontSize: 9,
    fontWeight: '800',
    color: MUTED,
  },

  v56FinishActions: {
    marginTop: 22,
    flexDirection: 'row',
    gap: 10,
  },
  v56FinishReviewButton: {
    flex: 1,
    minHeight: 60,
    borderRadius: 30,
    borderWidth: 2,
    borderColor: SIGNAL,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  v56FinishReviewText: {
    fontSize: 17,
    fontWeight: '900',
    color: INK,
  },
  v56FinishShareButton: {
    flex: 1,
    minHeight: 60,
    borderRadius: 30,
    backgroundColor: SIGNAL,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  v56FinishShareText: {
    fontSize: 17,
    fontWeight: '900',
    color: INK,
  },
  v56FinishHomeLink: {
    minHeight: 50,
    marginTop: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  v56FinishHomeLinkText: {
    fontSize: 16,
    fontWeight: '800',
    color: MUTED,
  },

  v56HistoryScreen: {
    flex: 1,
    backgroundColor: SCREEN,
    paddingTop: 58,
  },
  v56HistoryTop: {
    height: 58,
    paddingHorizontal: 22,
    flexDirection: 'row',
    alignItems: 'center',
  },
  v56HistoryBack: {
    width: 54,
    height: 54,
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  v56HistoryBackText: {
    fontSize: 34,
    lineHeight: 38,
    color: INK,
  },
  v56HistoryBrand: {
    flex: 1,
    fontSize: 30,
    lineHeight: 34,
    fontWeight: '900',
    letterSpacing: -1.1,
    color: INK,
  },
  v56HistoryMenu: {
    width: 54,
  },
  v56HistoryScroll: {
    paddingHorizontal: 18,
    paddingTop: 24,
    paddingBottom: 80,
  },
  v56HistoryTitle: {
    fontSize: 44,
    lineHeight: 50,
    fontWeight: '900',
    letterSpacing: -2,
    color: INK,
  },
  v56HistorySubtitle: {
    marginTop: 8,
    marginBottom: 26,
    fontSize: 16,
    lineHeight: 23,
    fontWeight: '700',
    color: MUTED,
  },
  v56HistoryList: {
    gap: 12,
  },
  v56HistoryTicket: {
    minHeight: 170,
    flexDirection: 'row',
    borderWidth: 1,
    borderColor: '#D3CABD',
    borderRadius: 9,
    backgroundColor: PAPER,
    overflow: 'hidden',
    position: 'relative',
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 7,
    shadowOffset: { width: 0, height: 3 },
    elevation: 2,
  },
  v56HistoryTicketFeatured: {
    borderColor: SIGNAL,
    borderLeftWidth: 4,
    borderLeftColor: SIGNAL,
  },
  v56HistoryTicketMain: {
    flex: 1,
    paddingHorizontal: 14,
    paddingTop: 13,
    paddingBottom: 11,
  },
  v56HistoryTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  v56HistoryMood: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderWidth: 1,
    borderColor: SIGNAL,
    borderRadius: 3,
    fontSize: 11,
    lineHeight: 14,
    fontWeight: '900',
    color: SIGNAL,
  },
  v56HistoryDate: {
    fontSize: 10,
    lineHeight: 14,
    fontWeight: '800',
    color: MUTED,
  },
  v56HistoryMiddleRow: {
    flex: 1,
    minHeight: 69,
    flexDirection: 'row',
    alignItems: 'center',
  },
  v56HistoryDestinationWrap: {
    flex: 1.15,
    paddingRight: 8,
  },
  v56HistoryDestination: {
    fontSize: 24,
    lineHeight: 29,
    fontWeight: '900',
    letterSpacing: -0.8,
    color: INK,
  },
  v56HistoryRoute: {
    flex: 0.85,
    height: 58,
  },
  v56HistoryFacts: {
    minHeight: 35,
    flexDirection: 'row',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: '#CFC6B9',
  },
  v56HistoryFact: {
    flex: 1,
    textAlign: 'center',
    fontSize: 11,
    lineHeight: 15,
    fontWeight: '900',
    color: INK,
  },
  v56HistoryFactDivider: {
    width: 1,
    height: 18,
    backgroundColor: SIGNAL,
  },
  v56HistoryStub: {
    width: 60,
    borderLeftWidth: 1,
    borderLeftColor: '#BEB5A8',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F8F2E8',
  },
  v56HistoryNotchTop: {
    position: 'absolute',
    right: 52,
    top: -9,
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: SCREEN,
  },
  v56HistoryNotchBottom: {
    position: 'absolute',
    right: 52,
    bottom: -9,
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: SCREEN,
  },
  v56Barcode: {
    width: 34,
    height: 108,
    flexDirection: 'column',
    alignItems: 'stretch',
    justifyContent: 'center',
    gap: 1,
  },
  v56BarcodeBar: {
    width: '100%',
    backgroundColor: INK,
  },
  v56HistoryEmpty: {
    minHeight: 180,
    borderWidth: 1,
    borderColor: '#C9C0B3',
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 28,
  },
  v56HistoryEmptyTitle: {
    fontSize: 19,
    lineHeight: 26,
    fontWeight: '900',
    color: INK,
    textAlign: 'center',
  },
  v56HistoryClear: {
    minHeight: 50,
    marginTop: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  v56HistoryClearText: {
    fontSize: 14,
    fontWeight: '800',
    color: MUTED,
  },

  v56DetailScreen: {
    flex: 1,
    backgroundColor: SCREEN,
    paddingTop: 58,
  },
  v56DetailTop: {
    height: 58,
    paddingHorizontal: 22,
    flexDirection: 'row',
    alignItems: 'center',
  },
  v56DetailBack: {
    width: 54,
    height: 54,
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  v56DetailBackText: {
    fontSize: 34,
    lineHeight: 38,
    color: INK,
  },
  v56DetailBrand: {
    flex: 1,
    fontSize: 30,
    lineHeight: 34,
    fontWeight: '900',
    letterSpacing: -1.1,
    color: INK,
  },
  v56DetailSpacer: {
    width: 54,
  },
  v56DetailScroll: {
    paddingHorizontal: 24,
    paddingTop: 18,
    paddingBottom: 80,
  },
  v56DetailShareButton: {
    minHeight: 64,
    marginTop: 22,
    borderRadius: 32,
    backgroundColor: SIGNAL,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  v56DetailShareIcon: {
    fontSize: 25,
    color: INK,
  },
  v56DetailShareText: {
    fontSize: 20,
    fontWeight: '900',
    color: INK,
  },

  v56SharePoster: {
    width: 360,
    height: 640,
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 18,
    backgroundColor: SCREEN,
    overflow: 'hidden',
  },
  v56ShareBrand: {
    fontSize: 27,
    lineHeight: 31,
    fontWeight: '900',
    letterSpacing: -1.2,
    color: INK,
  },
  v56ShareBrandDot: {
    color: SIGNAL,
  },
  v56ShareMoodTitle: {
    marginTop: 12,
    fontSize: 42,
    lineHeight: 47,
    fontWeight: '900',
    letterSpacing: -1.8,
    color: INK,
  },
  v56ShareAccent: {
    width: 88,
    height: 5,
    marginTop: 2,
    marginBottom: 14,
    borderRadius: 3,
    backgroundColor: SIGNAL,
    transform: [{ rotate: '-3deg' }],
  },
  v56ShareCardWrap: {
    flex: 1,
    width: '100%',
  },
});
