import { Platform, StyleSheet } from 'react-native';
import { ABSOLUTE_FILL, BONE, INK, LINE, MUTED, SIGNAL, SOFT } from '../../theme/detour-theme';

export const journeyStyles = StyleSheet.create({
  detourTicketRoutePrint: {
    height: 52,
    marginTop: 20,
    flexDirection: 'row',
    alignItems: 'center',
    position: 'relative',
  },
  detourTicketRouteDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: SIGNAL,
  },
  detourTicketRouteLine: {
    height: 2,
    marginLeft: 6,
    backgroundColor: SIGNAL,
  },
  detourTicketRouteEnd: {
    marginLeft: 5,
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 2,
    borderColor: SIGNAL,
    backgroundColor: '#FAF7EE',
  },
  routeHomeScreen: {
    flex: 1,
    backgroundColor: BONE,
    paddingTop: 58,
    paddingHorizontal: 22,
    paddingBottom: 24,
  },
  routeHomeHeader: {
    minHeight: 68,
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  routeBrandLockup: {
    paddingTop: 3,
  },
  routeBrand: {
    fontSize: 18,
    fontWeight: '800',
    letterSpacing: 5.5,
    color: INK,
  },
  routeBrandTag: {
    marginTop: 8,
    fontSize: 7,
    lineHeight: 11,
    fontWeight: '700',
    letterSpacing: 2,
    color: '#98948A',
  },
  routeHomeUtilities: {
    marginLeft: 'auto',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  routeUtilityDivider: {
    width: 1,
    height: 32,
    backgroundColor: LINE,
  },
  routeSettingsButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    borderWidth: 1,
    borderColor: INK,
    alignItems: 'center',
    justifyContent: 'center',
  },
  routeSettingsGlyph: {
    marginTop: -6,
    fontSize: 18,
    fontWeight: '800',
    letterSpacing: 1,
    color: INK,
  },
  routePulseHero: {
    height: 2,
  },
  routePulseGraphic: {
    height: 188,
    marginTop: 8,
    position: 'relative',
    overflow: 'hidden',
  },
  routePulseStartWrap: {
    position: 'absolute',
    left: 20,
    top: 58,
    width: 54,
    height: 54,
    alignItems: 'center',
    justifyContent: 'center',
  },
  routePulseHaloLarge: {
    position: 'absolute',
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: 'rgba(255,90,54,0.08)',
  },
  routePulseHaloSmall: {
    position: 'absolute',
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: 'rgba(255,90,54,0.12)',
  },
  routePulseStart: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: SIGNAL,
    borderWidth: 3,
    borderColor: BONE,
  },
  routePulseStartCore: {
    position: 'absolute',
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: BONE,
  },
  routePulseStartLabel: {
    position: 'absolute',
    left: 0,
    top: 20,
    fontSize: 7,
    lineHeight: 10,
    fontWeight: '700',
    letterSpacing: 1.4,
    color: MUTED,
  },
  routeSegment: {
    position: 'absolute',
    height: 3,
    borderRadius: 2,
    backgroundColor: SIGNAL,
  },
  routeSegmentOne: {
    left: 63,
    top: 93,
    width: 74,
    transform: [{ rotate: '12deg' }],
  },
  routeSegmentTwo: {
    left: 127,
    top: 82,
    width: 66,
    transform: [{ rotate: '-19deg' }],
  },
  routeSegmentThree: {
    left: 183,
    top: 87,
    width: 74,
    transform: [{ rotate: '43deg' }],
  },
  routeSegmentFour: {
    left: 243,
    top: 119,
    width: 70,
    transform: [{ rotate: '2deg' }],
  },
  routeSegmentFive: {
    right: 16,
    top: 93,
    width: 74,
    transform: [{ rotate: '-48deg' }],
  },
  routeNode: {
    position: 'absolute',
    width: 14,
    height: 14,
    borderRadius: 7,
    borderWidth: 3,
    borderColor: SIGNAL,
    backgroundColor: BONE,
  },
  routeNodeOne: {
    left: 172,
    top: 59,
  },
  routeNodeOneLabel: {
    position: 'absolute',
    left: 144,
    top: 17,
    fontSize: 7,
    lineHeight: 10,
    fontWeight: '700',
    letterSpacing: 1.4,
    color: MUTED,
  },
  routeNodeTwo: {
    left: 246,
    top: 112,
  },
  routeNodeTwoLabel: {
    position: 'absolute',
    left: 228,
    top: 139,
    fontSize: 7,
    lineHeight: 10,
    fontWeight: '700',
    letterSpacing: 1.4,
    color: MUTED,
  },
  routeSceneDiscOne: {
    position: 'absolute',
    left: 105,
    top: 110,
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: '#C8C0A9',
    overflow: 'hidden',
  },
  routeSceneDiscOneInner: {
    position: 'absolute',
    left: 15,
    top: -4,
    width: 10,
    height: 54,
    backgroundColor: '#5E6756',
    transform: [{ rotate: '28deg' }],
  },
  routeSceneDiscTwo: {
    position: 'absolute',
    right: 67,
    top: 54,
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#8E8577',
    overflow: 'hidden',
  },
  routeSceneDiscTwoInner: {
    position: 'absolute',
    right: 10,
    top: 4,
    width: 12,
    height: 40,
    borderRadius: 6,
    backgroundColor: SIGNAL,
  },
  routeDestination: {
    position: 'absolute',
    right: 14,
    top: 40,
    width: 38,
    height: 55,
  },
  routeDestinationDot: {
    position: 'absolute',
    left: 2,
    bottom: 0,
    width: 13,
    height: 13,
    borderRadius: 7,
    backgroundColor: SIGNAL,
  },
  routeDestinationPole: {
    position: 'absolute',
    left: 8,
    top: 3,
    width: 2,
    height: 42,
    backgroundColor: SIGNAL,
  },
  routeDestinationFlag: {
    position: 'absolute',
    left: 10,
    top: 3,
    width: 23,
    height: 15,
    backgroundColor: SIGNAL,
    transform: [{ skewY: '-10deg' }],
  },
  routeDestinationLabel: {
    position: 'absolute',
    right: 0,
    top: 96,
    fontSize: 7,
    lineHeight: 10,
    fontWeight: '700',
    letterSpacing: 1.3,
    color: MUTED,
    textAlign: 'right',
  },
  routeTinyTreeOne: {
    position: 'absolute',
    left: 45,
    bottom: 12,
    fontSize: 16,
    color: '#C1BDB2',
  },
  routeTinyTreeTwo: {
    position: 'absolute',
    left: 66,
    bottom: 1,
    fontSize: 13,
    color: '#C1BDB2',
  },
  routeTinyMountain: {
    position: 'absolute',
    right: 68,
    bottom: 4,
    fontSize: 30,
    color: '#C9C5B8',
  },
  routeHomeCopy: {
    marginTop: 6,
  },
  routeHomeTitle: {
    fontSize: 41,
    lineHeight: 47,
    fontWeight: '700',
    letterSpacing: -2.2,
    color: INK,
  },
  routeHomeSubtitle: {
    marginTop: 12,
    fontSize: 17,
    lineHeight: 25,
    fontWeight: '500',
    color: '#6B675F',
  },
  routeTimeRow: {
    marginTop: 24,
    flexDirection: 'row',
    gap: 9,
  },
  routeTimeButton: {
    flex: 1,
    height: 86,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: INK,
    backgroundColor: BONE,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  routeTimeButtonActive: {
    borderWidth: 3,
    borderColor: SIGNAL,
    backgroundColor: '#FFF0E9',
  },
  routeTimeButtonPressed: {
    opacity: 0.6,
    transform: [{ translateY: 2 }],
  },
  routeTimeNumber: {
    fontSize: 30,
    lineHeight: 34,
    fontWeight: '700',
    letterSpacing: -1.5,
    color: INK,
  },
  routeTimeNumberActive: {
    color: INK,
  },
  routeTimeUnit: {
    marginTop: 3,
    fontSize: 9,
    fontWeight: '700',
    letterSpacing: 1.5,
    color: MUTED,
  },
  routeTimeUnitActive: {
    color: SIGNAL,
  },
  routeSelectedBurst: {
    position: 'absolute',
    top: -15,
    width: 42,
    height: 18,
  },
  routeBurstLeft: {
    position: 'absolute',
    left: 5,
    top: 8,
    width: 9,
    height: 2,
    borderRadius: 1,
    backgroundColor: SIGNAL,
    transform: [{ rotate: '55deg' }],
  },
  routeBurstCenter: {
    position: 'absolute',
    left: 20,
    top: 0,
    width: 2,
    height: 10,
    borderRadius: 1,
    backgroundColor: SIGNAL,
  },
  routeBurstRight: {
    position: 'absolute',
    right: 5,
    top: 8,
    width: 9,
    height: 2,
    borderRadius: 1,
    backgroundColor: SIGNAL,
    transform: [{ rotate: '-55deg' }],
  },
  routeHomePrimary: {
    marginTop: 18,
    minHeight: 64,
    paddingHorizontal: 20,
    borderRadius: 18,
    backgroundColor: SIGNAL,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  routeHomePrimaryDisabled: {
    backgroundColor: SOFT,
  },
  routeHomePrimaryPressed: {
    opacity: 0.78,
    transform: [{ translateY: 2 }],
  },
  routeHomePrimaryText: {
    fontSize: 17,
    fontWeight: '700',
    color: BONE,
  },
  routeHomePrimaryArrow: {
    fontSize: 24,
    lineHeight: 26,
    color: BONE,
  },
  routeHomePrimaryTextDisabled: {
    color: '#A5A097',
  },
  routeHomeFooter: {
    marginTop: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  routeHomeFooterText: {
    fontSize: 10,
    fontWeight: '600',
    letterSpacing: 0.5,
    color: MUTED,
  },
  routeHomeTestLabel: {
    fontSize: 8,
    fontWeight: '800',
    letterSpacing: 1.4,
    color: SIGNAL,
  },
  routeCanvas: {
    height: 120,
    marginTop: 54,
    flexDirection: 'row',
    alignItems: 'center',
  },
  routeStart: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: SIGNAL,
  },
  routeStroke: { height: 2, marginLeft: 6, backgroundColor: INK },
  routeEnd: {
    marginLeft: 6,
    width: 34,
    height: 34,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: INK,
    alignItems: 'center',
    justifyContent: 'center',
  },
  routeEndInner: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: INK,
  },
  journeyScreen: {
    flex: 1,
    backgroundColor: BONE,
    paddingTop: 62,
    paddingHorizontal: 22,
    paddingBottom: 34,
    justifyContent: 'space-between',
  },
  journeyTop: {
    minHeight: 42,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  mainQuestBar: { marginTop: 22 },
  mainQuestBarFillWrap: { height: 3, backgroundColor: '#34332F' },
  mainQuestBarFill: { height: 3, backgroundColor: SIGNAL },
  mainQuestBarMeta: {
    marginTop: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  mainQuestMini: { fontSize: 7, letterSpacing: 1.5, color: '#79766F' },
  journeyHero: { flex: 1, justifyContent: 'center' },
  mainQuestLabel: { fontSize: 9, letterSpacing: 2, color: SIGNAL },
  beatArrowWrap: {
    height: 84,
    marginTop: 16,
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  beatArrow: {
    fontSize: 58,
    lineHeight: 64,
    color: SIGNAL,
  },
  distanceBig: {
    marginTop: 8,
    fontSize: 76,
    lineHeight: 82,
    fontWeight: '700',
    letterSpacing: -4.8,
    color: BONE,
  },
  journeyInstruction: {
    marginTop: 20,
    fontSize: 30,
    fontWeight: '600',
    letterSpacing: -1.4,
    color: BONE,
  },
  journeySub: {
    marginTop: 11,
    maxWidth: 300,
    fontSize: 12,
    lineHeight: 20,
    color: '#8E8A82',
  },
  journeyFooter: { gap: 12 },
  sideQuestSummary: {
    minHeight: 54,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: '#393833',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sideQuestSummaryLabel: { fontSize: 8, letterSpacing: 1.5, color: '#8E8A82' },
  sideQuestSummaryValue: { fontSize: 11, fontWeight: '700', color: BONE },
  journeyUtilityRow: {
    minHeight: 54,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 14,
  },
  journeyUtilityText: {
    flex: 1,
    fontSize: 10,
    lineHeight: 16,
    letterSpacing: 0.5,
    color: '#8E8A82',
  },
  journeyCameraButton: {
    width: 52,
    height: 52,
    borderRadius: 26,
    borderWidth: 1,
    borderColor: '#4A4741',
    alignItems: 'center',
    justifyContent: 'center',
  },
  journeyCameraButtonPressed: {
    opacity: 0.55,
    transform: [{ scale: 0.96 }],
  },
  journeyCameraIcon: {
    fontSize: 21,
  },
  navigationArrowField: {
    alignItems: 'center',
    marginBottom: 8,
  },
  navigationCompassRing: {
    width: 118,
    height: 118,
    borderRadius: 59,
    borderWidth: 1,
    borderColor: '#35332F',
    alignItems: 'center',
    justifyContent: 'center',
  },
  navigationArrowRotator: {
    width: 90,
    height: 90,
    alignItems: 'center',
    justifyContent: 'center',
  },
  navigationArrow: {
    fontSize: 67,
    lineHeight: 76,
    color: SIGNAL,
  },
  nextBeatMapButton: {
    width: '100%',
    height: 48,
    marginTop: 24,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: '#34322E',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  nextBeatMapButtonPressed: {
    opacity: 0.45,
  },
  nextBeatMapButtonText: {
    fontSize: 11,
    fontWeight: '700',
    color: BONE,
  },
  nextBeatMapWrap: {
    flex: 1,
    marginTop: 20,
    marginBottom: 12,
    overflow: 'hidden',
    backgroundColor: '#1A1917',
  },
  nextBeatMap: {
    ...ABSOLUTE_FILL,
  },
  nextBeatMapChrome: {
    position: 'absolute',
    top: 14,
    left: 14,
    right: 14,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  nextBeatMapLabel: {
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    paddingVertical: 8,
    backgroundColor: BONE,
    fontSize: 8,
    fontWeight: '800',
    letterSpacing: 1.3,
    color: INK,
  },
  nextBeatMapHint: {
    marginTop: 7,
    alignSelf: 'flex-start',
    paddingHorizontal: 9,
    paddingVertical: 6,
    backgroundColor: 'rgba(17,17,15,0.82)',
    fontSize: 8,
    color: BONE,
  },
  nextBeatMapClose: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: BONE,
    alignItems: 'center',
    justifyContent: 'center',
  },
  nextBeatMapCloseText: {
    fontSize: 23,
    color: INK,
  },
  devNavNote: {
    marginBottom: 10,
    fontSize: 8,
    lineHeight: 14,
    color: '#77736B',
  },
  cleanJourneyTop: {
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
  },
  cleanJourneyHero: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
    paddingBottom: 34,
  },
  cleanDistance: {
    fontSize: 92,
    lineHeight: 102,
    fontWeight: '700',
    letterSpacing: -6,
    color: INK,
  },
  cleanDistanceUnit: {
    fontSize: 34,
    letterSpacing: -1,
    fontWeight: '600',
    color: INK,
  },
  cleanDistanceNear: {
    color: SIGNAL,
  },
  questPulseOverlay: {
    ...ABSOLUTE_FILL,
    zIndex: 20,
    backgroundColor: BONE,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 32,
  },
  questPulseNode: {
    width: 66,
    height: 66,
    borderRadius: 33,
    borderWidth: 2,
    borderColor: SIGNAL,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 24,
  },
  questPulseNodeCore: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: SIGNAL,
  },
  questPulseCode: {
    fontSize: 9,
    fontWeight: '800',
    letterSpacing: 2.1,
    color: SIGNAL,
  },
  questPulseTitle: {
    marginTop: 13,
    fontSize: 28,
    lineHeight: 34,
    fontWeight: '700',
    letterSpacing: -1.3,
    color: INK,
    textAlign: 'center',
  },
  cleanJourneyBottom: {
    minHeight: 88,
    justifyContent: 'flex-end',
  },
  cleanCameraButton: {
    alignSelf: 'flex-end',
    width: 54,
    height: 54,
    borderRadius: 27,
    borderWidth: 1,
    borderColor: LINE,
    backgroundColor: BONE,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  cleanCameraButtonPressed: {
    opacity: 0.45,
    transform: [{ scale: 0.96 }],
  },
  cleanCameraIcon: {
    fontSize: 20,
  },
  cleanMapWrap: {
    flex: 1,
    marginTop: 22,
    marginBottom: 18,
    overflow: 'hidden',
    backgroundColor: '#E7E2D6',
    borderWidth: 1,
    borderColor: LINE,
  },
  cleanMap: {
    ...ABSOLUTE_FILL,
  },
  cleanMapTop: {
    position: 'absolute',
    top: 14,
    left: 14,
    right: 14,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  cleanMapCopy: {
    backgroundColor: BONE,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  cleanMapLabel: {
    fontSize: 8,
    letterSpacing: 1.2,
    color: MUTED,
  },
  cleanMapDistance: {
    marginTop: 4,
    fontSize: 17,
    fontWeight: '800',
    color: INK,
  },
  cleanMapClose: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: BONE,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cleanMapCloseText: {
    fontSize: 24,
    color: INK,
  },
  cleanMapFootnote: {
    position: 'absolute',
    left: 14,
    bottom: 14,
    paddingHorizontal: 10,
    paddingVertical: 7,
    backgroundColor: 'rgba(17,17,15,0.84)',
    fontSize: 8,
    letterSpacing: 1,
    color: BONE,
  },
  cleanRouteStatus: {
    marginTop: 14,
    fontSize: 9,
    letterSpacing: 1.4,
    color: SIGNAL,
  },
  cleanRouteRetry: {
    marginTop: 14,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: LINE,
  },
  cleanRouteRetryText: {
    fontSize: 9,
    color: MUTED,
  },
  fieldEventRouteStrip: {
    height: 70,
    marginTop: 28,
    paddingHorizontal: 4,
    flexDirection: 'row',
    alignItems: 'center',
    position: 'relative',
  },
  fieldEventRouteNode: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: SIGNAL,
    alignItems: 'center',
    justifyContent: 'center',
  },
  fieldEventRouteNodeCore: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: SIGNAL,
  },
  fieldEventRouteLine: {
    width: 70,
    height: 2,
    backgroundColor: SIGNAL,
  },
  fieldEventRouteQuest: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: SIGNAL,
    alignItems: 'center',
    justifyContent: 'center',
  },
  fieldEventRouteQuestMark: {
    fontSize: 18,
    color: BONE,
  },
  fieldEventRouteLineMuted: {
    flex: 1,
    height: 1,
    backgroundColor: LINE,
  },
  fieldEventRouteLabel: {
    position: 'absolute',
    right: 0,
    bottom: 0,
    fontSize: 7,
    fontWeight: '800',
    letterSpacing: 1.4,
    color: MUTED,
  },
  fieldEventCamera: {
    width: 64,
    minHeight: 64,
    borderWidth: 1,
    borderColor: LINE,
    alignItems: 'center',
    justifyContent: 'center',
  },
  fieldEventCameraIcon: {
    fontSize: 20,
  },
  cleanMissionScreen: {
    flex: 1,
    backgroundColor: INK,
    paddingTop: 62,
    paddingHorizontal: 22,
    paddingBottom: 34,
  },
  cleanMissionTop: {
    minHeight: 42,
    flexDirection: 'row',
    alignItems: 'center',
  },
  cleanMissionClose: {
    width: 34,
    height: 38,
    justifyContent: 'center',
  },
  cleanMissionCloseText: {
    fontSize: 28,
    lineHeight: 30,
    color: BONE,
  },
  cleanMissionBrand: {
    marginLeft: 28,
    fontSize: 14,
    fontWeight: '800',
    letterSpacing: 4,
    color: BONE,
  },
  cleanMissionType: {
    marginLeft: 'auto',
    fontSize: 8,
    letterSpacing: 1.8,
    color: '#77736B',
  },
  cleanMissionHero: {
    flex: 1,
    justifyContent: 'center',
    paddingBottom: 26,
  },
  cleanMissionCode: {
    fontSize: 9,
    letterSpacing: 2,
    color: SIGNAL,
    marginBottom: 18,
  },
  cleanMissionTitle: {
    fontSize: 45,
    lineHeight: 52,
    fontWeight: '600',
    letterSpacing: -2.4,
    color: BONE,
  },
  cleanMissionInstruction: {
    marginTop: 24,
    maxWidth: 345,
    fontSize: 17,
    lineHeight: 28,
    fontWeight: '500',
    color: '#B7B2A8',
  },
  cleanMissionCompletion: {
    marginTop: 24,
    maxWidth: 340,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: '#2F2D29',
    fontSize: 14,
    lineHeight: 22,
    fontWeight: '600',
    color: BONE,
  },
  cleanMissionContextNote: {
    marginTop: 16,
    maxWidth: 330,
    fontSize: 10,
    lineHeight: 17,
    color: '#77736B',
  },
  cleanMissionBottom: {
    gap: 10,
  },
  cleanMissionActions: {
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: 10,
  },
  cleanMissionPrimary: {
    minHeight: 64,
    paddingHorizontal: 18,
    backgroundColor: BONE,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  cleanMissionPrimaryFlexible: {
    flex: 1,
  },
  cleanMissionPrimaryText: {
    fontSize: 16,
    fontWeight: '700',
    color: INK,
  },
  cleanMissionPrimaryArrow: {
    fontSize: 23,
    color: SIGNAL,
  },
  cleanMissionCamera: {
    width: 64,
    minHeight: 64,
    borderWidth: 1,
    borderColor: '#3A3833',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cleanMissionCameraIcon: {
    fontSize: 21,
  },
  cleanMissionSkip: {
    minHeight: 38,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cleanMissionSkipText: {
    fontSize: 10,
    color: '#77736B',
  },
  cleanMissionPressed: {
    opacity: 0.5,
  },
  missionScreen: {
    flex: 1,
    backgroundColor: INK,
    paddingTop: 62,
    paddingHorizontal: 22,
    paddingBottom: 34,
    justifyContent: 'space-between',
  },
  missionTop: {
    minHeight: 42,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  missionSpineReminder: {
    marginTop: 22,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: '#34332F',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  missionSpineLabel: { fontSize: 7, letterSpacing: 1.4, color: SIGNAL },
  missionSpineValue: { fontSize: 7, letterSpacing: 1.2, color: '#8E8A82' },
  missionHero: { flex: 1, justifyContent: 'center' },
  missionCode: { fontSize: 10, letterSpacing: 2.1, color: SIGNAL },
  missionTitle: {
    marginTop: 18,
    fontSize: 43,
    lineHeight: 49,
    fontWeight: '600',
    letterSpacing: -2.2,
    color: BONE,
  },
  missionInstruction: {
    marginTop: 24,
    maxWidth: 330,
    fontSize: 15,
    lineHeight: 25,
    color: '#BBB7AE',
  },
  missionBottom: { gap: 12 },
  missionButtonEyebrow: {
    marginBottom: 5,
    fontSize: 7,
    letterSpacing: 1.3,
    color: MUTED,
  },
  optionalMissionActions: {
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: 10,
  },
  optionalCameraButton: {
    width: 70,
    minHeight: 70,
    borderWidth: 1,
    borderColor: '#4A4741',
    alignItems: 'center',
    justifyContent: 'center',
  },
  optionalCameraButtonPressed: { backgroundColor: '#262521' },
  optionalCameraIcon: { fontSize: 25 },
  skipMissionButton: {
    minHeight: 46,
    marginTop: 10,
    paddingHorizontal: 2,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  skipMissionPressed: { opacity: 0.45 },
  skipMissionText: {
    fontSize: 11,
    lineHeight: 17,
    color: '#8E8A82',
  },
  skipMissionArrow: { fontSize: 16, color: '#8E8A82' },
  arrivalSkipButton: {
    minHeight: 44,
    marginTop: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  arrivalSkipText: {
    fontSize: 10,
    letterSpacing: 0.4,
    color: MUTED,
  },
  cleanArrivalScreen: {
    flex: 1,
    backgroundColor: BONE,
    paddingTop: 62,
    paddingHorizontal: 22,
    paddingBottom: 34,
  },
  cleanArrivalTop: {
    minHeight: 40,
    flexDirection: 'row',
    alignItems: 'center',
  },
  cleanArrivalMeta: {
    marginLeft: 'auto',
    fontSize: 8,
    letterSpacing: 1.8,
    color: MUTED,
  },
  arrivalRevealStrip: {
    height: 58,
    marginTop: 30,
    flexDirection: 'row',
    alignItems: 'center',
    position: 'relative',
  },
  arrivalRevealStart: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: SIGNAL,
  },
  arrivalRevealLine: {
    flex: 1,
    height: 2,
    marginHorizontal: 8,
    backgroundColor: SIGNAL,
  },
  arrivalRevealFlag: {
    width: 28,
    height: 36,
    position: 'relative',
  },
  arrivalRevealFlagPole: {
    position: 'absolute',
    left: 4,
    top: 2,
    width: 2,
    height: 30,
    backgroundColor: SIGNAL,
  },
  arrivalRevealFlagShape: {
    position: 'absolute',
    left: 6,
    top: 2,
    width: 18,
    height: 12,
    backgroundColor: SIGNAL,
  },
  arrivalRevealLabel: {
    position: 'absolute',
    right: 0,
    bottom: 0,
    fontSize: 7,
    fontWeight: '800',
    letterSpacing: 1.5,
    color: MUTED,
  },
  cleanArrivalHero: {
    flex: 1,
    justifyContent: 'center',
    paddingBottom: 26,
  },
  cleanArrivalKicker: {
    fontSize: 9,
    letterSpacing: 1.8,
    color: SIGNAL,
    marginBottom: 14,
  },
  cleanArrivalPlace: {
    fontSize: 43,
    lineHeight: 50,
    fontWeight: '700',
    letterSpacing: -2.3,
    color: INK,
  },
  cleanArrivalCode: {
    marginTop: 32,
    fontSize: 8,
    letterSpacing: 1.7,
    color: MUTED,
  },
  cleanArrivalMission: {
    marginTop: 9,
    fontSize: 24,
    lineHeight: 31,
    fontWeight: '700',
    color: INK,
  },
  cleanArrivalInstruction: {
    marginTop: 20,
    maxWidth: 345,
    fontSize: 17,
    lineHeight: 28,
    fontWeight: '500',
    color: '#5A5750',
  },
  cleanArrivalCompletion: {
    marginTop: 22,
    maxWidth: 340,
    paddingTop: 15,
    borderTopWidth: 1,
    borderTopColor: LINE,
    fontSize: 14,
    lineHeight: 22,
    fontWeight: '600',
    color: INK,
  },
  cleanArrivalBottom: {
    gap: 9,
  },
  cleanArrivalActions: {
    flexDirection: 'row',
    gap: 10,
  },
  cleanArrivalPrimary: {
    minHeight: 64,
    paddingHorizontal: 18,
    backgroundColor: INK,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  cleanArrivalPrimaryFlexible: {
    flex: 1,
  },
  cleanArrivalPrimaryText: {
    fontSize: 15,
    fontWeight: '700',
    color: BONE,
  },
  cleanArrivalPrimaryArrow: {
    fontSize: 22,
    color: SIGNAL,
  },
  cleanArrivalCamera: {
    width: 64,
    minHeight: 64,
    borderWidth: 1,
    borderColor: LINE,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cleanArrivalCameraIcon: {
    fontSize: 20,
  },
  cleanArrivalSkip: {
    minHeight: 36,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cleanArrivalSkipText: {
    fontSize: 9,
    color: MUTED,
  },
  cleanArrivalSource: {
    marginTop: 4,
    fontSize: 7,
    letterSpacing: 1.1,
    color: '#A5A197',
  },
  arrivalScreen: {
    flex: 1,
    backgroundColor: BONE,
    paddingTop: 62,
    paddingHorizontal: 22,
    paddingBottom: 34,
    justifyContent: 'space-between',
  },
  arrivalHero: { flex: 1, justifyContent: 'center' },
  arrivalStamp: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: SIGNAL,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 30,
  },
  arrivalStampText: { fontSize: 22, color: INK, fontWeight: '800' },
  arrivalKicker: { fontSize: 10, letterSpacing: 1.6, color: SIGNAL, marginBottom: 12 },
  arrivalTitle: {
    fontSize: 42,
    lineHeight: 48,
    fontWeight: '600',
    letterSpacing: -2.2,
    color: INK,
  },
  arrivalMissionCode: { marginTop: 32, fontSize: 9, letterSpacing: 1.8, color: MUTED },
  arrivalMissionTitle: {
    marginTop: 10,
    fontSize: 22,
    lineHeight: 29,
    fontWeight: '700',
    color: INK,
  },
  arrivalInstruction: { marginTop: 12, fontSize: 14, lineHeight: 23, color: MUTED },
  arrivalRule: { paddingTop: 14, borderTopWidth: 1, borderTopColor: LINE },
  arrivalRuleLabel: { fontSize: 8, letterSpacing: 1.3, color: MUTED },
  arrivalRuleText: { marginTop: 8, fontSize: 13, lineHeight: 20, color: INK },
  cameraNativeLayer: {
    ...ABSOLUTE_FILL,
    zIndex: 100,
    backgroundColor: '#000',
  },
  cameraModalScreen: { flex: 1, backgroundColor: '#000' },
  cameraPreview: { flex: 1 },
  cameraScreen: { flex: 1, backgroundColor: '#000' },
  cameraView: { ...ABSOLUTE_FILL },
  cameraOverlay: {
    ...ABSOLUTE_FILL,
    paddingTop: 58,
    paddingHorizontal: 18,
    paddingBottom: 28,
    justifyContent: 'space-between',
  },
  cameraTop: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  cameraClose: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: 'rgba(17,17,15,0.78)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cameraCloseText: { fontSize: 25, color: BONE },
  cameraMissionChip: {
    minHeight: 46,
    paddingHorizontal: 14,
    backgroundColor: 'rgba(17,17,15,0.78)',
    justifyContent: 'center',
  },
  cameraMissionChipText: { fontSize: 8, letterSpacing: 1.4, color: BONE },
  cameraPrompt: {
    alignSelf: 'stretch',
    backgroundColor: 'rgba(17,17,15,0.78)',
    padding: 16,
  },
  cameraPromptTitle: { fontSize: 19, lineHeight: 25, fontWeight: '700', color: BONE },
  cameraPromptRule: { marginTop: 8, fontSize: 11, lineHeight: 18, color: '#C9C5BC' },
  cameraBottom: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  cameraStatusColumn: { width: 105, gap: 6 },
  cameraReadyText: { fontSize: 7, letterSpacing: 1.3, color: BONE },
  cameraRestartText: { fontSize: 8, lineHeight: 13, color: SIGNAL },
  cameraCount: { width: 105, textAlign: 'right', fontSize: 7, letterSpacing: 1.3, color: BONE },
  shutterOuter: {
    width: 78,
    height: 78,
    borderRadius: 39,
    borderWidth: 3,
    borderColor: BONE,
    alignItems: 'center',
    justifyContent: 'center',
  },
  reviewMissionCode: { fontSize: 8, letterSpacing: 1.5, color: SIGNAL },
  journeyRollText: {
    marginTop: 6,
    fontSize: 7,
    letterSpacing: 1.3,
    color: '#77736B',
  },
  cleanArrivalProblem: {
    minHeight: 38,
    marginTop: 2,
    paddingHorizontal: 2,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  cleanArrivalProblemText: {
    fontSize: 10,
    color: MUTED,
  },
  cleanArrivalProblemArrow: {
    fontSize: 14,
    color: MUTED,
  },
  reissueRouteCard: {
    padding: 16,
    borderRadius: 16,
    backgroundColor: 'rgba(255,90,54,0.08)',
  },
  reissueRouteHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  reissueRouteLabel: {
    fontSize: 8,
    fontWeight: '800',
    letterSpacing: 1.5,
    color: MUTED,
  },
  reissueRouteLabelDark: {
    color: '#AAA49A',
  },
  reissueRouteStatus: {
    fontSize: 8,
    fontWeight: '900',
    letterSpacing: 1.5,
    color: SIGNAL,
  },
  reissueRouteGraphic: {
    height: 62,
    marginTop: 12,
    flexDirection: 'row',
    alignItems: 'center',
  },
  reissueRouteStart: {
    width: 15,
    height: 15,
    borderRadius: 8,
    backgroundColor: SIGNAL,
  },
  reissueRouteLineDone: {
    flex: 1,
    height: 3,
    backgroundColor: SIGNAL,
  },
  reissueRouteBreak: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: SIGNAL,
    alignItems: 'center',
    justifyContent: 'center',
  },
  reissueRouteBreakText: {
    marginTop: -2,
    fontSize: 18,
    fontWeight: '800',
    color: SIGNAL,
  },
  reissueRouteLineNext: {
    flex: 0.55,
    height: 1,
    borderTopWidth: 1,
    borderColor: SIGNAL,
    borderStyle: 'dashed',
  },
  reissueRouteQuestion: {
    width: 30,
    height: 30,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: SIGNAL,
    alignItems: 'center',
    justifyContent: 'center',
  },
  reissueRouteQuestionText: {
    fontSize: 14,
    fontWeight: '800',
    color: SIGNAL,
  },
  reissueRouteFoot: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  reissueRouteFootText: {
    fontSize: 9,
    fontWeight: '700',
    color: '#625E56',
  },
  reissueRouteFootTextDark: {
    color: '#B1ABA2',
  },
  reissueRouteFootArrow: {
    fontSize: 12,
    color: SIGNAL,
  },
  developingScreen: {
    flex: 1,
    backgroundColor: '#050505',
    paddingTop: 62,
    paddingHorizontal: 22,
    paddingBottom: 34,
    justifyContent: 'space-between',
  },
  developingTop: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  developingMeta: {
    marginLeft: 'auto',
    fontSize: 8,
    letterSpacing: 1.8,
    color: '#77736B',
  },
  developingHero: {
    flex: 1,
    justifyContent: 'center',
  },
  developingDot: {
    width: 9,
    height: 9,
    borderRadius: 5,
    backgroundColor: SIGNAL,
    marginBottom: 32,
  },
  developingCode: {
    fontSize: 9,
    fontWeight: '800',
    letterSpacing: 2.4,
    color: SIGNAL,
    marginBottom: 18,
  },
  developingTitle: {
    fontSize: 46,
    lineHeight: 52,
    fontWeight: '700',
    letterSpacing: -2.4,
    color: BONE,
  },
  developingBody: {
    marginTop: 20,
    fontSize: 9,
    letterSpacing: 1.8,
    color: '#77736B',
  },
  developingTrack: {
    height: 1,
    backgroundColor: '#2A2926',
    overflow: 'hidden',
  },
  developingTrackFill: {
    width: '72%',
    height: 1,
    backgroundColor: SIGNAL,
  },
  traceMapShell: {
    height: 260,
    marginTop: 34,
    overflow: 'hidden',
    backgroundColor: SOFT,
  },
  traceMap: { ...ABSOLUTE_FILL },
  routeHomeScreenDark: {
    backgroundColor: '#050505',
  },
  routeBrandDark: {
    color: BONE,
  },
  routeBrandTagDark: {
    color: '#9F9A90',
  },
  routeUtilityDividerDark: {
    backgroundColor: '#36322C',
  },
  routeSettingsButtonDark: {
    borderColor: '#4A453E',
  },
  routeSettingsGlyphDark: {
    color: BONE,
  },
  routePulseLabelDark: {
    color: '#A8A39A',
  },
  routeTinyGraphicDark: {
    color: '#9E9A90',
  },
  routeHomeTitleDark: {
    color: BONE,
  },
  routeHomeSubtitleDark: {
    color: '#B3ADA3',
  },
  routeTimeButtonDark: {
    borderColor: '#403B34',
    backgroundColor: '#151412',
  },
  routeTimeButtonActiveDark: {
    backgroundColor: 'rgba(255,90,54,0.16)',
    borderColor: SIGNAL,
  },
  routeTimeNumberDark: {
    color: BONE,
  },
  routeTimeUnitDark: {
    color: '#A9A39A',
  },
  routeHomePrimaryDark: {
    backgroundColor: SIGNAL,
  },
  routeHomePrimaryDisabledDark: {
    backgroundColor: '#24211D',
  },
  routeHomePrimaryTextDark: {
    color: '#130F0B',
  },
  routeHomePrimaryArrowDark: {
    color: '#130F0B',
  },
  routeHomePrimaryTextDisabledDark: {
    color: '#8D877D',
  },
  routeHomeFooterTextDark: {
    color: '#A8A39A',
  }
});
