import { Platform, StyleSheet } from 'react-native';
import { ABSOLUTE_FILL, BONE, INK, LINE, MUTED, SIGNAL, SOFT } from '../../theme/detour-theme';

export const legacyStyles = StyleSheet.create({
  v43MoodGlyph: {
    width: 84,
    height: 84,
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
  },
  v43WanderLineA: {
    position: 'absolute',
    left: 18,
    top: 43,
    width: 34,
    height: 7,
    borderRadius: 4,
    transform: [{ rotate: '-31deg' }],
  },
  v43WanderLineB: {
    position: 'absolute',
    left: 43,
    top: 28,
    width: 27,
    height: 7,
    borderRadius: 4,
    transform: [{ rotate: '21deg' }],
  },
  v43WanderDot: { position: 'absolute', width: 13, height: 13, borderRadius: 7 },
  v43WanderDotA: { left: 12, bottom: 21 },
  v43WanderDotB: { left: 40, top: 29 },
  v43WanderDotC: { right: 8, top: 20 },
  v43FoodBowl: {
    position: 'absolute',
    top: 32,
    width: 55,
    height: 29,
    borderWidth: 6,
    borderTopWidth: 0,
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
  },
  v43FoodPlate: { position: 'absolute', bottom: 17, width: 52, height: 6, borderRadius: 3 },
  v43FoodStem: { position: 'absolute', top: 14, width: 6, height: 25, borderRadius: 3 },
  v43FoodStemLeft: { left: 29, transform: [{ rotate: '-8deg' }] },
  v43FoodStemRight: { right: 28, transform: [{ rotate: '9deg' }] },
  v43QuietMoon: { position: 'absolute', width: 54, height: 54, borderRadius: 27, left: 15, top: 15 },
  v43QuietCutout: { position: 'absolute', width: 48, height: 48, borderRadius: 24, left: 31, top: 8 },
  v43QuietDot: { position: 'absolute', width: 9, height: 9, borderRadius: 5, right: 13, bottom: 17 },
  v43WeirdFrame: { width: 48, height: 48, borderWidth: 6, transform: [{ rotate: '13deg' }] },
  v43WeirdFrameInner: { position: 'absolute', width: 24, height: 24, borderWidth: 5, transform: [{ rotate: '-11deg' }] },
  v43WeirdDot: { position: 'absolute', width: 10, height: 10, borderRadius: 5, right: 10, top: 13 },
  v43ColorRingOuter: { position: 'absolute', width: 58, height: 58, borderRadius: 29, borderWidth: 6 },
  v43ColorRingMid: { position: 'absolute', width: 38, height: 38, borderRadius: 19, borderWidth: 6 },
  v43ColorCore: { width: 16, height: 16, borderRadius: 8 },
  v43FateDiamond: { position: 'absolute', transform: [{ rotate: '45deg' }] },
  v43FateDiamondMain: { width: 34, height: 34 },
  v43FateDiamondA: { width: 12, height: 12, left: 9, top: 17 },
  v43FateDiamondB: { width: 10, height: 10, right: 11, bottom: 16 },
  v43FateDiamondC: { width: 8, height: 8, right: 13, top: 10 },
  v43DevClose: {
    minHeight: 50,
    marginTop: 14,
    borderTopWidth: 1,
    borderTopColor: LINE,
    justifyContent: 'center',
  },
  v43DevCloseText: {
    fontSize: 16,
    fontWeight: '800',
    color: SIGNAL,
  },
  v43DetailScreen: {
    flex: 1,
    backgroundColor: BONE,
    paddingTop: 58,
    paddingHorizontal: 22,
  },
  v43DetailTop: {
    minHeight: 52,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  v43DetailBack: {
    position: 'absolute',
    left: 0,
    width: 48,
    height: 48,
    justifyContent: 'center',
  },
  v43DetailBackText: { fontSize: 34, color: INK },
  v43DetailHeader: { fontSize: 27, fontWeight: '900', color: INK, letterSpacing: -0.6 },
  v43DetailTopSpacer: { position: 'absolute', right: 0, width: 48, height: 48 },
  v43DetailScroll: { paddingTop: 24, paddingBottom: 64 },
  v43MemoryCard: {
    overflow: 'hidden',
    backgroundColor: '#FCF8EE',
    borderWidth: 1,
    borderColor: '#D7D1C4',
  },
  v43MemoryHeroPhoto: { width: '100%', aspectRatio: 4 / 3, backgroundColor: SOFT },
  v43MemoryNoPhoto: {
    width: '100%',
    aspectRatio: 4 / 3,
    backgroundColor: '#E6E1D5',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  v43MemoryRouteLine: { width: '58%', height: 6, borderRadius: 3, backgroundColor: INK, transform: [{ rotate: '-9deg' }] },
  v43MemoryRouteDot: { position: 'absolute', left: '20%', top: '47%', width: 18, height: 18, borderRadius: 9, backgroundColor: SIGNAL },
  v43MemoryRouteFlag: { position: 'absolute', right: '19%', top: '37%', width: 18, height: 26, borderLeftWidth: 4, borderLeftColor: INK, borderTopWidth: 11, borderTopColor: SIGNAL },
  v43MemoryNoPhotoText: { position: 'absolute', bottom: 24, fontSize: 17, fontWeight: '700', color: MUTED },
  v43MemoryCopy: { padding: 22 },
  v43MemoryTopline: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  v43MemoryBrand: { fontSize: 20, fontWeight: '900', letterSpacing: 3.6, color: INK },
  v43MemoryDate: { fontSize: 15, fontWeight: '700', color: MUTED },
  v43MemoryMood: { marginTop: 26, fontSize: 45, lineHeight: 50, fontWeight: '900', letterSpacing: -2.1, color: INK },
  v43MemoryDestination: { marginTop: 8, fontSize: 22, lineHeight: 29, fontWeight: '800', color: INK },
  v43MemoryFacts: { marginTop: 24, paddingTop: 18, borderTopWidth: 1, borderTopColor: LINE, flexDirection: 'row', flexWrap: 'wrap', gap: 16 },
  v43MemoryFact: { fontSize: 16, fontWeight: '800', color: MUTED },
  v43PhotoStrip: { gap: 10, paddingTop: 14, paddingRight: 22 },
  v43PhotoThumb: { width: 86, height: 86, borderWidth: 2, borderColor: 'transparent', backgroundColor: SOFT },
  v43PhotoThumbActive: { borderColor: SIGNAL },
  v43SummaryRow: {
    marginTop: 34,
    minHeight: 112,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: LINE,
    flexDirection: 'row',
  },
  v43SummaryItem: { flex: 1, justifyContent: 'center' },
  v43SummaryValue: { fontSize: 34, lineHeight: 39, fontWeight: '900', color: INK },
  v43SummaryLabel: { marginTop: 5, fontSize: 15, fontWeight: '700', color: MUTED },
  v43RouteSection: { marginTop: 38 },
  v43SectionHead: { marginBottom: 14, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  v43SectionTitle: { fontSize: 20, fontWeight: '900', color: INK },
  v43SectionMeta: { fontSize: 15, fontWeight: '700', color: MUTED },
  v43RouteCard: { padding: 22, borderWidth: 1, borderColor: LINE, backgroundColor: '#F7F3E9' },
  v43RouteVisual: { height: 92, position: 'relative' },
  v43RouteStart: { position: 'absolute', left: 4, bottom: 12, width: 18, height: 18, borderRadius: 9, backgroundColor: SIGNAL },
  v43RouteSegmentA: { position: 'absolute', left: 20, bottom: 27, width: '45%', height: 6, borderRadius: 3, backgroundColor: INK, transform: [{ rotate: '-10deg' }] },
  v43RouteTurn: { position: 'absolute', left: '46%', top: 28, width: 26, height: 26, borderTopWidth: 6, borderRightWidth: 6, borderColor: INK, transform: [{ rotate: '15deg' }] },
  v43RouteSegmentB: { position: 'absolute', right: 24, top: 28, width: '35%', height: 6, borderRadius: 3, backgroundColor: INK, transform: [{ rotate: '7deg' }] },
  v43RouteEnd: { position: 'absolute', right: 4, top: 20, width: 20, height: 28, borderLeftWidth: 4, borderLeftColor: SIGNAL, borderTopWidth: 12, borderTopColor: SIGNAL },
  v43RouteDestination: { marginTop: 4, fontSize: 23, lineHeight: 30, fontWeight: '900', color: INK },
  v43RouteNote: { marginTop: 8, fontSize: 16, lineHeight: 23, color: MUTED },
  v43MissionSection: { marginTop: 42 },
  v43MissionCard: { minHeight: 126, paddingVertical: 18, borderTopWidth: 1, borderTopColor: LINE, flexDirection: 'row', alignItems: 'center', gap: 16 },
  v43MissionCopy: { flex: 1 },
  v43MissionTopline: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  v43MissionNumber: { fontSize: 16, fontWeight: '900', color: SIGNAL },
  v43MissionStatus: { paddingHorizontal: 10, paddingVertical: 5, borderRadius: 14, backgroundColor: INK },
  v43MissionStatusSkipped: { backgroundColor: '#D9D4C9' },
  v43MissionStatusText: { fontSize: 14, fontWeight: '900', color: BONE },
  v43MissionStatusTextSkipped: { color: MUTED },
  v43MissionTitle: { marginTop: 14, fontSize: 25, lineHeight: 32, fontWeight: '900', color: INK },
  v43MissionPhoto: { width: 94, height: 94, borderRadius: 4, backgroundColor: SOFT },
  v43LegacyCard: { padding: 20, borderWidth: 1, borderColor: LINE },
  v43LegacyText: { fontSize: 16, lineHeight: 24, color: MUTED },
  v43RecoveryCard: { marginTop: 28, padding: 20, backgroundColor: '#EAE5D9' },
  v43RecoveryTitle: { fontSize: 19, fontWeight: '900', color: INK },
  v43RecoveryBody: { marginTop: 7, fontSize: 16, lineHeight: 24, color: MUTED },
  v43ShareButton: { marginTop: 34, minHeight: 72, borderRadius: 36, backgroundColor: INK, paddingHorizontal: 26, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  v43ShareText: { fontSize: 21, fontWeight: '900', color: BONE },
  v43ShareArrow: { fontSize: 28, color: SIGNAL },
  v42TicketFlowScreen: {
    flex: 1,
    backgroundColor: '#F5F1E8',
    paddingTop: 58,
    paddingHorizontal: 24,
    paddingBottom: 28,
  },
  v42TicketTopBar: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  v42TicketTopBrand: {
    fontSize: 23,
    fontWeight: '900',
    letterSpacing: 7,
    color: INK,
  },
  v42TicketBack: {
    position: 'absolute',
    left: 0,
    width: 46,
    height: 46,
    justifyContent: 'center',
    zIndex: 2,
  },
  v42TicketBackText: {
    fontSize: 34,
    color: INK,
  },
  v42TicketTopSpacer: {
    position: 'absolute',
    right: 0,
    width: 46,
    height: 46,
  },
  v42PrintingTitle: {
    marginTop: 38,
    fontSize: 30,
    lineHeight: 38,
    fontWeight: '900',
    letterSpacing: -1.2,
    color: INK,
    textAlign: 'center',
  },
  v42PrinterStage: {
    alignSelf: 'center',
    width: 330,
    height: 490,
    marginTop: 26,
  },
  v42PrinterHousing: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 70,
    borderRadius: 15,
    backgroundColor: '#1A1917',
    zIndex: 5,
    shadowColor: '#000',
    shadowOpacity: 0.18,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
  },
  v42PrinterSlot: {
    position: 'absolute',
    left: 20,
    right: 20,
    bottom: 12,
    height: 13,
    borderRadius: 7,
    backgroundColor: '#090908',
  },
  v42PrinterGlow: {
    position: 'absolute',
    left: 26,
    right: 26,
    bottom: 20,
    height: 9,
    borderRadius: 5,
    backgroundColor: SIGNAL,
    shadowColor: SIGNAL,
    shadowOpacity: 0.7,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 0 },
  },
  v42TicketRevealWindow: {
    position: 'absolute',
    top: 50,
    left: 9,
    right: 9,
    height: 440,
    overflow: 'hidden',
    alignItems: 'center',
  },
  v42ReadyTicketStage: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 20,
  },
  v42TicketPaper: {
    width: 312,
    height: 432,
    paddingHorizontal: 26,
    paddingTop: 25,
    paddingBottom: 22,
    backgroundColor: '#FCF8EE',
    borderWidth: 1,
    borderColor: '#D8D0C3',
    shadowColor: '#000',
    shadowOpacity: 0.13,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 9 },
  },
  v42TicketNotch: {
    position: 'absolute',
    top: 186,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#F5F1E8',
    borderWidth: 1,
    borderColor: '#D8D0C3',
  },
  v42TicketNotchLeft: { left: -13 },
  v42TicketNotchRight: { right: -13 },
  v42TicketHeader: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
  },
  v42TicketBrand: {
    fontSize: 35,
    lineHeight: 38,
    fontWeight: '900',
    letterSpacing: -1.8,
    color: INK,
  },
  v42TicketSerial: {
    paddingBottom: 4,
    fontSize: 14,
    fontWeight: '800',
    letterSpacing: 1.6,
    color: MUTED,
  },
  v42TicketRule: {
    height: 1,
    marginTop: 17,
    marginBottom: 14,
    backgroundColor: '#BEB6AA',
  },
  v42TicketLabel: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '900',
    color: '#5E5951',
  },
  v42TicketTimeRow: {
    marginTop: 2,
    flexDirection: 'row',
    alignItems: 'flex-end',
  },
  v42TicketTime: {
    fontSize: 63,
    lineHeight: 67,
    fontWeight: '900',
    letterSpacing: -3.5,
    color: INK,
  },
  v42TicketTimeUnit: {
    marginLeft: 7,
    marginBottom: 8,
    fontSize: 23,
    fontWeight: '900',
    color: INK,
  },
  v42TicketMoodRow: {
    minHeight: 93,
    flexDirection: 'row',
    alignItems: 'center',
  },
  v42TicketMoodCopy: {
    flex: 1,
  },
  v42TicketMood: {
    marginTop: 3,
    fontSize: 39,
    lineHeight: 46,
    fontWeight: '900',
    letterSpacing: -1.8,
    color: INK,
  },
  v42TicketStamp: {
    position: 'absolute',
    right: -4,
    bottom: 10,
    paddingHorizontal: 13,
    paddingVertical: 8,
    borderWidth: 3,
    borderColor: SIGNAL,
    backgroundColor: 'rgba(252,248,238,0.76)',
  },
  v42TicketStampText: {
    fontSize: 19,
    fontWeight: '900',
    letterSpacing: 0.6,
    color: SIGNAL,
  },
  v42TicketDash: {
    marginTop: 6,
    borderTopWidth: 1,
    borderStyle: 'dashed',
    borderColor: '#BEB6AA',
  },
  v42TicketFooter: {
    flex: 1,
    paddingTop: 20,
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
  },
  v42TicketBarcode: {
    height: 56,
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: 3,
  },
  v42TicketBar: {
    height: '100%',
    backgroundColor: INK,
  },
  v42TicketFooterMark: {
    paddingBottom: 2,
    fontSize: 15,
    fontWeight: '900',
    letterSpacing: 2,
    color: SIGNAL,
  },
  v42DepartButton: {
    minHeight: 76,
    borderRadius: 38,
    backgroundColor: INK,
    paddingHorizontal: 28,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 18,
  },
  v42DepartButtonLocked: {
    opacity: 0.28,
  },
  v42DepartText: {
    fontSize: 24,
    fontWeight: '900',
    color: BONE,
  },
  v42DepartArrow: {
    fontSize: 32,
    color: SIGNAL,
  },
  v42TicketErrorPanel: {
    position: 'absolute',
    left: 24,
    right: 24,
    bottom: 24,
    padding: 16,
    borderWidth: 1,
    borderColor: '#D3CEC1',
    backgroundColor: '#FCF8EE',
  },
  v42TicketErrorText: {
    fontSize: 16,
    lineHeight: 23,
    fontWeight: '700',
    color: INK,
  },
  v42TicketRetry: {
    minHeight: 56,
    marginTop: 12,
    paddingHorizontal: 18,
    backgroundColor: SIGNAL,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  v42TicketRetryText: {
    fontSize: 20,
    fontWeight: '900',
    color: INK,
  },
  v42TicketRetryArrow: {
    fontSize: 28,
    color: INK,
  },
  v35Pressed: { opacity: 0.78, transform: [{ scale: 0.985 }] },
  v35HomeScreen: { flex: 1, backgroundColor: '#F5F1E8', paddingTop: 58, paddingHorizontal: 24, paddingBottom: 28 },
  v35TopBar: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  v35Brand: { fontSize: 42, lineHeight: 44, fontWeight: '900', letterSpacing: -2.7, color: INK },
  v35BrandSlash: { width: 21, height: 10, marginLeft: 124, marginTop: -5, backgroundColor: SIGNAL, transform: [{ rotate: '-8deg' }] },
  v35MenuButton: { width: 56, height: 56, borderRadius: 28, backgroundColor: '#EAE5DB', alignItems: 'center', justifyContent: 'center', gap: 5 },
  v35MenuLine: { width: 23, height: 3, borderRadius: 2, backgroundColor: INK },
  v35MenuLineShort: { width: 16, height: 3, borderRadius: 2, backgroundColor: INK },
  v35RouteSketch: { height: 145, marginTop: 10, position: 'relative', overflow: 'hidden' },
  v35CityBlock: { position: 'absolute', bottom: 18, width: 26, backgroundColor: '#DCD8CF', opacity: 0.76 },
  v35RouteDash: { position: 'absolute', height: 4, borderRadius: 999, backgroundColor: SIGNAL, opacity: 0.96 },
  v35MapPin: { position: 'absolute', width: 20, height: 20, borderRadius: 10, backgroundColor: '#F5F1E8', borderWidth: 4, borderColor: SIGNAL, alignItems: 'center', justifyContent: 'center', zIndex: 3 },
  v35MapPinCore: { width: 6, height: 6, borderRadius: 3, backgroundColor: SIGNAL },
  v36TravelerDot: { position: 'absolute', left: '7%', top: 84, width: 16, height: 16, borderRadius: 8, backgroundColor: '#F5F1E8', borderWidth: 3, borderColor: SIGNAL, alignItems: 'center', justifyContent: 'center', zIndex: 6, shadowColor: SIGNAL, shadowOpacity: 0.28, shadowRadius: 7, shadowOffset: { width: 0, height: 0 } },
  v36TravelerDotCore: { width: 5, height: 5, borderRadius: 3, backgroundColor: SIGNAL },
  v35SketchBench: { position: 'absolute', right: '26%', top: 52, width: 44, height: 30 },
  v35BenchSeat: { position: 'absolute', left: 0, right: 0, top: 8, height: 7, borderRadius: 2, backgroundColor: INK },
  v35BenchLeg: { position: 'absolute', left: 4, bottom: 0, width: 4, height: 15, backgroundColor: INK },
  v35BenchLegRight: { left: undefined, right: 2 },
  v35SketchFlag: { position: 'absolute', right: '6%', top: 47, width: 34, height: 42 },
  v35FlagPole: { position: 'absolute', left: 4, top: 0, width: 4, height: 42, backgroundColor: INK, transform: [{ rotate: '5deg' }] },
  v35FlagCloth: { position: 'absolute', left: 9, top: 3, width: 25, height: 17, backgroundColor: SIGNAL, transform: [{ rotate: '7deg' }] },
  v35HomeQuestion: { marginTop: 4, fontSize: 38, lineHeight: 47, fontWeight: '900', letterSpacing: -2.2, color: INK, textAlign: 'center' },
  v35Underline: {
    alignSelf: 'center',
    marginTop: 0,
    marginLeft: 112,
  },
  v35MinuteReadout: { marginTop: 25, alignSelf: 'center', flexDirection: 'row', alignItems: 'flex-end', gap: 9 },
  v35MinuteNumber: { fontSize: 78, lineHeight: 82, fontWeight: '900', letterSpacing: -4, color: SIGNAL },
  v35MinuteUnit: { marginBottom: 11, fontSize: 17, fontWeight: '900', color: INK },
  v35SliderWrap: { height: 62, marginTop: 11, marginHorizontal: 8, position: 'relative' },
  v35SliderRail: { position: 'absolute', left: 0, right: 0, top: 10, height: 9, borderRadius: 5, backgroundColor: '#D8D4CB' },
  v35SliderFill: { position: 'absolute', left: 0, top: 10, height: 9, borderRadius: 5, backgroundColor: SIGNAL },
  v35TickWrap: { position: 'absolute', top: 5, width: 1, alignItems: 'center' },
  v35Tick: { width: 9, height: 9, marginLeft: -4, borderRadius: 5, backgroundColor: '#BEB9AF' },
  v35TickActive: { backgroundColor: SIGNAL },
  v35TickLabel: { width: 28, marginTop: 12, marginLeft: -14, textAlign: 'center', fontSize: 11, fontWeight: '700', color: INK },
  v35SliderThumb: { position: 'absolute', top: 0, width: 42, height: 42, marginLeft: -21, borderRadius: 21, backgroundColor: BONE, borderWidth: 2, borderColor: '#E9E4DA', alignItems: 'center', justifyContent: 'center', shadowColor: '#000', shadowOpacity: 0.18, shadowRadius: 6, shadowOffset: { width: 0, height: 3 } },
  v35SliderThumbCore: { width: 26, height: 26, borderRadius: 13, backgroundColor: SIGNAL },
  v35TicketButton: { marginTop: 16, minHeight: 78, backgroundColor: SIGNAL, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 24, position: 'relative', overflow: 'hidden' },
  v35TicketButtonPressed: { transform: [{ scale: 0.988 }], opacity: 0.88 },
  v35TicketNotchLeft: { position: 'absolute', left: -10, top: '50%', marginTop: -10, width: 20, height: 20, borderRadius: 10, backgroundColor: '#F5F1E8' },
  v35TicketNotchRight: { position: 'absolute', right: -10, top: '50%', marginTop: -10, width: 20, height: 20, borderRadius: 10, backgroundColor: '#F5F1E8' },
  v35TicketArrow: { fontSize: 36, color: INK },
  v35TicketText: { flex: 1, marginLeft: 15, fontSize: 21, fontWeight: '900', letterSpacing: -0.8, color: INK, textAlign: 'center' },
  v35TicketDivider: { width: 1, height: 52, borderLeftWidth: 1, borderStyle: 'dashed', borderColor: 'rgba(17,17,15,0.6)', marginHorizontal: 16 },
  v35TicketMark: { fontSize: 24, color: '#9D331B', transform: [{ rotate: '18deg' }] },
  v35CompletedButton: { marginTop: 11, minHeight: 54, borderWidth: 1, borderColor: '#CFC9BD', flexDirection: 'row', alignItems: 'center', paddingHorizontal: 18, backgroundColor: 'rgba(255,255,255,0.18)' },
  v35CompletedText: { fontSize: 16, fontWeight: '800', color: INK },
  v35CompletedCount: { marginLeft: 10, minWidth: 25, height: 25, paddingHorizontal: 7, borderRadius: 13, backgroundColor: INK, alignItems: 'center', justifyContent: 'center' },
  v35CompletedCountText: { fontSize: 10, fontWeight: '800', color: BONE },
  v35CompletedArrow: { marginLeft: 'auto', fontSize: 23, color: SIGNAL },
  v35MoodScreen: { flex: 1, backgroundColor: '#F5F1E8', paddingTop: 57, paddingHorizontal: 24, paddingBottom: 24 },
  v35MoodTop: { flexDirection: 'row', alignItems: 'center' },
  v35BackButton: { width: 38, height: 44, justifyContent: 'center' },
  v35BackArrow: { fontSize: 48, lineHeight: 48, fontWeight: '300', color: INK },
  v35MoodBrand: { marginLeft: 18, fontSize: 35, fontWeight: '900', letterSpacing: -2, color: INK },
  v35TimePill: { marginLeft: 'auto', minHeight: 48, borderRadius: 24, backgroundColor: INK, paddingHorizontal: 16, flexDirection: 'row', alignItems: 'center', gap: 8 },
  v35TimePillIcon: { fontSize: 18, fontWeight: '800', color: SIGNAL },
  v35TimePillText: { fontSize: 14, fontWeight: '900', color: BONE },
  v35MoodTitle: { marginTop: 55, fontSize: 42, lineHeight: 48, fontWeight: '900', letterSpacing: -2.2, color: INK, textAlign: 'center' },
  v35UnderlineMood: { alignSelf: 'flex-end', marginRight: 43, marginTop: 2, width: 114, height: 6, borderRadius: 4, backgroundColor: SIGNAL, transform: [{ rotate: '-4deg' }] },
  v35MoodScroll: { paddingTop: 34, paddingBottom: 18 },
  v35MoodGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', rowGap: 10 },
  v35MoodCard: { width: '48%', minHeight: 148, borderWidth: 1, borderColor: '#D6D0C5', borderRadius: 12, backgroundColor: 'rgba(255,255,255,0.2)', alignItems: 'center', justifyContent: 'center', paddingHorizontal: 12 },
  v35MoodCardActive: { borderWidth: 2, borderColor: SIGNAL, backgroundColor: '#F8EFE6' },
  v35MoodArt: { width: 90, height: 72, alignItems: 'center', justifyContent: 'center', position: 'relative' },
  v35MoodSymbol: { fontSize: 54, lineHeight: 60, fontWeight: '900', color: INK },
  v35MoodSymbolActive: { color: INK },
  v35MoodCardLabel: { marginTop: 3, fontSize: 20, fontWeight: '900', color: INK },
  v35MoodPrimary: { minHeight: 72, backgroundColor: SIGNAL, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', position: 'relative', overflow: 'hidden' },
  v35MoodPrimaryDisabled: { opacity: 0.42 },
  v35MoodPrimaryText: { fontSize: 29, fontWeight: '900', color: INK },
  v35MoodPrimaryDivider: { position: 'absolute', right: 72, top: 10, bottom: 10, width: 1, borderLeftWidth: 1, borderStyle: 'dashed', borderColor: 'rgba(17,17,15,0.52)' },
  v35MoodPrimaryArrow: { position: 'absolute', right: 23, fontSize: 31, color: INK },
  v35PreparingScreen: { flex: 1, backgroundColor: '#F5F1E8', paddingTop: 62, paddingHorizontal: 24, alignItems: 'center' },
  v35PreparingBrand: { alignSelf: 'flex-start', fontSize: 39, fontWeight: '900', letterSpacing: -2.5, color: INK },
  v35PreparingTitle: { marginTop: 78, fontSize: 44, lineHeight: 49, fontWeight: '900', letterSpacing: -2, color: INK, textAlign: 'center' },
  v35PreparingUnderline: { marginTop: 2, width: 165, height: 7, borderRadius: 4, backgroundColor: SIGNAL, transform: [{ rotate: '-4deg' }] },
  v35Printer: { marginTop: 36, width: '94%', height: 410, position: 'relative', alignItems: 'center', overflow: 'hidden' },
  v35PrinterTop: { position: 'absolute', top: 0, width: '94%', height: 88, borderRadius: 16, backgroundColor: '#A9A49A', borderWidth: 1, borderColor: '#8E887F' },
  v35PrinterSlot: { position: 'absolute', top: 32, width: '83%', height: 24, borderRadius: 10, backgroundColor: '#171614', zIndex: 4 },
  v35PrintingTicket: { position: 'absolute', top: 54, width: '78%', minHeight: 330, backgroundColor: '#F6F1E8', padding: 20, borderWidth: 1, borderColor: '#D2CBC0', shadowColor: '#000', shadowOpacity: 0.12, shadowRadius: 8, shadowOffset: { width: 0, height: 4 } },
  v35PrintOrangeBand: { height: 26, marginHorizontal: -20, marginTop: -20, marginBottom: 16, backgroundColor: SIGNAL },
  v35PrintBrand: { fontSize: 28, fontWeight: '900', letterSpacing: -1.7, color: INK },
  v35PrintDash: { height: 1, marginVertical: 14, borderTopWidth: 1, borderStyle: 'dashed', borderColor: '#BDB7AD' },
  v35PrintFacts: { flexDirection: 'row', alignItems: 'center' },
  v35PrintLabel: { fontSize: 11, fontWeight: '900', color: INK },
  v35PrintMinute: { marginTop: 3, fontSize: 46, lineHeight: 50, fontWeight: '900', letterSpacing: -2, color: SIGNAL },
  v35PrintMinuteUnit: { fontSize: 14, color: INK },
  v35PrintDivider: { width: 1, height: 72, marginHorizontal: 18, backgroundColor: '#C5BFB5' },
  v35PrintMoodBlock: { flex: 1 },
  v35PrintMood: { marginTop: 11, fontSize: 21, lineHeight: 26, fontWeight: '900', color: INK },
  v35PrintDestination: { fontSize: 19, fontWeight: '900', color: INK },
  v35PrintBarcode: { marginTop: 27, height: 42, flexDirection: 'row', gap: 3, justifyContent: 'center', alignItems: 'stretch' },
  v35PrintBar: { backgroundColor: INK },
  v35PreparingStatus: { marginTop: 8, fontSize: 12, fontWeight: '700', color: MUTED, textAlign: 'center' },
  v35JourneyScreen: { flex: 1, backgroundColor: '#090909', paddingTop: 57, paddingHorizontal: 24, paddingBottom: 25 },
  v35JourneyTop: { flexDirection: 'row', alignItems: 'center' },
  v35JourneyBack: { width: 44, height: 44, justifyContent: 'center' },
  v35JourneyBackText: { fontSize: 38, color: BONE },
  v35JourneyBrand: { marginLeft: 10, fontSize: 34, fontWeight: '900', letterSpacing: -2, color: BONE },
  v35JourneyProgress: { marginLeft: 'auto', flexDirection: 'row', alignItems: 'center' },
  v35JourneyProgressItem: { flexDirection: 'row', alignItems: 'center' },
  v35JourneyProgressDot: { width: 11, height: 11, borderRadius: 6, borderWidth: 2, borderColor: '#6F6F6C', backgroundColor: '#090909' },
  v35JourneyProgressCurrent: { width: 17, height: 17, borderRadius: 9, borderColor: SIGNAL, borderWidth: 4 },
  v35JourneyProgressDone: { borderColor: SIGNAL, backgroundColor: SIGNAL },
  v35JourneyProgressLine: { width: 16, height: 1, marginHorizontal: 4, backgroundColor: '#66645F' },
  v35JourneyProgressLineDone: { backgroundColor: SIGNAL },
  v35JourneyFlag: { marginLeft: 7, fontSize: 18, color: '#8E8C86' },
  v35JourneyHero: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingBottom: 35 },
  v35Compass: { width: 245, height: 245, borderRadius: 123, borderWidth: 18, borderColor: '#272727', alignItems: 'center', justifyContent: 'center', backgroundColor: '#0E0E0E' },
  v35CompassTicks: { position: 'absolute', top: 25, bottom: 25, left: '50%', width: 5, marginLeft: -2.5, borderTopWidth: 18, borderBottomWidth: 18, borderColor: '#6D6B66' },
  v35CompassArrow: { fontSize: 150, lineHeight: 160, fontWeight: '900', color: SIGNAL },
  v35JourneyDistance: { marginTop: 22, fontSize: 76, lineHeight: 80, fontWeight: '900', letterSpacing: -4, color: SIGNAL },
  v35JourneyDistanceUnit: { fontSize: 30, color: BONE },
  v35JourneyInstruction: { marginTop: 12, fontSize: 29, lineHeight: 36, fontWeight: '900', letterSpacing: -1.4, color: BONE, textAlign: 'center' },
  v35JourneyStatus: { marginTop: 12, fontSize: 12, color: '#A29E95' },
  v35JourneyMapWrap: { flex: 1, marginTop: 28, marginBottom: 24, borderRadius: 28, overflow: 'hidden', borderWidth: 1, borderColor: '#2B2B2B' },
  v35JourneyMap: { flex: 1 },
  v35JourneyMapClose: { position: 'absolute', top: 16, right: 16, width: 40, height: 40, borderRadius: 20, backgroundColor: 'rgba(9,9,9,0.82)', alignItems: 'center', justifyContent: 'center' },
  v35JourneyMapCloseText: { fontSize: 24, color: BONE },
  v35QuestPulse: { position: 'absolute', left: 24, right: 24, top: 125, minHeight: 44, borderRadius: 22, backgroundColor: SIGNAL, alignItems: 'center', justifyContent: 'center' },
  v35QuestPulseText: { fontSize: 13, fontWeight: '900', color: INK },
  v35JourneyBottom: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  v35JourneyCamera: { width: 68, height: 68, borderRadius: 34, backgroundColor: SIGNAL, alignItems: 'center', justifyContent: 'center' },
  v35JourneyCameraText: { fontSize: 31, color: BONE },
  v35JourneyPrimary: { flex: 1, minHeight: 62, borderWidth: 1, borderColor: '#3A3936', backgroundColor: 'transparent', flexDirection: 'row', alignItems: 'center', paddingHorizontal: 18, position: 'relative' },
  v35JourneyPrimaryPressed: { opacity: 0.72 },
  v35JourneyPrimaryArrow: { fontSize: 20, color: '#A9A59C' },
  v35JourneyPrimaryDivider: { width: 1, height: 28, marginHorizontal: 13, backgroundColor: '#3A3936' },
  v35JourneyPrimaryText: { flex: 1, fontSize: 16, fontWeight: '800', color: BONE, textAlign: 'center' },
  v35JourneyPressed: { opacity: 0.75 },
  v35DevAdvance: { position: 'absolute', right: 0, bottom: 76, paddingHorizontal: 12, paddingVertical: 7, backgroundColor: '#2A2926', borderRadius: 13 },
  v35DevAdvanceText: { fontSize: 9, color: '#A9A59B' },
  v35FinishScreen: { flex: 1, backgroundColor: '#F5F1E8', paddingTop: 58 },
  v35FinishTop: { paddingHorizontal: 24, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  v35FinishBrand: { fontSize: 40, fontWeight: '900', letterSpacing: -2.5, color: INK },
  v35FinishMenu: { width: 52, height: 52, borderRadius: 26, backgroundColor: '#E9E4D9', alignItems: 'center', justifyContent: 'center', gap: 4 },
  v35FinishScroll: { paddingHorizontal: 24, paddingBottom: 50 },
  v35FinishTitle: { marginTop: 40, fontSize: 44, fontWeight: '900', letterSpacing: -2.4, color: INK, textAlign: 'center' },
  v35Postcard: { marginTop: 27, backgroundColor: '#F7F2E9', borderWidth: 1, borderColor: '#E0D9CD', padding: 16, shadowColor: '#000', shadowOpacity: 0.13, shadowRadius: 12, shadowOffset: { width: 0, height: 7 } },
  v35PostcardTop: { height: 48, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: 1, borderStyle: 'dashed', borderColor: '#BDB7AD', marginBottom: 14 },
  v35PostcardBrand: { fontSize: 25, fontWeight: '900', letterSpacing: -1.4, color: INK },
  v35FinishStamp: { width: 82, height: 82, marginTop: 25, borderWidth: 3, borderColor: SIGNAL, borderRadius: 41, alignItems: 'center', justifyContent: 'center', transform: [{ rotate: '-9deg' }], backgroundColor: 'rgba(245,241,232,0.88)', zIndex: 4 },
  v35FinishStampText: { fontSize: 14, fontWeight: '900', color: SIGNAL },
  v35FinishStampPlane: { marginTop: 4, fontSize: 16, color: SIGNAL },
  v35PostcardHeroPhoto: { width: '100%', height: 236, borderRadius: 13 },
  v35PostcardThumbRow: { marginTop: 8, flexDirection: 'row', gap: 7 },
  v35PostcardThumb: { flex: 1, height: 78, borderRadius: 8 },
  v35PostcardNoPhoto: { height: 225, backgroundColor: '#E7E2D8', alignItems: 'center', justifyContent: 'center', position: 'relative', overflow: 'hidden' },
  v35PostcardRouteLine: { position: 'absolute', width: 220, height: 2, backgroundColor: SIGNAL, transform: [{ rotate: '-13deg' }] },
  v35PostcardRoutePin: { width: 22, height: 22, borderRadius: 11, borderWidth: 5, borderColor: SIGNAL, backgroundColor: BONE },
  v35PostcardNoPhotoText: { marginTop: 58, fontSize: 18, fontWeight: '900', color: INK },
  v35PostcardMetaRow: { marginTop: 17, minHeight: 70, flexDirection: 'row', alignItems: 'center' },
  v35PostcardPlace: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 9 },
  v35PostcardPlaceIcon: { fontSize: 22, color: SIGNAL },
  v35PostcardPlaceText: { flex: 1, fontSize: 22, lineHeight: 27, fontWeight: '900', color: INK },
  v35PostcardMetaDivider: { width: 1, height: 58, marginHorizontal: 14, backgroundColor: '#C9C2B6' },
  v35PostcardFacts: { width: 110, gap: 5 },
  v35PostcardFact: { fontSize: 14, fontWeight: '800', color: INK },
  v35FinishPrimary: { marginTop: 28, minHeight: 68, backgroundColor: SIGNAL, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 16 },
  v35FinishPrimaryArrow: { fontSize: 32, color: INK },
  v35FinishPrimaryText: { fontSize: 25, fontWeight: '900', color: INK },
  v35FinishSecondary: { marginTop: 10, minHeight: 56, borderWidth: 1, borderColor: '#CBC5BA', alignItems: 'center', justifyContent: 'center' },
  v35FinishSecondaryText: { fontSize: 16, fontWeight: '800', color: INK },
  v35FeedbackPanel: { marginTop: 30, paddingTop: 21, borderTopWidth: 1, borderColor: '#D3CDC2' },
  v35FeedbackTitle: { marginBottom: 12, fontSize: 15, fontWeight: '900', color: INK },
  v35ReviewHeaderTitle: { flex: 1, textAlign: 'center', fontSize: 29, fontWeight: '900', letterSpacing: -1.5, color: INK },
  v35ReviewPhotoSection: { marginTop: 20 },
  v35ReviewHeroPhoto: { width: '100%', height: 360, borderRadius: 18 },
  v35ReviewThumbStrip: { marginTop: 12, gap: 8, paddingBottom: 4 },
  v35ReviewThumb: { width: 76, height: 76, borderRadius: 10, borderWidth: 2, borderColor: 'transparent' },
  v35ReviewThumbActive: { borderColor: SIGNAL },
  v35ReviewEmptyPhoto: { marginTop: 20, minHeight: 170, borderWidth: 1, borderColor: '#D2CBC0', alignItems: 'center', justifyContent: 'center' },
  v35ReviewEmptyTitle: { fontSize: 16, fontWeight: '800', color: MUTED },
  v35ReviewShare: { marginTop: 26, minHeight: 66, backgroundColor: SIGNAL, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 14 },
  v35ReviewShareIcon: { fontSize: 28, color: BONE },
  v35ReviewShareText: { fontSize: 21, fontWeight: '900', color: BONE },
  // v0.38 — five clearer moods; surprise gets the last full-width beat.
  v38MoodWide: {
    width: '100%',
    minHeight: 126,
  },
  v38PhotoPressed: {
    opacity: 0.82,
  },
  v38ZoomBadge: {
    position: 'absolute',
    right: 14,
    bottom: 14,
    paddingHorizontal: 11,
    paddingVertical: 7,
    borderRadius: 16,
    backgroundColor: 'rgba(17,17,15,0.78)',
  },
  v38ZoomBadgeText: {
    fontSize: 10,
    fontWeight: '700',
    color: BONE,
  },
  v38ZoomScreen: {
    flex: 1,
    backgroundColor: '#000',
  },
  v38ZoomScroll: {
    flex: 1,
  },
  v38ZoomContent: {
    flexGrow: 1,
    minHeight: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  v38ZoomImage: {
    width: '100%',
    height: '100%',
    minHeight: 620,
  },
  v38ZoomClose: {
    position: 'absolute',
    top: 58,
    left: 22,
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: 'rgba(17,17,15,0.72)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  v38ZoomCloseText: {
    fontSize: 30,
    lineHeight: 32,
    color: BONE,
  },
  v38ZoomHint: {
    position: 'absolute',
    bottom: 36,
    alignSelf: 'center',
    fontSize: 11,
    fontWeight: '700',
    color: 'rgba(241,239,231,0.78)',
  },
  v38ShareSection: {
    marginTop: 34,
  },
  v38SharePreviewLabel: {
    marginBottom: 12,
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1.8,
    color: MUTED,
  },
  v38ShareTicket: {
    width: '100%',
    minHeight: 570,
    padding: 24,
    backgroundColor: '#FAF7EE',
    borderWidth: 1,
    borderColor: '#CFC8B8',
    position: 'relative',
    overflow: 'hidden',
  },
  v38ShareSignal: {
    position: 'absolute',
    left: 0,
    top: 0,
    right: 0,
    height: 10,
    backgroundColor: SIGNAL,
  },
  v38ShareTicketHead: {
    marginTop: 8,
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  v38ShareBrand: {
    fontSize: 25,
    fontWeight: '900',
    letterSpacing: 2,
    color: INK,
  },
  v38ShareMicro: {
    marginTop: 3,
    fontSize: 8,
    fontWeight: '800',
    letterSpacing: 2.2,
    color: SIGNAL,
  },
  v38ShareSerial: {
    marginTop: 4,
    fontSize: 8,
    fontWeight: '800',
    letterSpacing: 1.2,
    color: MUTED,
  },
  v38ShareDash: {
    marginVertical: 18,
    borderTopWidth: 1,
    borderStyle: 'dashed',
    borderColor: '#BEB7A8',
  },
  v38ShareDestinationLabel: {
    fontSize: 8,
    fontWeight: '800',
    letterSpacing: 2,
    color: MUTED,
  },
  v38ShareDestination: {
    marginTop: 8,
    fontSize: 34,
    lineHeight: 39,
    fontWeight: '800',
    letterSpacing: -1.4,
    color: INK,
  },
  v38SharePhoto: {
    marginTop: 18,
    width: '100%',
    height: 205,
    borderRadius: 4,
    backgroundColor: SOFT,
  },
  v38ShareNoPhoto: {
    marginTop: 18,
    height: 205,
    backgroundColor: SOFT,
    alignItems: 'center',
    justifyContent: 'center',
  },
  v38ShareNoPhotoMark: {
    fontSize: 20,
    color: SIGNAL,
  },
  v38ShareRouteRow: {
    marginTop: 20,
    height: 28,
    flexDirection: 'row',
    alignItems: 'center',
  },
  v38ShareRouteStart: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: SIGNAL,
  },
  v38ShareRouteLine: {
    flex: 1,
    height: 3,
    marginLeft: 5,
    backgroundColor: SIGNAL,
  },
  v38ShareRouteFlag: {
    marginLeft: 6,
    fontSize: 25,
    color: SIGNAL,
  },
  v38ShareFacts: {
    marginTop: 18,
    flexDirection: 'row',
    gap: 12,
  },
  v38ShareFact: {
    flex: 1,
  },
  v38ShareFactLabel: {
    fontSize: 7,
    fontWeight: '800',
    letterSpacing: 1.5,
    color: MUTED,
  },
  v38ShareFactValue: {
    marginTop: 5,
    fontSize: 11,
    lineHeight: 15,
    fontWeight: '800',
    color: INK,
  },
  v38ShareFoot: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  v38ShareFootText: {
    fontSize: 8,
    fontWeight: '800',
    letterSpacing: 1.5,
    color: MUTED,
  },
  v41PrinterScan: { position: 'absolute', top: 38, width: 76, height: 4, borderRadius: 2, backgroundColor: SIGNAL, zIndex: 6 },
  v41PreparingStatus: { marginTop: 8, paddingHorizontal: 24, fontSize: 16, lineHeight: 23, fontWeight: '800', color: '#5F5A52', textAlign: 'center' },
  v41TicketErrorPanel: { width: '100%', marginTop: 14, padding: 16, borderWidth: 1, borderColor: '#D3CEC1', backgroundColor: '#FAF7EE' },
  v41TicketErrorText: { fontSize: 16, lineHeight: 23, fontWeight: '700', color: INK },
  v41TicketRetry: { minHeight: 58, marginTop: 14, paddingHorizontal: 18, backgroundColor: SIGNAL, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  v41TicketRetryText: { fontSize: 20, fontWeight: '900', color: INK },
  v41TicketRetryArrow: { fontSize: 28, color: INK },
  v41ActiveFind: { marginTop: 18, alignSelf: 'stretch', minHeight: 86, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12, paddingHorizontal: 18, paddingVertical: 14, borderWidth: 1, borderColor: 'rgba(241,239,231,0.34)', borderRadius: 18, backgroundColor: 'rgba(255,255,255,0.035)' },
  v41ActiveFindCopy: { flex: 1 },
  v41ActiveFindLabel: { fontSize: 14, fontWeight: '900', color: SIGNAL },
  v41ActiveFindTitle: { marginTop: 4, fontSize: 22, lineHeight: 27, fontWeight: '900', color: BONE },
  v41ActiveFindAction: { fontSize: 16, fontWeight: '900', color: SIGNAL },
  v41DevAdvance: { position: 'absolute', right: 0, bottom: 82, minHeight: 44, paddingHorizontal: 15, borderRadius: 22, backgroundColor: '#302F2B', alignItems: 'center', justifyContent: 'center' },
  v41DevAdvanceText: { fontSize: 14, fontWeight: '800', color: BONE },
  v41MissionScreen: { flex: 1, backgroundColor: '#F5F1E8', paddingTop: 58, paddingHorizontal: 24, paddingBottom: 28 },
  v41MissionTop: { flexDirection: 'row', alignItems: 'center' },
  v41MissionBack: { width: 44, height: 44, justifyContent: 'center' },
  v41MissionBackText: { fontSize: 36, color: INK },
  v41MissionBrand: { marginLeft: 10, fontSize: 31, fontWeight: '900', letterSpacing: -1.7, color: INK },
  v41MissionBadge: { marginLeft: 'auto', width: 42, height: 42, borderRadius: 21, backgroundColor: SIGNAL, alignItems: 'center', justifyContent: 'center' },
  v41MissionBadgeText: { fontSize: 22, fontWeight: '900', color: BONE },
  v41MissionRoute: { height: 82, marginTop: 46, flexDirection: 'row', alignItems: 'center' },
  v41MissionRouteStart: { width: 28, height: 28, borderRadius: 14, borderWidth: 4, borderColor: SIGNAL, alignItems: 'center', justifyContent: 'center' },
  v41MissionRouteCore: { width: 8, height: 8, borderRadius: 4, backgroundColor: SIGNAL },
  v41MissionRouteLine: { flex: 0.45, height: 4, backgroundColor: SIGNAL },
  v41MissionRouteQuest: { width: 56, height: 56, borderRadius: 28, backgroundColor: SIGNAL, alignItems: 'center', justifyContent: 'center' },
  v41MissionRouteQuestText: { fontSize: 27, color: BONE },
  v41MissionRouteLineMuted: { flex: 1, height: 2, backgroundColor: '#D1CBC0' },
  v41MissionHero: { flex: 1, justifyContent: 'center', paddingBottom: 28 },
  v41MissionCue: { fontSize: 16, fontWeight: '900', color: SIGNAL },
  v41MissionTitle: { marginTop: 16, maxWidth: 355, fontSize: 52, lineHeight: 60, fontWeight: '900', letterSpacing: -2.9, color: INK },
  v41MissionSafety: { marginTop: 22, maxWidth: 340, fontSize: 16, lineHeight: 24, fontWeight: '600', color: '#67625A' },
  v41MissionBottom: { gap: 10 },
  v41MissionPrimary: { minHeight: 74, backgroundColor: SIGNAL, paddingHorizontal: 22, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  v41MissionPrimaryText: { fontSize: 26, fontWeight: '900', color: INK },
  v41MissionPrimaryArrow: { fontSize: 32, color: INK },
  v41MissionSkip: { minHeight: 52, alignItems: 'center', justifyContent: 'center' },
  v41MissionSkipText: { fontSize: 16, fontWeight: '700', color: '#77736B' },
  v41PassportScreen: { flex: 1, backgroundColor: '#F5F1E8', paddingTop: 58 },
  v41PassportTop: { minHeight: 48, paddingHorizontal: 24, flexDirection: 'row', alignItems: 'center' },
  v41PassportBack: { width: 44, height: 44, justifyContent: 'center' },
  v41PassportBackText: { fontSize: 36, color: INK },
  v41PassportHeader: { marginLeft: 8, fontSize: 27, fontWeight: '900', letterSpacing: -1.2, color: INK },
  v41PassportMeta: { marginLeft: 'auto', fontSize: 15, fontWeight: '800', color: MUTED },
  v41PassportScroll: { paddingHorizontal: 24, paddingTop: 42, paddingBottom: 56 },
  v41PassportKicker: { fontSize: 16, fontWeight: '900', color: SIGNAL },
  v41PassportTitle: { marginTop: 12, fontSize: 42, lineHeight: 49, fontWeight: '900', letterSpacing: -2.3, color: INK },
  v41PassportStats: { marginTop: 34, paddingVertical: 22, borderTopWidth: 1, borderBottomWidth: 1, borderColor: '#CFC9BD', flexDirection: 'row' },
  v41PassportStat: { flex: 1 },
  v41PassportStatValue: { fontSize: 38, lineHeight: 42, fontWeight: '900', color: INK },
  v41PassportStatLabel: { marginTop: 5, fontSize: 14, fontWeight: '700', color: MUTED },
  v41PassportSectionRow: { marginTop: 42, marginBottom: 14, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  v41PassportSectionTitle: { fontSize: 21, fontWeight: '900', color: INK },
  v41PassportSectionMeta: { fontSize: 14, fontWeight: '700', color: MUTED },
  v41PassportList: { gap: 18 },
  v41PassportCard: { overflow: 'hidden', borderWidth: 1, borderColor: '#D2CBC0', backgroundColor: '#FAF7EE' },
  v41PassportPhoto: { width: '100%', height: 220, backgroundColor: SOFT },
  v41PassportNoPhoto: { width: '100%', height: 190, backgroundColor: '#E6E0D5', alignItems: 'center', justifyContent: 'center', overflow: 'hidden' },
  v41PassportNoPhotoLine: { position: 'absolute', width: 280, height: 4, backgroundColor: SIGNAL, transform: [{ rotate: '-12deg' }] },
  v41PassportNoPhotoDot: { width: 26, height: 26, borderRadius: 13, borderWidth: 6, borderColor: SIGNAL, backgroundColor: '#E6E0D5' },
  v41PassportNoPhotoText: { marginTop: 60, fontSize: 23, fontWeight: '900', color: INK },
  v41PassportCardBody: { padding: 18 },
  v41PassportCardTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  v41PassportCardNumber: { fontSize: 17, fontWeight: '900', color: SIGNAL },
  v41PassportCardDate: { fontSize: 14, fontWeight: '700', color: MUTED },
  v41PassportCardMood: { marginTop: 18, fontSize: 18, fontWeight: '900', color: SIGNAL },
  v41PassportCardDestination: { marginTop: 7, fontSize: 30, lineHeight: 36, fontWeight: '900', letterSpacing: -1.4, color: INK },
  v41PassportCardFacts: { marginTop: 18, flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  v41PassportCardFact: { paddingHorizontal: 10, paddingVertical: 7, borderRadius: 14, backgroundColor: '#EDE7DC', fontSize: 14, fontWeight: '800', color: INK },
  v41PassportOpen: { marginTop: 18, minHeight: 54, borderTopWidth: 1, borderColor: '#D2CBC0', paddingTop: 15, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  v41PassportOpenText: { fontSize: 17, fontWeight: '900', color: INK },
  v41PassportOpenArrow: { fontSize: 25, color: SIGNAL },
  v41PassportEmpty: { minHeight: 220, borderWidth: 1, borderColor: '#D2CBC0', alignItems: 'center', justifyContent: 'center', padding: 24 },
  v41PassportEmptyMark: { fontSize: 28, color: SIGNAL },
  v41PassportEmptyTitle: { marginTop: 22, fontSize: 21, lineHeight: 28, fontWeight: '900', color: INK, textAlign: 'center' },
  v41PassportClear: { marginTop: 30, minHeight: 54, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#D2CBC0' },
  v41PassportClearText: { fontSize: 15, fontWeight: '800', color: SIGNAL },
  v41ReadableMeta: { fontSize: 15, lineHeight: 21 },
  v41ReadableKicker: { fontSize: 17, lineHeight: 23 },
  v41ReadableBody: { fontSize: 17, lineHeight: 26 },
  v41DevelopingCode: { fontSize: 14, lineHeight: 20 },
  v41DevelopingBody: { fontSize: 16, lineHeight: 23, letterSpacing: 0.4 }
});
