import { StyleSheet } from 'react-native';
import { INK, MUTED, SIGNAL, SOFT } from '../../theme/detour-theme';

const PAPER = '#FBF7EE';
const PAPER_ALT = '#F3EDE2';
const LINE = '#CFC6B9';

export const recapOverrides = StyleSheet.create({
  v45FinishScroll: {
    paddingHorizontal: 24,
    paddingTop: 14,
    paddingBottom: 104,
  },
  v45FinishTitleWrap: {
    alignSelf: 'center',
    alignItems: 'center',
    position: 'relative',
    marginBottom: 28,
  },
  v45FinishTitleUnderline: {
    position: 'absolute',
    right: 0,
    bottom: -8,
  },
  v45FinishPrimary: {
    height: 64,
    marginTop: 24,
    backgroundColor: SIGNAL,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 14,
    borderRadius: 4,
  },
  v45FinishPrimaryArrow: {
    fontSize: 28,
    color: INK,
  },
  v45FinishPrimaryText: {
    fontSize: 22,
    fontWeight: '900',
    color: INK,
  },
  v45FinishSecondary: {
    height: 50,
    marginTop: 8,
    borderWidth: 0,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
  },
  v45FinishSecondaryText: {
    fontSize: 17,
    fontWeight: '800',
    color: MUTED,
  },

  v54TicketWrap: {
    width: '100%',
    paddingBottom: 4,
  },
  v54TicketPaper: {
    width: '100%',
    overflow: 'hidden',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: LINE,
    borderLeftWidth: 4,
    borderLeftColor: SIGNAL,
    backgroundColor: PAPER,
    shadowColor: '#000',
    shadowOpacity: 0.07,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
  },
  v54TicketHeader: {
    minHeight: 58,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: PAPER,
  },
  v54TicketBrand: {
    flex: 1.15,
    fontSize: 16,
    fontWeight: '900',
    letterSpacing: 1.8,
    color: INK,
  },
  v54TicketStatus: {
    flex: 1,
    fontSize: 13,
    fontWeight: '900',
    textAlign: 'center',
    color: SIGNAL,
  },
  v54TicketDate: {
    flex: 1.15,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '800',
    textAlign: 'right',
    color: MUTED,
  },
  v54Perforation: {
    marginHorizontal: 14,
    borderTopWidth: 1,
    borderStyle: 'dashed',
    borderColor: '#BEB5A8',
  },
  v54PerforationInset: {
    marginHorizontal: 18,
    borderTopWidth: 1,
    borderStyle: 'dashed',
    borderColor: '#C6BDB0',
  },

  v54HeroStage: {
    width: 'auto',
    aspectRatio: 1,
    marginHorizontal: 14,
    marginTop: 14,
    borderRadius: 9,
    overflow: 'hidden',
    backgroundColor: PAPER_ALT,
    position: 'relative',
  },
  v54HeroStageRoute: {
    backgroundColor: '#EAE4D9',
  },
  v54ZoomScroll: {
    width: '100%',
    height: '100%',
    backgroundColor: PAPER_ALT,
  },
  v54ZoomContent: {
    flexGrow: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  v54ZoomCanvas: {
    width: '100%',
    aspectRatio: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: PAPER_ALT,
  },
  v54HeroPhoto: {
    width: '100%',
    height: '100%',
    backgroundColor: PAPER_ALT,
  },
  v54CompleteStamp: {
    position: 'absolute',
    right: 12,
    top: 12,
    width: 64,
    height: 64,
    borderRadius: 32,
    borderWidth: 3,
    borderColor: SIGNAL,
    backgroundColor: 'rgba(251,247,238,0.9)',
    alignItems: 'center',
    justifyContent: 'center',
    transform: [{ rotate: '-10deg' }],
  },
  v54CompleteStampTop: {
    fontSize: 10,
    lineHeight: 13,
    fontWeight: '900',
    letterSpacing: 1,
    color: SIGNAL,
  },
  v54CompleteStampBottom: {
    marginTop: -1,
    fontSize: 22,
    lineHeight: 24,
    fontWeight: '900',
    color: INK,
  },
  v54DateTag: {
    position: 'absolute',
    right: 10,
    bottom: 10,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 3,
    backgroundColor: SIGNAL,
  },
  v54DateTagText: {
    fontSize: 11,
    fontWeight: '900',
    color: INK,
  },

  v54FilmStrip: {
    minHeight: 72,
    marginHorizontal: 14,
    marginTop: 10,
    paddingHorizontal: 8,
    paddingVertical: 8,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderStyle: 'dashed',
    borderColor: '#BEB5A8',
    backgroundColor: '#F7F1E7',
  },
  v54FilmPhotos: {
    height: 54,
    flexDirection: 'row',
    gap: 6,
  },
  v54FilmPress: {
    flex: 1,
    height: '100%',
    borderRadius: 5,
    overflow: 'hidden',
  },
  v54FilmPhoto: {
    width: '100%',
    height: '100%',
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#C9C0B3',
    opacity: 0.65,
    backgroundColor: SOFT,
  },
  v54FilmPhotoActive: {
    borderWidth: 2,
    borderColor: SIGNAL,
    opacity: 1,
  },

  v54TicketCopy: {
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 18,
  },
  v54MoodTicket: {
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 3,
    borderWidth: 1,
    borderColor: SIGNAL,
    backgroundColor: 'transparent',
    fontSize: 13,
    lineHeight: 17,
    fontWeight: '900',
    color: SIGNAL,
  },
  v54Destination: {
    marginTop: 10,
    fontSize: 32,
    lineHeight: 37,
    fontWeight: '900',
    letterSpacing: -1.1,
    color: INK,
  },
  v54TripFacts: {
    marginTop: 15,
    minHeight: 52,
    flexDirection: 'row',
    alignItems: 'stretch',
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: '#C8BFB2',
    backgroundColor: '#F7F1E7',
  },
  v54TripFactCell: {
    flex: 1,
    minHeight: 52,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  v54TripFactDivider: {
    position: 'absolute',
    left: 0,
    top: 11,
    bottom: 11,
    width: 1,
    backgroundColor: SIGNAL,
    opacity: 0.72,
  },
  v54TripFactText: {
    fontSize: 14,
    lineHeight: 18,
    fontWeight: '900',
    color: INK,
  },
  v54TicketRouteMark: {
    width: '108%',
    height: 82,
    marginLeft: '-4%',
    marginTop: 12,
    opacity: 0.92,
  },

  v54RouteSection: {
    paddingHorizontal: 18,
    paddingTop: 17,
    paddingBottom: 18,
    backgroundColor: PAPER,
  },
  v54RouteSectionTop: {
    minHeight: 44,
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  v54RouteSectionKicker: {
    fontSize: 11,
    lineHeight: 15,
    fontWeight: '900',
    letterSpacing: 0.7,
    color: SIGNAL,
  },
  v54RouteSectionTitle: {
    marginTop: 2,
    fontSize: 19,
    lineHeight: 24,
    fontWeight: '900',
    color: INK,
  },
  v54RouteStage: {
    width: '100%',
    height: 170,
    borderRadius: 7,
    overflow: 'hidden',
    backgroundColor: '#EAE4D9',
  },
  v54RouteTrace: {
    width: '100%',
    height: '100%',
    position: 'relative',
    backgroundColor: '#EAE4D9',
    overflow: 'hidden',
  },
  v54RouteTraceLabel: {
    position: 'absolute',
    left: 12,
    bottom: 11,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: 'rgba(251,247,238,0.92)',
  },
  v54RouteTraceLabelText: {
    fontSize: 12,
    fontWeight: '900',
    color: INK,
  },
  v54RouteMissing: {
    flex: 1,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 34,
    backgroundColor: '#EAE4D9',
  },
  v54RouteMissingTitle: {
    fontSize: 20,
    lineHeight: 26,
    fontWeight: '900',
    textAlign: 'center',
    color: INK,
  },
  v54RouteMissingBody: {
    marginTop: 7,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
    textAlign: 'center',
    color: MUTED,
  },

  v54NoteSection: {
    paddingHorizontal: 18,
    paddingTop: 17,
    paddingBottom: 20,
    backgroundColor: PAPER,
  },
  v54NoteHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 9,
  },
  v54NoteTitle: {
    fontSize: 17,
    lineHeight: 22,
    fontWeight: '900',
    color: INK,
  },
  v54NoteSaved: {
    fontSize: 11,
    fontWeight: '800',
    color: MUTED,
  },
  v54NoteInput: {
    minHeight: 104,
    paddingHorizontal: 13,
    paddingVertical: 12,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: '#BEB5A8',
    borderRadius: 5,
    backgroundColor: '#F7F1E7',
    fontSize: 17,
    lineHeight: 26,
    fontWeight: '600',
    color: INK,
  },
  v54NoteCount: {
    marginTop: 6,
    textAlign: 'right',
    fontSize: 11,
    fontWeight: '700',
    color: MUTED,
  },

  v45DetailScreen: {
    flex: 1,
    backgroundColor: '#F5F1E8',
    paddingTop: 58,
    overflow: 'hidden',
  },
  v45DetailTop: {
    height: 64,
    paddingHorizontal: 22,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  v45DetailTitle: {
    fontSize: 34,
    lineHeight: 40,
    fontWeight: '900',
    letterSpacing: -1.3,
    color: INK,
  },
  v45DetailScroll: {
    paddingHorizontal: 24,
    paddingTop: 10,
    paddingBottom: 76,
  },
  v45DetailThumbRow: {
    display: 'none',
  },
  v45RouteStrip: {
    display: 'none',
  },
  v45NoteCard: {
    display: 'none',
  },
  v45ShareButton: {
    height: 66,
    marginTop: 26,
    backgroundColor: SIGNAL,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    borderRadius: 4,
  },
  v45ShareIcon: {
    fontSize: 27,
    color: INK,
  },
  v45ShareText: {
    fontSize: 21,
    fontWeight: '900',
    color: INK,
  },

  v45Poster: {
    width: 360,
    height: 640,
    backgroundColor: '#F5F1E8',
    paddingHorizontal: 22,
    paddingTop: 18,
    paddingBottom: 14,
  },
  v45PosterTop: {
    height: 42,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  v45PosterBrand: {
    fontSize: 26,
    fontWeight: '900',
    letterSpacing: -1.2,
    color: INK,
  },
  v45PosterDate: {
    fontSize: 13,
    fontWeight: '800',
    color: MUTED,
  },
  v54PosterPhotoStage: {
    width: '100%',
    height: 240,
    borderRadius: 14,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#D0C7BA',
    backgroundColor: PAPER_ALT,
  },
  v54PosterRouteStage: {
    width: '100%',
    height: 240,
    borderRadius: 14,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#D0C7BA',
    backgroundColor: '#EAE4D9',
  },
  v54PosterCollage: {
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    backgroundColor: PAPER_ALT,
  },
  v54PosterTile: {
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#F5F1E8',
    backgroundColor: PAPER_ALT,
  },
  v54PosterTilePhoto: {
    width: '100%',
    height: '100%',
    backgroundColor: PAPER_ALT,
  },
  v54PosterSinglePhoto: {
    width: '100%',
    height: '100%',
    backgroundColor: PAPER_ALT,
  },
  v45PosterCopy: {
    paddingTop: 13,
  },
  v45PosterMood: {
    fontSize: 31,
    lineHeight: 35,
    fontWeight: '900',
    letterSpacing: -1.2,
    color: INK,
  },
  v45PosterDestination: {
    marginTop: 2,
    fontSize: 22,
    lineHeight: 27,
    fontWeight: '900',
    color: SIGNAL,
  },
  v45PosterOrangeRule: {
    display: 'none',
  },
  v54PosterFacts: {
    marginTop: 10,
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: '#CFC6B9',
  },
  v54PosterFact: {
    flex: 1,
    textAlign: 'center',
    fontSize: 17,
    lineHeight: 22,
    fontWeight: '900',
    color: INK,
  },
  v54PosterHomeRoute: {
    width: '116%',
    height: 112,
    marginLeft: '-8%',
    marginTop: 7,
  },

  v51CompleteCard: {
    display: 'none',
  },
  v51ReviewHeroStage: {
    display: 'none',
  },
  v46ReviewArtwork: {
    display: 'none',
  },
});
