import { StyleSheet } from 'react-native';
import { BONE, INK, LINE, MUTED, SIGNAL, SOFT } from '../../theme/detour-theme';

export const recapOverrides = StyleSheet.create({
  v45FinishTitleWrap: {
    alignSelf: 'center',
    alignItems: 'center',
    position: 'relative',
    marginBottom: 28,
  },
  v45FinishTitleUnderline: {
    position: 'absolute',
    right: 0,
    bottom: -8,
  },

  v51CompleteCard: {
    width: '100%',
    marginBottom: 24,
    borderWidth: 1,
    borderColor: '#D3CCBF',
    borderRadius: 18,
    backgroundColor: '#FBF8EF',
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOpacity: 0.07,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  v51CompleteTopInfo: {
    minHeight: 68,
    paddingHorizontal: 18,
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#D9D2C6',
  },
  v51CompleteTopBrand: {
    flex: 1.2,
    fontSize: 16,
    fontWeight: '900',
    letterSpacing: 1.4,
    color: INK,
  },
  v51CompleteTopMeta: {
    flex: 0.9,
    fontSize: 13,
    fontWeight: '900',
    textAlign: 'center',
    color: INK,
  },
  v51CompleteTopDate: {
    flex: 1.3,
    fontSize: 12,
    fontWeight: '800',
    textAlign: 'right',
    color: MUTED,
  },
  v51CompleteMedia: {
    width: '100%',
    height: 306,
    backgroundColor: '#E8E2D7',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  v51CompleteHeroPhoto: {
    width: '100%',
    height: '100%',
    backgroundColor: '#E8E2D7',
  },
  v51CompleteMediaFallback: {
    flex: 1,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  v51CompleteMediaFallbackText: {
    fontSize: 19,
    fontWeight: '900',
    color: MUTED,
  },
  v51CompleteThumbRow: {
    minHeight: 72,
    paddingHorizontal: 10,
    paddingVertical: 9,
    flexDirection: 'row',
    gap: 6,
    backgroundColor: '#F5F0E6',
    borderTopWidth: 1,
    borderTopColor: '#D9D2C6',
    borderBottomWidth: 1,
    borderBottomColor: '#D9D2C6',
  },
  v51CompleteThumbPress: {
    flex: 1,
    height: 54,
  },
  v51CompleteThumb: {
    width: '100%',
    height: '100%',
    borderRadius: 8,
    borderWidth: 2,
    borderColor: 'transparent',
    backgroundColor: SOFT,
  },
  v51CompleteThumbActive: {
    borderColor: SIGNAL,
  },
  v51CompleteCopy: {
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 20,
  },
  v51CompleteKicker: {
    fontSize: 14,
    fontWeight: '800',
    color: MUTED,
  },
  v51CompleteDestination: {
    marginTop: 5,
    fontSize: 28,
    lineHeight: 33,
    fontWeight: '900',
    letterSpacing: -0.8,
    color: INK,
  },
  v51CompleteMeta: {
    marginTop: 8,
    fontSize: 14,
    fontWeight: '800',
    color: MUTED,
  },
  v51CompleteBand: {
    minHeight: 58,
    paddingHorizontal: 20,
    alignItems: 'flex-start',
    justifyContent: 'center',
    backgroundColor: SIGNAL,
  },
  v51CompleteBandText: {
    fontSize: 21,
    fontWeight: '900',
    letterSpacing: 1.2,
    color: BONE,
  },

  v51RouteTrace: {
    width: '100%',
    height: '100%',
    position: 'relative',
    backgroundColor: '#EAE4D9',
    overflow: 'hidden',
  },
  v51RouteTraceLabel: {
    position: 'absolute',
    left: 14,
    bottom: 13,
    paddingHorizontal: 11,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: 'rgba(245,241,232,0.92)',
    borderWidth: 1,
    borderColor: '#CFC7BA',
  },
  v51RouteTraceLabelText: {
    fontSize: 12,
    fontWeight: '900',
    color: INK,
  },

  v45PosterPhoto: {
    width: '100%',
    height: '100%',
    backgroundColor: '#E8E2D7',
  },
  v51PosterPhotoStage: {
    width: '100%',
    height: 300,
    borderRadius: 18,
    overflow: 'hidden',
    backgroundColor: '#E8E2D7',
  },
  v51PosterRouteStage: {
    width: '100%',
    height: 300,
    borderRadius: 18,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#D2CBBD',
  },
  v51PosterHomeRoute: {
    width: '100%',
    height: 54,
    marginTop: 10,
  },

  v51ReviewHeroStage: {
    position: 'absolute',
    left: '10.2%',
    top: '17.1%',
    width: '79.2%',
    height: '38.4%',
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: '#E8E2D7',
  },
  v46ReviewHeroPhoto: {
    width: '100%',
    height: '100%',
    borderRadius: 12,
    backgroundColor: '#E8E2D7',
  },
});
