import { Platform, StyleSheet } from 'react-native';
import { ABSOLUTE_FILL, BONE, INK, LINE, MUTED, SIGNAL, SOFT } from '../../theme/detour-theme';

export const setupStyles = StyleSheet.create({
  onboardingScreen: {
    flex: 1,
    backgroundColor: BONE,
    paddingTop: 62,
    paddingHorizontal: 22,
    paddingBottom: 34,
  },
  onboardingTop: {
    minHeight: 42,
    flexDirection: 'row',
    alignItems: 'center',
  },
  onboardingBack: {
    width: 34,
    height: 38,
    justifyContent: 'center',
  },
  onboardingBackText: {
    fontSize: 26,
    color: INK,
  },
  onboardingBrand: {
    marginLeft: 26,
    fontSize: 14,
    fontWeight: '800',
    letterSpacing: 4,
    color: INK,
  },
  onboardingCounter: {
    marginLeft: 'auto',
    fontSize: 8,
    letterSpacing: 1.6,
    color: MUTED,
  },
  onboardingHero: {
    flex: 1,
    justifyContent: 'flex-start',
    paddingTop: 92,
    paddingBottom: 24,
  },
  onboardingEyebrow: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 2.2,
    color: SIGNAL,
    marginBottom: 18,
  },
  onboardingTitle: {
    maxWidth: 355,
    fontSize: 44,
    lineHeight: 50,
    fontWeight: '700',
    letterSpacing: -2.4,
    color: INK,
  },
  onboardingBody: {
    marginTop: 28,
    maxWidth: 350,
    fontSize: 18,
    lineHeight: 29,
    fontWeight: '500',
    letterSpacing: -0.3,
    color: '#3F3D38',
  },
  onboardingNote: {
    marginTop: 24,
    maxWidth: 338,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: LINE,
    fontSize: 13,
    lineHeight: 21,
    fontWeight: '600',
    color: INK,
  },
  onboardingPrimary: {
    minHeight: 72,
    paddingHorizontal: 20,
    backgroundColor: INK,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  onboardingPrimaryPressed: {
    opacity: 0.55,
  },
  onboardingPrimaryText: {
    fontSize: 18,
    fontWeight: '700',
    color: BONE,
  },
  onboardingPrimaryArrow: {
    fontSize: 24,
    color: SIGNAL,
  },
  settingsScreen: {
    flex: 1,
    backgroundColor: BONE,
    paddingTop: 62,
    paddingHorizontal: 22,
  },
  settingsTop: {
    minHeight: 42,
    flexDirection: 'row',
    alignItems: 'center',
  },
  settingsBack: {
    width: 34,
    height: 38,
    justifyContent: 'center',
  },
  settingsBackText: {
    fontSize: 26,
    color: INK,
  },
  settingsBrand: {
    marginLeft: 26,
    fontSize: 14,
    fontWeight: '800',
    letterSpacing: 4,
    color: INK,
  },
  settingsMeta: {
    marginLeft: 'auto',
    fontSize: 8,
    letterSpacing: 1.6,
    color: MUTED,
  },
  settingsScroll: {
    paddingTop: 28,
    paddingBottom: 64,
  },
  settingsHero: {
    marginBottom: 34,
  },
  settingsEyebrow: {
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 1.9,
    color: SIGNAL,
    marginBottom: 14,
  },
  settingsTitle: {
    maxWidth: 350,
    fontSize: 39,
    lineHeight: 45,
    fontWeight: '700',
    letterSpacing: -2.1,
    color: INK,
  },
  settingsSection: {
    marginTop: 32,
  },
  settingsSectionLabel: {
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 1.8,
    color: MUTED,
    marginBottom: 12,
  },
  settingsChoice: {
    minHeight: 88,
    paddingVertical: 16,
    borderTopWidth: 1,
    borderColor: LINE,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  settingsChoiceActive: {
    paddingLeft: 10,
  },
  settingsChoiceLabel: {
    fontSize: 18,
    fontWeight: '700',
    color: INK,
  },
  settingsChoiceNote: {
    marginTop: 7,
    maxWidth: 255,
    fontSize: 13,
    lineHeight: 20,
    color: '#5A5750',
  },
  settingsChoiceRight: {
    alignItems: 'flex-end',
    gap: 5,
  },
  settingsChoiceCode: {
    fontSize: 7,
    letterSpacing: 1.2,
    color: MUTED,
  },
  settingsChoiceMark: {
    fontSize: 14,
    color: SIGNAL,
  },
  settingsAction: {
    minHeight: 84,
    paddingVertical: 16,
    borderTopWidth: 1,
    borderColor: LINE,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  settingsActionTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: INK,
  },
  settingsActionNote: {
    marginTop: 7,
    maxWidth: 270,
    fontSize: 13,
    lineHeight: 20,
    color: '#5A5750',
  },
  settingsActionState: {
    fontSize: 9,
    fontWeight: '800',
    letterSpacing: 1.3,
    color: MUTED,
  },
  settingsActionStateOn: {
    color: SIGNAL,
  },
  settingsActionArrow: {
    fontSize: 18,
    color: SIGNAL,
  },
  settingsDataRow: {
    minHeight: 56,
    borderTopWidth: 1,
    borderColor: LINE,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  settingsDataLabel: {
    fontSize: 9,
    letterSpacing: 1.3,
    color: INK,
  },
  settingsDataValue: {
    fontSize: 9,
    letterSpacing: 1.1,
    color: MUTED,
  },
  settingsDanger: {
    minHeight: 50,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: LINE,
    justifyContent: 'center',
  },
  settingsDangerText: {
    fontSize: 11,
    color: SIGNAL,
  },
  settingsPrivacy: {
    marginTop: 42,
    paddingTop: 18,
    borderTopWidth: 1,
    borderColor: LINE,
  },
  settingsPrivacyTitle: {
    fontSize: 8,
    letterSpacing: 1.5,
    color: MUTED,
  },
  settingsPrivacyBody: {
    marginTop: 12,
    maxWidth: 340,
    fontSize: 13,
    lineHeight: 21,
    color: '#5A5750',
  },
  ticketMoodScreen: {
    flex: 1,
    backgroundColor: BONE,
    paddingTop: 58,
    paddingHorizontal: 22,
    paddingBottom: 24,
  },
  ticketFlowTimePill: {
    marginLeft: 'auto',
    minWidth: 66,
    height: 36,
    paddingHorizontal: 11,
    borderRadius: 18,
    backgroundColor: INK,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
  },
  ticketFlowTimeValue: {
    fontSize: 14,
    fontWeight: '800',
    color: BONE,
  },
  ticketFlowTimeUnit: {
    fontSize: 7,
    fontWeight: '800',
    letterSpacing: 1.2,
    color: '#A7A29A',
  },
  ticketMoodScroll: {
    flex: 1,
  },
  ticketMoodScrollContent: {
    paddingTop: 24,
    paddingBottom: 12,
  },
  ticketMoodHero: {
    marginTop: 0,
  },
  ticketMoodTitle: {
    marginTop: 11,
    fontSize: 38,
    lineHeight: 43,
    fontWeight: '700',
    letterSpacing: -2.1,
    color: INK,
  },
  ticketMoodGrid: {
    marginTop: 20,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  ticketMoodCard: {
    width: '48.5%',
    minHeight: 122,
    padding: 13,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: LINE,
    backgroundColor: '#F7F4EB',
    justifyContent: 'space-between',
  },
  ticketMoodCardWide: {
    width: '100%',
    minHeight: 96,
  },
  ticketMoodCardActive: {
    borderWidth: 2,
    borderColor: SIGNAL,
    backgroundColor: '#FFF0E9',
  },
  ticketMoodCardPressed: {
    opacity: 0.62,
    transform: [{ translateY: 2 }],
  },
  ticketMoodCardTop: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  ticketMoodSymbol: {
    fontSize: 26,
    lineHeight: 30,
    color: INK,
  },
  ticketMoodSymbolActive: {
    color: SIGNAL,
  },
  ticketMoodIndex: {
    fontSize: 8,
    fontWeight: '700',
    letterSpacing: 1,
    color: MUTED,
  },
  ticketMoodIndexActive: {
    color: SIGNAL,
  },
  ticketMoodLabel: {
    marginTop: 10,
    fontSize: 17,
    fontWeight: '700',
    letterSpacing: -0.6,
    color: INK,
  },
  ticketMoodHint: {
    marginTop: 5,
    fontSize: 10,
    lineHeight: 15,
    color: '#69645C',
  },
  ticketMoodCardFoot: {
    marginTop: 9,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  ticketMoodCode: {
    fontSize: 7,
    fontWeight: '800',
    letterSpacing: 1.4,
    color: MUTED,
  },
  ticketMoodCodeActive: {
    color: SIGNAL,
  },
  ticketMoodCheck: {
    fontSize: 8,
    fontWeight: '800',
    letterSpacing: 1,
    color: '#A49F96',
  },
  ticketMoodCheckActive: {
    color: SIGNAL,
  },
  ticketMoodFooter: {
    paddingTop: 10,
    backgroundColor: BONE,
  },
  ticketMoodPrimary: {
    minHeight: 60,
    paddingHorizontal: 18,
    borderRadius: 16,
    backgroundColor: INK,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  ticketMoodPrimaryDisabled: {
    backgroundColor: SOFT,
  },
  ticketMoodPrimaryPressed: {
    opacity: 0.76,
    transform: [{ translateY: 2 }],
  },
  ticketMoodPrimaryText: {
    fontSize: 16,
    fontWeight: '700',
    color: BONE,
  },
  ticketMoodPrimaryArrow: {
    fontSize: 22,
    color: SIGNAL,
  },
  ticketMoodPrimaryTextDisabled: {
    color: '#AAA59B',
  },
  ticketPrepareScreen: {
    flex: 1,
    backgroundColor: BONE,
    paddingTop: 58,
    paddingHorizontal: 22,
    paddingBottom: 26,
  },
  ticketPrepareMeta: {
    marginLeft: 'auto',
    fontSize: 8,
    fontWeight: '800',
    letterSpacing: 1.5,
    color: SIGNAL,
  },
  ticketPrepareHero: {
    marginTop: 44,
  },
  ticketPrepareTitle: {
    marginTop: 14,
    fontSize: 44,
    lineHeight: 49,
    fontWeight: '700',
    letterSpacing: -2.4,
    color: INK,
  },
  ticketPrepareSubtitle: {
    marginTop: 18,
    maxWidth: 330,
    fontSize: 14,
    lineHeight: 22,
    color: '#6B665E',
  },
  detourTicketShellReady: {
    marginTop: 24,
    minHeight: 386,
    paddingTop: 20,
    paddingHorizontal: 22,
    paddingBottom: 18,
    backgroundColor: '#FAF7EE',
    borderWidth: 1,
    borderColor: '#D3CEC1',
    position: 'relative',
    overflow: 'hidden',
  },
  ticketPrepareBottom: {
    marginTop: 'auto',
  },
  ticketPrepareBottomText: {
    marginTop: 12,
    fontSize: 11,
    lineHeight: 18,
    color: MUTED,
  },
  ticketReadyScreen: {
    flex: 1,
    backgroundColor: BONE,
    paddingTop: 58,
    paddingHorizontal: 22,
    paddingBottom: 24,
  },
  ticketReadyMeta: {
    marginLeft: 'auto',
    fontSize: 8,
    fontWeight: '800',
    letterSpacing: 1.5,
    color: SIGNAL,
  },
  ticketReadyHero: {
    marginTop: 32,
  },
  ticketReadyTitle: {
    marginTop: 13,
    fontSize: 39,
    lineHeight: 44,
    fontWeight: '700',
    letterSpacing: -2.1,
    color: INK,
  },
  ticketReadySubtitle: {
    marginTop: 14,
    fontSize: 13,
    lineHeight: 20,
    color: '#6B665E',
  },
  detourTicketReadyFacts: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  detourTicketReadyFact: {
    width: '31%',
  },
  detourTicketReadyValue: {
    marginTop: 7,
    fontSize: 14,
    fontWeight: '800',
    color: INK,
  },
  detourTicketReadyFoot: {
    marginTop: 1,
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
  },
  detourTicketReadyStamp: {
    paddingHorizontal: 9,
    paddingVertical: 6,
    borderWidth: 2,
    borderColor: SIGNAL,
    fontSize: 7,
    fontWeight: '900',
    letterSpacing: 1.2,
    color: SIGNAL,
    transform: [{ rotate: '-4deg' }],
  },
  ticketReadyPrimary: {
    minHeight: 64,
    marginTop: 18,
    paddingHorizontal: 19,
    borderRadius: 15,
    backgroundColor: INK,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  ticketReadyPrimaryPressed: {
    opacity: 0.78,
    transform: [{ translateY: 2 }],
  },
  ticketReadyPrimaryText: {
    fontSize: 16,
    fontWeight: '700',
    color: BONE,
  },
  ticketReadyPrimaryArrow: {
    fontSize: 23,
    color: SIGNAL,
  },
  ticketReadyTestLabel: {
    marginTop: 10,
    textAlign: 'center',
    fontSize: 7,
    fontWeight: '800',
    letterSpacing: 1.5,
    color: SIGNAL,
  },
  homeUtilityCluster: {
    marginLeft: 'auto',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  homeSettingsButton: {
    width: 46,
    height: 46,
    borderWidth: 1,
    borderColor: INK,
    alignItems: 'center',
    justifyContent: 'center',
  },
  homeSettingsGlyph: {
    marginTop: -6,
    fontSize: 22,
    fontWeight: '800',
    letterSpacing: 1,
    color: INK,
  },
  homeUtilityPressed: {
    opacity: 0.42,
    transform: [{ scale: 0.97 }],
  },
  homeHero: {
    marginTop: 34,
  },
  homeIntroBlock: {
    maxWidth: 352,
  },
  homeTitle: {
    fontSize: 52,
    lineHeight: 58,
    fontWeight: '700',
    letterSpacing: -3,
    color: INK,
  },
  homeBody: {
    marginTop: 20,
    maxWidth: 338,
    fontSize: 18,
    lineHeight: 28,
    fontWeight: '500',
    color: '#4B4842',
  },
  homeCtaBlock: {
    marginTop: 44,
  },
  homeSectionRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  homeSectionTitle: {
    fontSize: 21,
    fontWeight: '700',
    letterSpacing: -0.8,
    color: INK,
  },
  homeSectionNote: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1.2,
    color: SIGNAL,
  },
  timeCardGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  timeCard: {
    width: '48.3%',
    minHeight: 172,
    paddingTop: 14,
    paddingHorizontal: 14,
    paddingBottom: 16,
    borderWidth: 1,
    borderColor: INK,
    backgroundColor: '#F6F3EA',
  },
  timeCardPressed: {
    opacity: 0.72,
    transform: [{ translateY: 2 }],
  },
  timeCardCode: {
    fontSize: 9,
    fontWeight: '700',
    letterSpacing: 1.4,
    color: MUTED,
  },
  timeCardTopRow: {
    marginTop: 18,
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  timeCardNumber: {
    fontSize: 42,
    lineHeight: 42,
    fontWeight: '700',
    letterSpacing: -2.2,
    color: INK,
  },
  timeCardArrow: {
    marginTop: 6,
    fontSize: 20,
    lineHeight: 20,
    color: SIGNAL,
  },
  timeCardUnit: {
    marginTop: 6,
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1.6,
    color: MUTED,
  },
  timeCardBlurb: {
    marginTop: 18,
    fontSize: 13,
    lineHeight: 20,
    fontWeight: '500',
    color: '#4B4842',
  },
  homeFootRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 18,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: LINE,
  },
  devHomeLabel: {
    fontSize: 9,
    fontWeight: '700',
    letterSpacing: 1.4,
    color: SIGNAL,
  },
  moodHeader: { marginTop: 38, marginBottom: 22 },
  moodList: { borderTopWidth: 1, borderTopColor: LINE },
  moodRow: {
    minHeight: 72,
    borderBottomWidth: 1,
    borderBottomColor: LINE,
    flexDirection: 'row',
    alignItems: 'center',
  },
  moodRowPressed: { paddingLeft: 8, opacity: 0.45 },
  moodIndex: { width: 38, fontSize: 9, letterSpacing: 1.3, color: MUTED },
  moodTextWrap: { flex: 1 },
  moodLabel: {
    fontSize: 22,
    fontWeight: '600',
    letterSpacing: -0.9,
    color: INK,
  },
  moodCode: {
    marginTop: 6,
    fontSize: 10,
    fontWeight: '600',
    letterSpacing: 1.5,
    color: MUTED,
  },
  moodArrow: { fontSize: 20, color: INK },
  colorHero: { marginTop: 38 },
  colorGrid: { borderTopWidth: 1, borderTopColor: LINE },
  colorButton: {
    height: 64,
    borderBottomWidth: 1,
    borderBottomColor: LINE,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  colorButtonPressed: { opacity: 0.45, paddingLeft: 6 },
  colorSwatch: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(17,17,15,0.16)',
  },
  colorLabel: { fontSize: 16, fontWeight: '700', color: INK },
  colorCode: { marginTop: 2, fontSize: 7, letterSpacing: 1.4, color: MUTED },
  colorArrow: { marginLeft: 'auto', fontSize: 18, color: INK },
  prepareScreen: {
    flex: 1,
    backgroundColor: BONE,
    paddingTop: 62,
    paddingHorizontal: 22,
    paddingBottom: 34,
    justifyContent: 'space-between',
  },
  prepareHero: { marginTop: 44 },
  prepareTitle: {
    fontSize: 47,
    lineHeight: 52,
    fontWeight: '600',
    letterSpacing: -2.5,
    color: INK,
  },
  readyHero: { marginTop: 30 },
  readyNumber: {
    fontSize: 112,
    lineHeight: 112,
    fontWeight: '700',
    letterSpacing: -8,
    color: INK,
  },
  readyMinutes: {
    marginTop: 4,
    fontSize: 9,
    letterSpacing: 2.5,
    color: MUTED,
  },
  readyTitle: {
    marginTop: 34,
    fontSize: 36,
    lineHeight: 42,
    fontWeight: '600',
    letterSpacing: -1.8,
    color: INK,
  },
  reissueHero: {
    marginTop: 34,
  },
  ticketMoodScreenDark: {
    backgroundColor: '#050505',
  },
  ticketFlowTimePillDark: {
    backgroundColor: '#11110F',
    borderWidth: 1,
    borderColor: '#3A362F',
  },
  ticketFlowTimeValueDark: {
    color: BONE,
  },
  ticketFlowTimeUnitDark: {
    color: '#B2ADA4',
  },
  ticketMoodTitleDark: {
    color: BONE,
  },
  ticketMoodCardDark: {
    borderColor: '#3A362F',
    backgroundColor: '#131210',
  },
  ticketMoodCardActiveDark: {
    borderColor: SIGNAL,
    backgroundColor: 'rgba(255,90,54,0.12)',
  },
  ticketMoodSymbolDark: {
    color: BONE,
  },
  ticketMoodIndexDark: {
    color: '#AAA59C',
  },
  ticketMoodLabelDark: {
    color: BONE,
  },
  ticketMoodHintDark: {
    color: '#A7A197',
  },
  ticketMoodCodeDark: {
    color: '#9A958C',
  },
  ticketMoodCheckDark: {
    color: '#8D887F',
  },
  ticketMoodFooterDark: {
    backgroundColor: '#050505',
  },
  ticketMoodPrimaryDark: {
    backgroundColor: SIGNAL,
  },
  ticketMoodPrimaryDisabledDark: {
    backgroundColor: '#24211D',
  },
  ticketMoodPrimaryTextDark: {
    color: '#130F0B',
  },
  ticketMoodPrimaryArrowDark: {
    color: '#130F0B',
  },
  ticketMoodPrimaryTextDisabledDark: {
    color: '#8D877D',
  }
});
