import { Platform, StyleSheet } from 'react-native';
import { ABSOLUTE_FILL, BONE, INK, LINE, MUTED, SIGNAL, SOFT } from '../../theme/detour-theme';

export const ticketRecapStyles = StyleSheet.create({
  v48PrintingTopBar: {
    height: 48,
    flexDirection: 'row',
    alignItems: 'center',
  },
  v48PrintingBack: {
    width: 42,
    height: 48,
    marginLeft: -8,
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  v48PrintingBackText: {
    fontSize: 38,
    lineHeight: 42,
    color: INK,
  },
  v48PrintingTitleWrap: {
    marginTop: 48,
  },
  v48PrinterAssembly: {
    width: '100%',
    height: 456,
    marginTop: 12,
    position: 'relative',
    alignItems: 'center',
  },
  v50PrinterBody: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 82,
    borderRadius: 18,
    backgroundColor: '#AAA7A0',
    borderWidth: 1,
    borderColor: '#D5D2CB',
    zIndex: 1,
    shadowColor: '#000',
    shadowOpacity: 0.18,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 7,
  },
  v50PrinterHighlight: {
    position: 'absolute',
    left: 18,
    right: 18,
    top: 3,
    height: 1,
    backgroundColor: 'rgba(255,255,255,0.62)',
  },
  v50PrinterSlotShell: {
    position: 'absolute',
    left: 18,
    right: 18,
    top: 31,
    height: 29,
    borderRadius: 10,
    backgroundColor: '#5E5B55',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.34,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 3 },
    elevation: 4,
  },
  v50PrinterSlot: {
    width: '94%',
    height: 13,
    borderRadius: 7,
    backgroundColor: '#11110F',
  },
  v48PaperViewport: {
    position: 'absolute',
    top: 47,
    width: 310,
    height: 409,
    overflow: 'hidden',
    alignItems: 'center',
    zIndex: 2,
  },
  v48PaperTrack: {
    position: 'absolute',
    top: 0,
    width: 310,
    alignItems: 'center',
  },
  v50PrinterFrontLip: {
    position: 'absolute',
    left: 22,
    right: 22,
    top: 51,
    height: 9,
    borderBottomLeftRadius: 6,
    borderBottomRightRadius: 6,
    backgroundColor: '#77746E',
    borderTopWidth: 1,
    borderTopColor: '#96938C',
    zIndex: 4,
    shadowColor: '#000',
    shadowOpacity: 0.24,
    shadowRadius: 3,
    shadowOffset: { width: 0, height: 2 },
    elevation: 5,
  },
  v50PrinterFrontLipHighlight: {
    position: 'absolute',
    left: 8,
    right: 8,
    top: 1,
    height: 1,
    backgroundColor: 'rgba(255,255,255,0.24)',
  },
  v48DepartButton: {
    position: 'absolute',
    left: 30,
    right: 30,
    bottom: 24,
    minHeight: 68,
    borderRadius: 34,
    backgroundColor: INK,
    paddingHorizontal: 24,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    zIndex: 10,
    shadowColor: '#000',
    shadowOpacity: 0.18,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 8,
  },
  v48DepartButtonPressed: {
    transform: [{ translateY: 1 }],
    opacity: 0.9,
  },
  v48DepartButtonText: {
    fontSize: 24,
    fontWeight: '900',
    color: BONE,
  },
  v48DepartButtonArrow: {
    fontSize: 32,
    color: SIGNAL,
  },
  v48RetryOverlay: {
    flex: 1,
    backgroundColor: 'rgba(17,17,15,0.42)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  v48RetryCard: {
    width: '100%',
    maxWidth: 370,
    borderRadius: 24,
    backgroundColor: '#FFF9F1',
    borderWidth: 1,
    borderColor: SIGNAL,
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 18,
    shadowColor: '#000',
    shadowOpacity: 0.22,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 12 },
    elevation: 12,
  },
  v48RetryEyebrow: {
    fontSize: 14,
    fontWeight: '900',
    color: SIGNAL,
  },
  v48RetryTitle: {
    marginTop: 8,
    fontSize: 30,
    lineHeight: 36,
    fontWeight: '900',
    letterSpacing: -1.2,
    color: INK,
  },
  v48RetryBody: {
    marginTop: 12,
    fontSize: 17,
    lineHeight: 25,
    fontWeight: '700',
    color: INK,
  },
  v48RetryPrimary: {
    marginTop: 24,
    minHeight: 64,
    borderRadius: 32,
    backgroundColor: INK,
    paddingHorizontal: 22,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  v48RetryPrimaryText: {
    fontSize: 20,
    fontWeight: '900',
    color: BONE,
  },
  v48RetryPrimaryArrow: {
    fontSize: 30,
    color: SIGNAL,
  },
  v48RetrySecondary: {
    minHeight: 48,
    marginTop: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  v48RetrySecondaryText: {
    fontSize: 16,
    fontWeight: '800',
    color: MUTED,
  },
  v44MoodGlyph: {
    width: 86,
    height: 76,
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
  },
  v44MoodGlyphActive: {
    transform: [{ translateY: -1 }, { scale: 1.035 }],
  },
  v44WanderStem: {
    position: 'absolute',
    left: 40,
    top: 35,
    width: 6,
    height: 31,
    borderRadius: 3,
    backgroundColor: INK,
  },
  v44WanderBranchLeft: {
    position: 'absolute',
    left: 23,
    top: 29,
    width: 25,
    height: 6,
    borderRadius: 3,
    backgroundColor: INK,
    transform: [{ rotate: '-38deg' }],
  },
  v44WanderBranchRight: {
    position: 'absolute',
    right: 20,
    top: 25,
    width: 30,
    height: 6,
    borderRadius: 3,
    backgroundColor: INK,
    transform: [{ rotate: '38deg' }],
  },
  v44WanderOrigin: {
    position: 'absolute',
    left: 36,
    bottom: 4,
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: INK,
  },
  v44WanderChoice: {
    position: 'absolute',
    right: 11,
    top: 11,
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: SIGNAL,
  },
  v44FoodPlate: {
    width: 46,
    height: 46,
    borderRadius: 23,
    borderWidth: 5,
    borderColor: INK,
  },
  v44FoodForkHandle: {
    position: 'absolute',
    left: 7,
    top: 23,
    width: 5,
    height: 46,
    borderRadius: 3,
    backgroundColor: INK,
  },
  v44FoodForkTineA: { position: 'absolute', left: 3, top: 9, width: 4, height: 20, borderRadius: 2, backgroundColor: INK },
  v44FoodForkTineB: { position: 'absolute', left: 9, top: 8, width: 4, height: 21, borderRadius: 2, backgroundColor: INK },
  v44FoodForkTineC: { position: 'absolute', left: 15, top: 9, width: 4, height: 20, borderRadius: 2, backgroundColor: INK },
  v44FoodKnife: {
    position: 'absolute',
    right: 7,
    top: 9,
    width: 7,
    height: 59,
    borderRadius: 4,
    backgroundColor: SIGNAL,
    transform: [{ rotate: '4deg' }],
  },
  v44QuietBar: { position: 'absolute', bottom: 15, width: 7, borderRadius: 4, backgroundColor: INK },
  v44QuietBarA: { left: 18, height: 20 },
  v44QuietBarB: { left: 30, height: 34 },
  v44QuietBarC: { left: 42, height: 48 },
  v44QuietBarD: { right: 30, height: 34 },
  v44QuietBarE: { right: 18, height: 20 },
  v44QuietSlash: {
    position: 'absolute',
    width: 70,
    height: 7,
    borderRadius: 4,
    backgroundColor: SIGNAL,
    transform: [{ rotate: '-37deg' }],
  },
  v44WeirdTile: {
    position: 'absolute',
    width: 24,
    height: 24,
    borderWidth: 5,
    borderColor: INK,
  },
  v44WeirdTileA: { left: 17, top: 12 },
  v44WeirdTileB: { left: 17, top: 40 },
  v44WeirdTileC: { left: 45, top: 40 },
  v44WeirdOddTile: {
    position: 'absolute',
    right: 4,
    top: 3,
    width: 25,
    height: 25,
    backgroundColor: SIGNAL,
    transform: [{ rotate: '12deg' }],
  },
  v44ColorSwatch: {
    position: 'absolute',
    width: 30,
    height: 48,
    borderRadius: 3,
  },
  v44ColorSwatchBack: {
    left: 17,
    top: 16,
    backgroundColor: INK,
    transform: [{ rotate: '-13deg' }],
  },
  v44ColorSwatchSignal: {
    right: 16,
    top: 17,
    backgroundColor: SIGNAL,
    transform: [{ rotate: '13deg' }],
  },
  v44ColorSwatchFront: {
    left: 29,
    top: 9,
    backgroundColor: BONE,
    borderWidth: 5,
    borderColor: INK,
  },
  v44FateDie: {
    width: 52,
    height: 52,
    borderRadius: 8,
    borderWidth: 5,
    borderColor: INK,
    transform: [{ rotate: '8deg' }],
  },
  v44FatePip: { position: 'absolute', width: 9, height: 9, borderRadius: 5, backgroundColor: INK },
  v44FatePipA: { left: 8, top: 8 },
  v44FatePipB: { left: 17, top: 17, backgroundColor: SIGNAL },
  v44FatePipC: { right: 8, bottom: 8 },
  v44FateSignal: {
    position: 'absolute',
    right: 8,
    top: 7,
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: SIGNAL,
  },
  v44TicketPaper: {
    width: 296,
    height: 436,
    paddingHorizontal: 27,
    paddingTop: 26,
    paddingBottom: 22,
    backgroundColor: '#FBF5E9',
    borderWidth: 1,
    borderColor: '#D3CABD',
    shadowColor: '#000',
    shadowOpacity: 0.15,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
    position: 'relative',
  },
  v44TicketEdgeCut: {
    position: 'absolute',
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: BONE,
    zIndex: 3,
  },
  v44TicketEdgeLeft: { left: -7 },
  v44TicketEdgeRight: { right: -7 },
  v44TicketHeader: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
  },
  v44TicketBrand: {
    fontSize: 39,
    lineHeight: 42,
    fontWeight: '900',
    letterSpacing: -2.2,
    color: INK,
  },
  v44TicketSerial: {
    paddingBottom: 4,
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 1.5,
    color: MUTED,
  },
  v44TicketRule: {
    height: 1,
    marginTop: 18,
    backgroundColor: '#AAA296',
  },
  v44TicketTimeBlock: {
    paddingTop: 18,
    paddingBottom: 15,
  },
  v44TicketLabel: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '900',
    color: '#5F5A52',
  },
  v44TicketTimeRow: {
    marginTop: 1,
    flexDirection: 'row',
    alignItems: 'flex-end',
  },
  v44TicketTime: {
    fontSize: 68,
    lineHeight: 71,
    fontWeight: '900',
    letterSpacing: -4,
    color: INK,
  },
  v44TicketTimeUnit: {
    marginLeft: 7,
    marginBottom: 8,
    fontSize: 24,
    fontWeight: '900',
    color: INK,
  },
  v44TicketMoodBlock: {
    minHeight: 104,
    paddingTop: 15,
    borderTopWidth: 1,
    borderTopColor: '#C0B7AA',
    flexDirection: 'row',
    alignItems: 'center',
    position: 'relative',
  },
  v44TicketMoodCopy: { flex: 1 },
  v44TicketMood: {
    marginTop: 3,
    fontSize: 44,
    lineHeight: 50,
    fontWeight: '900',
    letterSpacing: -2.1,
    color: INK,
  },
  v44TicketStamp: {
    position: 'absolute',
    right: -2,
    bottom: 13,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderWidth: 3,
    borderColor: SIGNAL,
    backgroundColor: 'rgba(251,245,233,0.82)',
  },
  v44TicketStampText: {
    fontSize: 18,
    fontWeight: '900',
    letterSpacing: 0.6,
    color: SIGNAL,
  },
  v44TicketDash: {
    marginTop: 7,
    borderTopWidth: 1,
    borderStyle: 'dashed',
    borderColor: '#AFA79B',
  },
  v44TicketFooter: {
    flex: 1,
    paddingTop: 22,
    justifyContent: 'flex-end',
  },
  v44TicketBarcode: {
    height: 58,
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: 3,
  },
  v44TicketBar: {
    height: '100%',
    backgroundColor: INK,
  },
  // V45 refined paper / ticket visual system
  v45Skyline: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 78,
    opacity: 0.3,
  },
  v45SkylineBuilding: {
    position: 'absolute',
    bottom: 0,
    backgroundColor: '#B7B3A9',
  },
  v45SkylineBridgeDeck: {
    position: 'absolute',
    right: 8,
    bottom: 22,
    width: 122,
    height: 3,
    backgroundColor: '#8F8B82',
    transform: [{ rotate: '-2deg' }],
  },
  v45SkylineBridgeArch: {
    position: 'absolute',
    right: 24,
    bottom: 7,
    width: 92,
    height: 42,
    borderTopWidth: 3,
    borderColor: '#8F8B82',
    borderRadius: 50,
  },
  v45MoodScreen: {
    flex: 1,
    backgroundColor: '#F5F1E8',
    paddingTop: 58,
    paddingHorizontal: 26,
    paddingBottom: 24,
  },
  v45MoodHeader: {
    height: 68,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  v45BackButton: {
    width: 42,
    height: 42,
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  v45BackText: {
    fontSize: 48,
    lineHeight: 48,
    fontWeight: '300',
    color: INK,
    marginTop: -6,
  },
  v45MoodBrand: {
    position: 'absolute',
    left: 56,
    fontSize: 36,
    lineHeight: 40,
    fontWeight: '900',
    letterSpacing: -1.8,
    color: INK,
  },
  v45TimePill: {
    minWidth: 104,
    height: 54,
    paddingHorizontal: 17,
    borderRadius: 28,
    backgroundColor: INK,
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  v45TimePillIcon: {
    fontSize: 21,
    fontWeight: '800',
    color: SIGNAL,
  },
  v45TimePillText: {
    fontSize: 17,
    fontWeight: '800',
    color: BONE,
  },
  v45MoodTitleWrap: {
    marginTop: 35,
    marginBottom: 26,
    alignItems: 'center',
  },
  v45MoodTitle: {
    fontSize: 38,
    lineHeight: 45,
    fontWeight: '900',
    letterSpacing: -1.6,
    color: INK,
    textAlign: 'center',
  },
  v45MoodUnderline: {
    marginTop: 2,
  },
  v45MoodGrid: {
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignContent: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
    zIndex: 2,
  },
  v45MoodCard: {
    width: '48.2%',
    height: 140,
    borderWidth: 1,
    borderColor: '#D4CEC1',
    borderRadius: 16,
    backgroundColor: 'rgba(250,247,239,0.94)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  v45MoodCardActive: {
    borderWidth: 3,
    borderColor: SIGNAL,
    backgroundColor: '#FFF4EB',
  },
  v45MoodCardPressed: {
    opacity: 0.7,
    transform: [{ scale: 0.985 }],
  },
  v45MoodLabel: {
    marginTop: 4,
    fontSize: 20,
    lineHeight: 24,
    fontWeight: '900',
    letterSpacing: -0.4,
    color: INK,
  },
  v45MoodIconStage: {
    width: 112,
    height: 78,
    position: 'relative',
  },
  v45AccentDash: {
    position: 'absolute',
    width: 20,
    height: 4,
    borderRadius: 2,
    backgroundColor: SIGNAL,
  },
  v45WalkerBackpack: {
    position: 'absolute', left: 34, top: 25, width: 22, height: 31,
    borderRadius: 7, backgroundColor: SIGNAL, transform: [{ rotate: '8deg' }],
  },
  v45WalkerHead: {
    position: 'absolute', left: 51, top: 3, width: 19, height: 19,
    borderRadius: 10, backgroundColor: INK,
  },
  v45WalkerBody: {
    position: 'absolute', left: 55, top: 21, width: 11, height: 37,
    borderRadius: 6, backgroundColor: INK, transform: [{ rotate: '-10deg' }],
  },
  v45WalkerLimb: {
    position: 'absolute', width: 9, height: 35,
    borderRadius: 5, backgroundColor: INK,
  },
  v45WalkerArm: { left: 70, top: 28, height: 30, transform: [{ rotate: '-55deg' }] },
  v45WalkerLegA: { left: 49, top: 48, height: 33, transform: [{ rotate: '32deg' }] },
  v45WalkerLegB: { left: 68, top: 46, height: 35, transform: [{ rotate: '-24deg' }] },
  v45DrinkCup: {
    position: 'absolute', left: 26, top: 24, width: 27, height: 42,
    borderRadius: 4, backgroundColor: INK,
  },
  v45DrinkLid: {
    position: 'absolute', left: 23, top: 20, width: 33, height: 6,
    borderRadius: 3, backgroundColor: INK,
  },
  v45DrinkStraw: {
    position: 'absolute', left: 43, top: 2, width: 5, height: 24,
    borderRadius: 3, backgroundColor: INK, transform: [{ rotate: '10deg' }],
  },
  v45BurgerBun: {
    position: 'absolute', right: 18, top: 35, width: 43, height: 18,
    borderTopLeftRadius: 24, borderTopRightRadius: 24, backgroundColor: INK,
  },
  v45BurgerPatty: {
    position: 'absolute', right: 16, top: 54, width: 47, height: 8,
    borderRadius: 4, backgroundColor: SIGNAL,
  },
  v45BurgerBottom: {
    position: 'absolute', right: 18, top: 63, width: 43, height: 10,
    borderBottomLeftRadius: 8, borderBottomRightRadius: 8, backgroundColor: INK,
  },
  v45TreeCrownA: {
    position: 'absolute', left: 24, top: 15, width: 39, height: 47,
    borderRadius: 24, backgroundColor: INK,
  },
  v45TreeCrownB: {
    position: 'absolute', left: 39, top: 4, width: 34, height: 45,
    borderRadius: 22, backgroundColor: INK,
  },
  v45TreeTrunk: {
    position: 'absolute', left: 50, top: 46, width: 7, height: 29,
    backgroundColor: INK,
  },
  v45BenchSeat: {
    position: 'absolute', right: 15, top: 50, width: 49, height: 8,
    borderRadius: 2, backgroundColor: SIGNAL,
  },
  v45BenchBack: {
    position: 'absolute', right: 15, top: 39, width: 49, height: 7,
    borderRadius: 2, backgroundColor: SIGNAL,
  },
  v45BenchLeg: {
    position: 'absolute', top: 57, width: 5, height: 17, backgroundColor: INK,
  },
  v45CatBody: {
    position: 'absolute', left: 39, top: 35, width: 39, height: 38,
    borderRadius: 20, backgroundColor: INK,
  },
  v45CatHead: {
    position: 'absolute', left: 42, top: 18, width: 31, height: 31,
    borderRadius: 16, backgroundColor: INK,
  },
  v45CatEar: {
    position: 'absolute', top: 10, width: 0, height: 0,
    borderLeftWidth: 8, borderRightWidth: 8, borderBottomWidth: 16,
    borderLeftColor: 'transparent', borderRightColor: 'transparent', borderBottomColor: INK,
  },
  v45CatEarLeft: { left: 42, transform: [{ rotate: '-18deg' }] },
  v45CatEarRight: { left: 60, transform: [{ rotate: '18deg' }] },
  v45CatTail: {
    position: 'absolute', left: 70, top: 42, width: 33, height: 33,
    borderWidth: 8, borderLeftColor: 'transparent', borderTopColor: 'transparent',
    borderRightColor: INK, borderBottomColor: INK, borderRadius: 20,
    transform: [{ rotate: '-24deg' }],
  },
  v45QuestionMark: {
    position: 'absolute', right: 9, top: -1, fontSize: 37, fontWeight: '900', color: SIGNAL,
  },
  v45CameraBody: {
    position: 'absolute', left: 26, top: 24, width: 68, height: 45,
    borderRadius: 9, backgroundColor: INK,
  },
  v45CameraTop: {
    position: 'absolute', left: 43, top: 16, width: 27, height: 14,
    borderTopLeftRadius: 5, borderTopRightRadius: 5, backgroundColor: INK,
  },
  v45CameraLensOuter: {
    position: 'absolute', left: 48, top: 31, width: 30, height: 30,
    borderRadius: 15, backgroundColor: BONE, alignItems: 'center', justifyContent: 'center',
  },
  v45CameraLensInner: {
    width: 20, height: 20, borderRadius: 10, backgroundColor: INK,
  },
  v45Die: {
    position: 'absolute', left: 34, top: 13, width: 55, height: 55,
    borderRadius: 10, backgroundColor: INK, transform: [{ rotate: '14deg' }],
  },
  v45DiePip: {
    position: 'absolute', width: 7, height: 7, borderRadius: 4, backgroundColor: BONE,
  },
  v45MoodCta: {
    zIndex: 3,
    height: 68,
    marginTop: 12,
    marginBottom: 58,
    backgroundColor: SIGNAL,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 3,
    position: 'relative',
  },
  v45MoodCtaDisabled: { backgroundColor: '#E6B19E' },
  v45MoodCtaPressed: { opacity: 0.78, transform: [{ translateY: 2 }] },
  v45MoodCtaText: { fontSize: 28, fontWeight: '900', color: INK },
  v45MoodCtaArrow: { position: 'absolute', right: 22, fontSize: 34, color: INK },
  v45MoodCtaDivider: { position: 'absolute', right: 70, top: 10, bottom: 10, width: 1, backgroundColor: 'rgba(17,17,15,0.34)' },
  v45TicketNotchLeft: { position: 'absolute', left: -10, top: 25, width: 20, height: 20, borderRadius: 10, backgroundColor: '#F5F1E8' },
  v45TicketNotchRight: { position: 'absolute', right: -10, top: 25, width: 20, height: 20, borderRadius: 10, backgroundColor: '#F5F1E8' },
  v45PrintingScreen: {
    flex: 1, backgroundColor: '#F5F1E8', paddingTop: 70, paddingHorizontal: 30, overflow: 'hidden',
  },
  v45PrintingBrand: {
    fontSize: 34, lineHeight: 38, fontWeight: '900', letterSpacing: -1.4, color: INK,
  },
  v45PrintingTitleWrap: {
    marginTop: 68,
    alignItems: 'center',
    zIndex: 5,
  },
  v45PrintingTitle: {
    fontSize: 38, lineHeight: 47, fontWeight: '900', letterSpacing: -1.7, color: INK, textAlign: 'center',
  },
  v45PrintingUnderline: {
    marginTop: 2,
  },
  v45PrinterStage: { marginTop: 38, alignItems: 'center', height: 500, zIndex: 2 },
  v45PrinterMachine: { width:'100%',height:96,borderRadius:20,backgroundColor:'#AAA69E',borderWidth:1,borderColor:'#D3D0C9',paddingHorizontal:20,justifyContent:'center',zIndex:6,shadowColor:'#000',shadowOffset:{width:0,height:10},shadowOpacity:.22,shadowRadius:14,elevation:9 },
  v45PrinterPulse: {
    ...ABSOLUTE_FILL, borderRadius: 18, backgroundColor: '#C8B7A6',
  },
  v45PrinterSlot: { height:25,borderRadius:8,backgroundColor:'#11110F',borderWidth:6,borderColor:'#5D5A54',shadowColor:'#000',shadowOffset:{width:0,height:3},shadowOpacity:.4,shadowRadius:4,elevation:5 },
  v45PaperMask: {
    position: 'absolute', top: 64, width: '92%', height: 438, overflow: 'hidden', alignItems: 'center', zIndex: 3,
  },
  v45PaperMotion: { width: '100%', alignItems: 'center' },
  v45TicketPaper: {
    width: '100%', height: 432, backgroundColor: '#FBF8EF', paddingHorizontal: 26, paddingTop: 45, paddingBottom: 22,
    borderRadius: 2, position: 'relative', overflow: 'hidden',
    shadowColor: '#000', shadowOffset: { width: 0, height: 12 }, shadowOpacity: 0.18, shadowRadius: 16, elevation: 6,
  },
  v45TicketOrangeBand: { position: 'absolute', left: 0, right: 0, top: 0, height: 28, backgroundColor: SIGNAL },
  v45TicketBrand: { fontSize: 30, fontWeight: '900', letterSpacing: -1.3, color: INK },
  v45TicketRule: { height: 1, backgroundColor: '#C9C2B5', marginVertical: 16, borderStyle: 'dashed' },
  v45TicketInfoRow: { minHeight: 116, flexDirection: 'row', alignItems: 'stretch' },
  v45TicketInfoBlock: { flex: 1, justifyContent: 'center' },
  v45TicketVerticalRule: { width: 1, marginHorizontal: 16, backgroundColor: '#D1CABC' },
  v45TicketLabel: { fontSize: 16, fontWeight: '800', color: INK },
  v45TicketMinutesRow: { flexDirection: 'row', alignItems: 'flex-end', marginTop: 5 },
  v45TicketMinutes: { fontSize: 68, lineHeight: 72, fontWeight: '900', color: SIGNAL, letterSpacing: -3 },
  v45TicketMinutesUnit: { fontSize: 18, lineHeight: 28, fontWeight: '900', color: INK, marginLeft: 6, marginBottom: 7 },
  v45TicketMood: { marginTop: 18, fontSize: 25, lineHeight: 30, fontWeight: '900', color: INK },
  v45TicketMoodUnderline: { width: 93, height: 5, borderRadius: 3, backgroundColor: SIGNAL, marginTop: 5, transform: [{ rotate: '-4deg' }] },
  v45TicketDestinationRow: { minHeight: 78, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  v45TicketUnknown: { marginTop: 6, fontSize: 27, fontWeight: '900', color: INK },
  v45TicketRouteMini: { width: 130, height: 60, position: 'relative' },
  v45TicketRouteDot: { position: 'absolute', left: 4, top: 28, width: 12, height: 12, borderRadius: 6, backgroundColor: SIGNAL },
  v45TicketRouteDashA: { position: 'absolute', left: 18, top: 31, width: 48, height: 3, backgroundColor: SIGNAL, transform: [{ rotate: '21deg' }] },
  v45TicketRouteDashB: { position: 'absolute', left: 61, top: 30, width: 44, height: 3, backgroundColor: SIGNAL, transform: [{ rotate: '-18deg' }] },
  v45TicketRouteFlagPole: { position: 'absolute', right: 11, top: 14, width: 4, height: 34, backgroundColor: INK },
  v45TicketRouteFlag: { position: 'absolute', right: -2, top: 12, width: 22, height: 14, backgroundColor: SIGNAL, transform: [{ rotate: '5deg' }] },
  v45BarcodeRow: { height: 44, flexDirection: 'row', alignItems: 'stretch', justifyContent: 'center', gap: 3 },
  v45BarcodeBar: { height: 44, backgroundColor: '#5F5B55' },
  v45TicketStamp: { position: 'absolute', right: 25, top: 50, width: 90, height: 44, borderWidth: 3, borderColor: SIGNAL, borderRadius: 7, alignItems: 'center', justifyContent: 'center', transform: [{ rotate: '-7deg' }] },
  v45TicketStampText: { fontSize: 16, fontWeight: '900', color: SIGNAL },
  v45TicketErrorPanel: {
    position: 'absolute',
    left: 30,
    right: 30,
    bottom: 24,
    zIndex: 10,
    padding: 16,
    borderWidth: 1,
    borderColor: SIGNAL,
    borderRadius: 14,
    backgroundColor: '#FFF7F1',
  },
  v45TicketErrorText: { fontSize: 16, lineHeight: 24, fontWeight: '700', color: INK },
  v45TicketRetry: {
    marginTop: 12,
    minHeight: 54,
    borderRadius: 27,
    backgroundColor: INK,
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  v45TicketRetryText: { fontSize: 18, fontWeight: '800', color: BONE },
  v45TicketRetryArrow: { fontSize: 25, color: SIGNAL },
  v45FinishScreen: { flex: 1, backgroundColor: '#F5F1E8', paddingTop: 58, overflow: 'hidden' },
  v45FinishHeader: { height: 58, paddingHorizontal: 26, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', zIndex: 3 },
  v45FinishBrand: { fontSize: 34, fontWeight: '900', letterSpacing: -1.5, color: INK },
  v45FinishMenu: { width: 48, height: 48, borderRadius: 24, backgroundColor: '#E9E3D8', alignItems: 'center', justifyContent: 'center', gap: 4 },
  v45FinishMenuLine: { width: 21, height: 3, borderRadius: 2, backgroundColor: INK },
  v45FinishScroll: { paddingHorizontal: 28, paddingTop: 20, paddingBottom: 110 },
  v45FinishTitleWrap: { alignItems: 'center', marginBottom: 22 },
  v45FinishTitle: { fontSize: 40, lineHeight: 46, fontWeight: '900', letterSpacing: -1.5, color: INK },
  v45FinishTitleUnderline: {
    marginTop: -2,
    marginLeft: 120,
  },
  v45PassportCard: { backgroundColor: '#FBF8EF', padding: 18, borderRadius: 13, shadowColor: '#000', shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.12, shadowRadius: 12, elevation: 5 },
  v45PassportCardTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 12 },
  v45PassportLogo: { fontSize: 26, fontWeight: '900', letterSpacing: -1, color: INK },
  v45PassportNumber: { fontSize: 13, fontWeight: '700', color: MUTED },
  v45FinishHeroWrap: { position: 'relative' },
  v45FinishHero: { width: '100%', height: 248, borderRadius: 13, backgroundColor: SOFT },
  v45CompleteStamp: { position: 'absolute', right: -3, top: -10, width: 104, height: 104, borderRadius: 52, borderWidth: 5, borderColor: SIGNAL, alignItems: 'center', justifyContent: 'center', transform: [{ rotate: '-12deg' }], backgroundColor: 'rgba(245,241,232,0.7)' },
  v45CompleteStampText: { width: 70, textAlign: 'center', fontSize: 17, lineHeight: 21, fontWeight: '900', color: SIGNAL },
  v45FinishThumbRow: { flexDirection: 'row', gap: 9, marginTop: 10 },
  v45FinishThumb: { flex: 1, height: 78, borderRadius: 10, backgroundColor: SOFT },
  v45FinishNoPhoto: { height: 246, borderRadius: 13, backgroundColor: '#ECE7DC', alignItems: 'center', justifyContent: 'center' },
  v45FinishNoPhotoRoute: { width: '62%', height: 6, borderRadius: 3, backgroundColor: SIGNAL, transform: [{ rotate: '-7deg' }] },
  v45FinishNoPhotoText: { marginTop: 25, fontSize: 24, fontWeight: '900', color: INK },
  v45FinishInfoRow: { flexDirection: 'row', marginTop: 17, paddingTop: 17, borderTopWidth: 1, borderTopColor: '#D2CBBD' },
  v45FinishDestination: { flex: 1.1, paddingRight: 14 },
  v45FinishFacts: { flex: 0.9, paddingLeft: 16 },
  v45FinishInfoDivider: { width: 1, backgroundColor: '#D2CBBD' },
  v45FinishInfoLabel: { fontSize: 15, fontWeight: '800', color: MUTED },
  v45FinishDestinationText: { marginTop: 5, fontSize: 29, lineHeight: 34, fontWeight: '900', color: INK },
  v45FinishFact: { marginTop: 3, fontSize: 18, lineHeight: 22, fontWeight: '900', color: INK },
  v45FinishPrimary: { height: 66, marginTop: 22, backgroundColor: SIGNAL, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 16, borderRadius: 3 },
  v45FinishPrimaryArrow: { fontSize: 30, color: INK },
  v45FinishPrimaryText: { fontSize: 24, fontWeight: '900', color: INK },
  v45FinishSecondary: { height: 52, marginTop: 9, borderWidth: 1, borderColor: '#CBC5B9', alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(250,247,239,0.9)' },
  v45FinishSecondaryText: { fontSize: 18, fontWeight: '800', color: INK },
  v45DetailScreen: { flex: 1, backgroundColor: '#F5F1E8', paddingTop: 58, overflow: 'hidden' },
  v45DetailTop: { height: 64, paddingHorizontal: 24, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  v45DetailTitleWrap: { flex: 1, alignItems: 'center' },
  v45DetailTitle: { fontSize: 36, lineHeight: 42, fontWeight: '900', letterSpacing: -1.4, color: INK },
  v45DetailTitleUnderline: {
    marginTop: -2,
    marginLeft: 72,
  },
  v45DetailTopSpacer: { width: 42 },
  v45DetailScroll: { paddingHorizontal: 24, paddingTop: 18, paddingBottom: 70 },
  v45DetailTicketStrip: { minHeight: 92, borderWidth: 1, borderColor: '#D0CABD', borderRadius: 10, backgroundColor: '#FBF8EF', flexDirection: 'row', alignItems: 'stretch', paddingHorizontal: 13, paddingVertical: 12 },
  v45DetailTicketBrand: { width: 82, alignSelf: 'center', fontSize: 20, fontWeight: '900', letterSpacing: -1, color: INK },
  v45DetailTicketDivider: { width: 1, backgroundColor: '#D0CABD', marginHorizontal: 10 },
  v45DetailTicketCell: { flex: 1.1, justifyContent: 'center' },
  v45DetailTicketCellSmall: { flex: 0.9, justifyContent: 'center' },
  v45DetailTicketLabel: { fontSize: 12, fontWeight: '800', color: MUTED },
  v45DetailTicketValue: { marginTop: 4, fontSize: 18, lineHeight: 22, fontWeight: '900', color: INK },
  v45DetailTicketValueSmall: { marginTop: 4, fontSize: 14, lineHeight: 18, fontWeight: '900', color: INK },
  v45DetailHeroWrap: { marginTop: 18, height: 382, borderRadius: 19, overflow: 'hidden', position: 'relative' },
  v45DetailHero: { width: '100%', height: '100%', backgroundColor: SOFT },
  v45DetailPhotoCount: { position: 'absolute', right: 15, bottom: 14, paddingHorizontal: 12, height: 34, borderRadius: 17, backgroundColor: 'rgba(17,17,15,0.72)', alignItems: 'center', justifyContent: 'center' },
  v45DetailPhotoCountText: { fontSize: 15, fontWeight: '800', color: BONE },
  v45DetailNoPhoto: { marginTop: 18, height: 300, borderRadius: 19, backgroundColor: '#E9E4D9', alignItems: 'center', justifyContent: 'center' },
  v45DetailNoPhotoText: { fontSize: 22, fontWeight: '800', color: MUTED },
  v45DetailThumbRow: { gap: 9, paddingTop: 10, paddingRight: 20 },
  v45DetailThumb: { width: 65, height: 65, borderRadius: 10, backgroundColor: SOFT, borderWidth: 2, borderColor: 'transparent' },
  v45DetailThumbActive: { borderColor: SIGNAL },
  v45RouteStrip: { marginTop: 24, minHeight: 96, flexDirection: 'row', alignItems: 'center' },
  v45RouteEndpoint: { width: 82, alignItems: 'flex-start' },
  v45RouteEndpointRight: { alignItems: 'flex-end' },
  v45RouteCityIcon: { width: 25, height: 34, backgroundColor: INK, marginBottom: 4 },
  v45RouteFlag: { width: 28, height: 18, backgroundColor: SIGNAL, marginBottom: 8, transform: [{ rotate: '4deg' }] },
  v45RouteEndpointLabel: { fontSize: 12, fontWeight: '700', color: MUTED },
  v45RouteEndpointValue: { marginTop: 2, maxWidth: 90, fontSize: 16, fontWeight: '900', color: INK },
  v45RouteTrack: { flex: 1, height: 64, position: 'relative', flexDirection: 'row', alignItems: 'center', justifyContent: 'center' },
  v45RouteNode: { width: 13, height: 13, borderRadius: 7, borderWidth: 3, borderColor: SIGNAL, backgroundColor: '#F5F1E8', zIndex: 2 },
  v45RouteDashLine: { width: 48, height: 2, marginHorizontal: 2, backgroundColor: SIGNAL, transform: [{ rotate: '12deg' }] },
  v45RouteDashLineB: { width: 48, height: 2, marginHorizontal: 2, backgroundColor: SIGNAL, transform: [{ rotate: '-12deg' }] },
  v45RouteTree: { width: 18, height: 30, borderRadius: 10, backgroundColor: INK, marginHorizontal: 2 },
  v45NoteCard: { marginTop: 12, paddingHorizontal: 20, paddingVertical: 18, borderWidth: 1, borderColor: '#D0CABD', backgroundColor: '#FBF8EF' },
  v45NoteTitle: { fontSize: 20, fontWeight: '900', color: INK },
  v45NoteBody: { marginTop: 10, fontSize: 17, lineHeight: 27, fontWeight: '600', color: '#4F4B44' },
  v45ShareButton: { height: 68, marginTop: 22, backgroundColor: SIGNAL, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 12 },
  v45ShareIcon: { fontSize: 28, color: BONE },
  v45ShareText: { fontSize: 22, fontWeight: '900', color: BONE },
  v45SharePosterOffscreen: { position: 'absolute', left: -5000, top: 0, width: 360, height: 640, backgroundColor: '#F5F1E8' },
  v45Poster: { width: 360, height: 640, backgroundColor: '#F5F1E8', padding: 22 },
  v45PosterTop: { height: 48, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  v45PosterBrand: { fontSize: 26, fontWeight: '900', letterSpacing: -1.2, color: INK },
  v45PosterDate: { fontSize: 13, fontWeight: '800', color: MUTED },
  v45PosterPhoto: { width: '100%', height: 356, borderRadius: 18, backgroundColor: SOFT },
  v45PosterNoPhoto: { alignItems: 'center', justifyContent: 'center' },
  v45PosterNoPhotoText: { fontSize: 20, fontWeight: '800', color: MUTED },
  v45PosterCopy: { paddingTop: 18 },
  v45PosterMood: { fontSize: 34, lineHeight: 38, fontWeight: '900', letterSpacing: -1.3, color: INK },
  v45PosterDestination: { marginTop: 3, fontSize: 20, lineHeight: 25, fontWeight: '800', color: INK },
  v45PosterOrangeRule: { width: 94, height: 5, borderRadius: 3, marginTop: 10, backgroundColor: SIGNAL, transform: [{ rotate: '-3deg' }] },
  v45PosterFacts: { marginTop: 13, flexDirection: 'row', gap: 18 },
  v45PosterFact: { fontSize: 14, fontWeight: '800', color: MUTED },
  v45PosterRoute: { marginTop: 15, height: 34, flexDirection: 'row', alignItems: 'center' },
  v45PosterRouteStart: { width: 12, height: 12, borderRadius: 6, backgroundColor: SIGNAL },
  v45PosterRouteLineA: { width: 88, height: 3, backgroundColor: INK, transform: [{ rotate: '-7deg' }] },
  v45PosterRouteTurn: { width: 20, height: 20, borderTopWidth: 4, borderRightWidth: 4, borderColor: INK, transform: [{ rotate: '25deg' }] },
  v45PosterRouteLineB: { flex: 1, height: 3, backgroundColor: INK, transform: [{ rotate: '5deg' }] },
  v45PosterRouteEnd: { width: 15, height: 15, backgroundColor: SIGNAL },
  v46TicketPaper:{width:'100%',height:432,backgroundColor:'#FCF8EE',paddingHorizontal:24,paddingTop:40,paddingBottom:18,borderColor:'#D6D0C2',borderWidth:1,shadowColor:'#000',shadowOffset:{width:0,height:7},shadowOpacity:.12,shadowRadius:8,elevation:4,overflow:'hidden',position:'relative'},
  v46TicketOrangeFeed:{position:'absolute',top:0,left:0,right:0,height:22,backgroundColor:SIGNAL,opacity:.9},
  v46TicketBrand:{color:INK,fontSize:35,fontWeight:'900',letterSpacing:-2.3,marginBottom:12},
  v46TicketDashRule:{height:1,borderTopWidth:1.5,borderStyle:'dashed',borderColor:'#B7B0A5',marginVertical:10},
  v46TicketMainRow:{minHeight:112,flexDirection:'row',alignItems:'stretch'},
  v46TicketTimeBlock:{flex:.95,paddingRight:12,justifyContent:'center'},
  v46TicketLabel:{color:INK,fontSize:16,fontWeight:'900',letterSpacing:.5,marginBottom:5},
  v46TicketTimeRow:{flexDirection:'row',alignItems:'baseline'},
  v46TicketMinutes:{color:SIGNAL,fontSize:58,lineHeight:62,fontWeight:'900',letterSpacing:-3},
  v46TicketMinutesUnit:{color:INK,fontSize:20,fontWeight:'900',marginLeft:6},
  v46TicketVerticalDash:{width:1,borderLeftWidth:1.5,borderStyle:'dashed',borderColor:'#B7B0A5',marginVertical:7},
  v46TicketMoodBlock:{flex:1.15,paddingLeft:16,justifyContent:'center'},
  v46TicketMoodRow:{flexDirection:'row',alignItems:'center',gap:7},
  v46TicketMoodText:{flexShrink:1,color:INK,fontSize:24,fontWeight:'900',letterSpacing:-1},
  v46TicketDestinationRow:{minHeight:92,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},
  v46TicketUnknownRow:{flexDirection:'row',alignItems:'center'},
  v46TicketUnknown:{color:INK,fontSize:41,fontWeight:'900',letterSpacing:2},
  v46TicketPin:{width:25,height:32,borderRadius:15,backgroundColor:SIGNAL,marginRight:9,alignItems:'center',paddingTop:7},
  v46TicketPinHole:{width:8,height:8,borderRadius:4,backgroundColor:'#FCF8EE'},
  v46TicketMiniRoute:{width:132,height:66,position:'relative'},
  v46MiniBuilding:{position:'absolute',left:3,bottom:9,width:18,height:25,backgroundColor:INK},
  v46MiniRouteDash:{position:'absolute',left:28,top:34,width:29,height:3,borderRadius:2,backgroundColor:SIGNAL,transform:[{rotate:'18deg'}]},
  v46MiniTree:{position:'absolute',left:76,bottom:8,width:16,height:30,borderRadius:12,backgroundColor:INK},
  v46MiniFlagPole:{position:'absolute',right:16,bottom:8,width:3,height:42,backgroundColor:INK},
  v46MiniFlag:{position:'absolute',right:0,top:10,width:18,height:11,backgroundColor:SIGNAL},
  v46Barcode:{height:45,flexDirection:'row',alignItems:'stretch',justifyContent:'center',gap:3,paddingTop:3},
  v46BarcodeBar:{height:40,backgroundColor:INK},
  v46SecretStamp:{position:'absolute',right:18,top:205,borderWidth:3,borderColor:SIGNAL,paddingHorizontal:10,paddingVertical:7,backgroundColor:'rgba(252,248,238,.88)'},
  v46SecretStampText:{color:SIGNAL,fontSize:18,fontWeight:'900',letterSpacing:1},
  v46HomeHeroRoute: {
    width: '100%',
    height: '100%',
  },
  v46ArtTicket: {
    width: 310,
    aspectRatio: 1115 / 1411,
    position: 'relative',
  },
  v46ArtTicketBase: {
    ...ABSOLUTE_FILL,
    width: '100%',
    height: '100%',
  },
  v51TicketFeedHead: {
    position: 'absolute',
    left: 7,
    right: 7,
    top: 0,
    height: 63,
    backgroundColor: '#FCF8EE',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2,
    borderBottomWidth: 1,
    borderBottomColor: '#D8D0C2',
  },
  v51TicketFeedBarcode: {
    height: 38,
    flexDirection: 'row',
    alignItems: 'stretch',
    justifyContent: 'center',
    gap: 2.6,
  },
  v51TicketFeedBarcodeBar: {
    height: 38,
    backgroundColor: INK,
  },
  v49TicketArtworkPending: {
    opacity: 0,
  },
  v46ArtTicketHeader: {
    position: 'absolute',
    left: '9%',
    right: '9%',
    top: '16.5%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
  },
  v46ArtTicketBrand: {
    fontSize: 30,
    lineHeight: 34,
    fontWeight: '900',
    letterSpacing: -1.8,
    color: INK,
  },
  v46ArtTicketSerial: {
    paddingBottom: 3,
    fontSize: 9,
    fontWeight: '800',
    letterSpacing: 1.1,
    color: '#77736B',
  },
  v46ArtTicketLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '900',
    color: INK,
  },
  v46ArtTicketTimeBlock: {
    position: 'absolute',
    left: '10%',
    top: '32.5%',
    width: '37%',
  },
  v46ArtTicketTimeRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    marginTop: 2,
  },
  v46ArtTicketMinutes: {
    fontSize: 47,
    lineHeight: 50,
    fontWeight: '900',
    letterSpacing: -2.7,
    color: SIGNAL,
  },
  v46ArtTicketMinutesUnit: {
    marginLeft: 4,
    marginBottom: 5,
    fontSize: 16,
    fontWeight: '900',
    color: INK,
  },
  v46ArtTicketMoodBlock: {
    position: 'absolute',
    right: '7.5%',
    top: '32.5%',
    width: '39%',
  },
  v46ArtTicketMoodRow: {
    marginTop: 3,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  v46ArtTicketMoodText: {
    flex: 1,
    fontSize: 21,
    lineHeight: 25,
    fontWeight: '900',
    color: INK,
  },
  v46ArtTicketDestinationBlock: {
    position: 'absolute',
    left: '10%',
    top: '56.2%',
    width: '39%',
  },
  v46ArtTicketUnknownRow: {
    marginTop: 7,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  v46ArtTicketPin: {
    width: 24,
    height: 30,
    borderRadius: 13,
    backgroundColor: SIGNAL,
    alignItems: 'center',
    paddingTop: 7,
  },
  v46ArtTicketPinCore: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#FBF8EF',
  },
  v46ArtTicketUnknown: {
    fontSize: 36,
    lineHeight: 40,
    fontWeight: '900',
    letterSpacing: 2,
    color: INK,
  },
  v46ArtTicketMiniRoute: {
    position: 'absolute',
    right: '8%',
    top: '57%',
    width: '37%',
    height: 56,
  },
  v46ArtMiniStart: {
    position: 'absolute',
    left: 2,
    bottom: 10,
    width: 13,
    height: 22,
    borderRadius: 2,
    backgroundColor: INK,
  },
  v46ArtMiniDash: {
    position: 'absolute',
    width: 45,
    borderTopWidth: 3,
    borderStyle: 'dashed',
    borderColor: SIGNAL,
  },
  v46ArtMiniTree: {
    position: 'absolute',
    left: 58,
    top: 13,
    width: 15,
    height: 27,
    borderRadius: 8,
    backgroundColor: INK,
  },
  v46ArtMiniFlagPole: {
    position: 'absolute',
    right: 9,
    top: 7,
    width: 3,
    height: 34,
    backgroundColor: INK,
  },
  v46ArtMiniFlag: {
    position: 'absolute',
    right: -2,
    top: 7,
    width: 14,
    height: 11,
    backgroundColor: SIGNAL,
  },
  v46ArtBarcode: {
    position: 'absolute',
    left: '21%',
    right: '21%',
    bottom: '13%',
    height: 39,
    flexDirection: 'row',
    alignItems: 'stretch',
    justifyContent: 'center',
    gap: 2,
  },
  v46ArtBarcodeBar: {
    height: '100%',
    backgroundColor: INK,
  },
  v46ArtSecretStamp: {
    position: 'absolute',
    right: '7%',
    top: '44%',
    paddingHorizontal: 9,
    paddingVertical: 6,
    borderWidth: 3,
    borderColor: SIGNAL,
    backgroundColor: 'rgba(251,248,239,0.86)',
  },
  v46ArtSecretStampText: {
    fontSize: 17,
    fontWeight: '900',
    color: SIGNAL,
  },
  v46ArtPrinterStage: {
    width: '100%',
    height: 430,
    marginTop: 18,
    alignItems: 'center',
    position: 'relative',
    zIndex: 2,
  },
  v46ArtPrinterImage: {
    position: 'absolute',
    top: -25,
    width: '100%',
    aspectRatio: 2048 / 682,
    zIndex: 4,
  },
  v46ArtPaperReveal: {
    position: 'absolute',
    top: 34,
    width: 310,
    overflow: 'hidden',
    alignItems: 'center',
    zIndex: 2,
  },
  v47PrintTicketBottomAnchor: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: 'center',
  },
  v46ArtPrinterTopMask: {
    display: 'none',
  },
  v46ArtPrinterImageMask: {
    position: 'absolute',
    top: 0,
    width: '100%',
    aspectRatio: 2048 / 682,
  },
  v46ArtworkBase: {
    ...ABSOLUTE_FILL,
    width: '100%',
    height: '100%',
  },
  v46CompleteArtwork: {
    width: '100%',
    aspectRatio: 942 / 1670,
    position: 'relative',
    marginBottom: 24,
  },
  v46CompleteHeroPhoto: {
    position: 'absolute',
    left: '5.1%',
    top: '15.2%',
    width: '89.8%',
    height: '41.1%',
    borderRadius: 10,
  },
  v46CompleteTopInfo: {
    position: 'absolute',
    left: '4.8%',
    right: '4.8%',
    top: '3.8%',
    height: '8.2%',
    flexDirection: 'row',
    alignItems: 'center',
  },
  v46CompleteTopCell: {
    flex: 1,
    height: '100%',
    textAlign: 'center',
    textAlignVertical: 'center',
    fontSize: 10,
    fontWeight: '900',
    color: INK,
    borderRightWidth: 1,
    borderRightColor: '#B8B0A4',
  },
  v46CompleteTopCellLast: {
    borderRightWidth: 0,
  },
  v46CompleteThumbRow: {
    position: 'absolute',
    left: '3.2%',
    right: '3.2%',
    top: '58.2%',
    height: '9.8%',
    flexDirection: 'row',
    gap: 3,
  },
  v46CompleteThumb: {
    flex: 1,
    height: '100%',
    borderRadius: 8,
  },
  v46CompleteThumbEmpty: {
    flex: 1,
    height: '100%',
  },
  v46CompleteCopy: {
    position: 'absolute',
    left: '8%',
    right: '8%',
    top: '70.1%',
  },
  v46CompleteKicker: {
    fontSize: 12,
    fontWeight: '800',
    color: MUTED,
  },
  v46CompleteDestination: {
    marginTop: 5,
    width: '62%',
    fontSize: 21,
    lineHeight: 25,
    fontWeight: '900',
    color: INK,
  },
  v46CompleteMeta: {
    marginTop: 7,
    fontSize: 12,
    fontWeight: '700',
    color: MUTED,
  },
  v46CompleteOrangeBand: {
    position: 'absolute',
    left: '7%',
    bottom: '9.4%',
    fontSize: 16,
    fontWeight: '900',
    letterSpacing: 1,
    color: '#FFF8EE',
  },
  v46ReviewArtwork: {
    width: '100%',
    aspectRatio: 1122 / 1402,
    position: 'relative',
    marginBottom: 22,
  },
  v46ReviewHeader: {
    position: 'absolute',
    left: '9%',
    right: '9%',
    top: '5.5%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  v46ReviewBrand: {
    fontSize: 19,
    fontWeight: '900',
    letterSpacing: 3,
    color: INK,
  },
  v46ReviewDate: {
    fontSize: 11,
    fontWeight: '800',
    color: MUTED,
  },
  v46ReviewHeroPhoto: {
    position: 'absolute',
    left: '10.2%',
    top: '17.1%',
    width: '79.2%',
    height: '38.4%',
    borderRadius: 12,
  },
  v46ReviewThumbRow: {
    position: 'absolute',
    left: '10.2%',
    right: '10.2%',
    top: '57.1%',
    height: '12.4%',
    flexDirection: 'row',
    gap: 6,
  },
  v46ReviewThumbPress: {
    flex: 1,
    height: '100%',
  },
  v46ReviewThumb: {
    width: '100%',
    height: '100%',
    borderRadius: 11,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  v46ReviewThumbActive: {
    borderColor: SIGNAL,
  },
  v46ReviewThumbEmpty: {
    flex: 1,
  },
  v46ReviewCopyLeft: {
    position: 'absolute',
    left: '12.2%',
    top: '76.7%',
    width: '35%',
  },
  v46ReviewCopyRight: {
    position: 'absolute',
    left: '58.5%',
    top: '76.7%',
    width: '29%',
  },
  v46ReviewKicker: {
    fontSize: 12,
    fontWeight: '900',
    color: SIGNAL,
  },
  v46ReviewDestination: {
    marginTop: 6,
    fontSize: 18,
    lineHeight: 23,
    fontWeight: '900',
    color: INK,
  },
  v46ReviewFact: {
    marginBottom: 7,
    fontSize: 14,
    fontWeight: '800',
    color: INK,
  }
});
