from pathlib import Path
import re
ROOT=Path(__file__).resolve().parents[1]
INDEX=ROOT/'src/app/index.tsx'; BUILD=ROOT/'src/lib/build-info.ts'
text=INDEX.read_text()
for a,b in [('隨便走走','隨便走'),('吃點東西','吃東西'),('放鬆一下','想安靜'),('探索新鮮','這是哪'),('拍照走走','色色的'),('交給驚喜','命運')]: text=text.replace("label: '"+a+"'","label: '"+b+"'",1)
text=text.replace("function V45MoodIcon({ moodId }: { moodId: MoodId }) {\n  const commonProps = { width: 76, height: 76 };","function V45MoodIcon({ moodId, size = 76 }: { moodId: MoodId; size?: number }) {\n  const commonProps = { width: size, height: size };",1)
start=text.index('function V45Ticket('); m=re.search(r'\nfunction [A-Za-z0-9_]+\(',text[start+1:]); end=start+1+m.start()
ticket='''function V45Ticket({ timeLabel, moodLabel, moodId, serial: _serial, stamped = false, stampProgress }: { timeLabel: string; moodLabel: string; moodId: MoodId; serial: string; stamped?: boolean; stampProgress?: Animated.Value; }) {\n  const stampScale = stampProgress ? stampProgress.interpolate({ inputRange: [0,1], outputRange: [1.28,1] }) : 1;\n  const stampOpacity = stampProgress ?? (stamped ? 1 : 0);\n  return <View style={styles.v46TicketPaper}>\n    <View style={styles.v46TicketOrangeFeed}/><Text style={styles.v46TicketBrand}>DETOUR</Text><View style={styles.v46TicketDashRule}/>\n    <View style={styles.v46TicketMainRow}><View style={styles.v46TicketTimeBlock}><Text style={styles.v46TicketLabel}>旅程時間</Text><View style={styles.v46TicketTimeRow}><Text style={styles.v46TicketMinutes}>{timeLabel}</Text><Text style={styles.v46TicketMinutesUnit}>分鐘</Text></View></View><View style={styles.v46TicketVerticalDash}/><View style={styles.v46TicketMoodBlock}><Text style={styles.v46TicketLabel}>此趟心情</Text><View style={styles.v46TicketMoodRow}><V45MoodIcon moodId={moodId} size={48}/><Text style={styles.v46TicketMoodText}>{moodLabel}</Text></View></View></View>\n    <View style={styles.v46TicketDashRule}/><View style={styles.v46TicketDestinationRow}><View><Text style={styles.v46TicketLabel}>目的地</Text><View style={styles.v46TicketUnknownRow}><View style={styles.v46TicketPin}><View style={styles.v46TicketPinHole}/></View><Text style={styles.v46TicketUnknown}>???</Text></View></View><View style={styles.v46TicketMiniRoute}><View style={styles.v46MiniBuilding}/><View style={styles.v46MiniRouteDash}/><View style={styles.v46MiniTree}/><View style={[styles.v46MiniRouteDash,{left:72,transform:[{rotate:'-16deg'}]}]}/><View style={styles.v46MiniFlagPole}/><View style={styles.v46MiniFlag}/></View></View>\n    <View style={styles.v46TicketDashRule}/><View style={styles.v46Barcode}>{Array.from({length:27}).map((_,i)=><View key={`barcode-${i}`} style={[styles.v46BarcodeBar,{width:i%5===0?4:i%3===0?2:1.5}]}/>)}</View>\n    {stamped&&<Animated.View style={[styles.v46SecretStamp,{opacity:stampOpacity,transform:[{rotate:'-8deg'},{scale:stampScale}]}]}><Text style={styles.v46SecretStampText}>終點保密</Text></Animated.View>}\n  </View>;\n}\n'''
text=text[:start]+ticket+text[end:]
needle="<V45Ticket\n                    timeLabel={selectedTime ?? '15'}"; assert text.count(needle)==2
text=text.replace(needle,"<V45Ticket\n                    timeLabel={selectedTime ?? '15'}\n                    moodId={selectedMood ?? 'wander'}")
text=text.replace('<View style={styles.v45PaperMask}>',"<Animated.View style={[styles.v45PaperMask,{height:routeProgress.interpolate({inputRange:[0,1],outputRange:[4,438]})}]}>",1)
text=text.replace('outputRange: [-438, 0],','outputRange: [0, 0],',1)
ms=text.index('<Animated.View style={[styles.v45PaperMask'); pair='                </Animated.View>\n              </View>'; p=text.find(pair,ms); assert p!=-1; text=text[:p]+'                </Animated.View>\n              </Animated.View>'+text[p+len(pair):]
ps=text.index("{stage === 'preparing' && ("); pe=text.index("{stage === 'ready' && (",ps); block=text[ps:pe].replace('\n            <V45Skyline />','').replace('\n          <V45Skyline />',''); text=text[:ps]+block+text[pe:]
text=re.sub(r"  v45PrinterMachine: \{.*?\n  \},\n  v45PrinterPulse:","  v45PrinterMachine: { width:'100%',height:96,borderRadius:20,backgroundColor:'#AAA69E',borderWidth:1,borderColor:'#D3D0C9',paddingHorizontal:20,justifyContent:'center',zIndex:6,shadowColor:'#000',shadowOffset:{width:0,height:10},shadowOpacity:.22,shadowRadius:14,elevation:9 },\n  v45PrinterPulse:",text,count=1,flags=re.S)
text=re.sub(r"  v45PrinterSlot: \{.*?\n  \},\n  v45PaperMask:","  v45PrinterSlot: { height:25,borderRadius:8,backgroundColor:'#11110F',borderWidth:6,borderColor:'#5D5A54',shadowColor:'#000',shadowOffset:{width:0,height:3},shadowOpacity:.4,shadowRadius:4,elevation:5 },\n  v45PaperMask:",text,count=1,flags=re.S)
styles="""\n  v46TicketPaper:{width:'100%',height:432,backgroundColor:'#FCF8EE',paddingHorizontal:24,paddingTop:40,paddingBottom:18,borderColor:'#D6D0C2',borderWidth:1,shadowColor:'#000',shadowOffset:{width:0,height:7},shadowOpacity:.12,shadowRadius:8,elevation:4,overflow:'hidden',position:'relative'}, v46TicketOrangeFeed:{position:'absolute',top:0,left:0,right:0,height:22,backgroundColor:SIGNAL,opacity:.9}, v46TicketBrand:{color:INK,fontSize:35,fontWeight:'900',letterSpacing:-2.3,marginBottom:12}, v46TicketDashRule:{height:1,borderTopWidth:1.5,borderStyle:'dashed',borderColor:'#B7B0A5',marginVertical:10},\n  v46TicketMainRow:{minHeight:112,flexDirection:'row',alignItems:'stretch'},v46TicketTimeBlock:{flex:.95,paddingRight:12,justifyContent:'center'},v46TicketLabel:{color:INK,fontSize:16,fontWeight:'900',letterSpacing:.5,marginBottom:5},v46TicketTimeRow:{flexDirection:'row',alignItems:'baseline'},v46TicketMinutes:{color:SIGNAL,fontSize:58,lineHeight:62,fontWeight:'900',letterSpacing:-3},v46TicketMinutesUnit:{color:INK,fontSize:20,fontWeight:'900',marginLeft:6},v46TicketVerticalDash:{width:1,borderLeftWidth:1.5,borderStyle:'dashed',borderColor:'#B7B0A5',marginVertical:7},v46TicketMoodBlock:{flex:1.15,paddingLeft:16,justifyContent:'center'},v46TicketMoodRow:{flexDirection:'row',alignItems:'center',gap:7},v46TicketMoodText:{flexShrink:1,color:INK,fontSize:24,fontWeight:'900',letterSpacing:-1},\n  v46TicketDestinationRow:{minHeight:92,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},v46TicketUnknownRow:{flexDirection:'row',alignItems:'center'},v46TicketUnknown:{color:INK,fontSize:41,fontWeight:'900',letterSpacing:2},v46TicketPin:{width:25,height:32,borderRadius:15,backgroundColor:SIGNAL,marginRight:9,alignItems:'center',paddingTop:7},v46TicketPinHole:{width:8,height:8,borderRadius:4,backgroundColor:'#FCF8EE'},v46TicketMiniRoute:{width:132,height:66,position:'relative'},v46MiniBuilding:{position:'absolute',left:3,bottom:9,width:18,height:25,backgroundColor:INK},v46MiniRouteDash:{position:'absolute',left:28,top:34,width:29,height:3,borderRadius:2,backgroundColor:SIGNAL,transform:[{rotate:'18deg'}]},v46MiniTree:{position:'absolute',left:76,bottom:8,width:16,height:30,borderRadius:12,backgroundColor:INK},v46MiniFlagPole:{position:'absolute',right:16,bottom:8,width:3,height:42,backgroundColor:INK},v46MiniFlag:{position:'absolute',right:0,top:10,width:18,height:11,backgroundColor:SIGNAL},\n  v46Barcode:{height:45,flexDirection:'row',alignItems:'stretch',justifyContent:'center',gap:3,paddingTop:3},v46BarcodeBar:{height:40,backgroundColor:INK},v46SecretStamp:{position:'absolute',right:18,top:205,borderWidth:3,borderColor:SIGNAL,paddingHorizontal:10,paddingVertical:7,backgroundColor:'rgba(252,248,238,.88)'},v46SecretStampText:{color:SIGNAL,fontSize:18,fontWeight:'900',letterSpacing:1},\n"""
i=text.rfind('\n});'); text=text[:i]+styles+text[i:]; INDEX.write_text(text)
b=BUILD.read_text(); b=re.sub(r"// v0\.45\.1:.*\nexport const DETOUR_BUILD_VERSION = '0\.45\.1';","// v0.45.2: restore approved Mood labels/icons and rebuild the physical ticket printer.\nexport const DETOUR_BUILD_VERSION = '0.45.2';",b,count=1); BUILD.write_text(b)
