name: Try iOS preview build

on:
  push:
    branches:
      - main

jobs:
  build_ios_preview:
    name: Build iOS preview
    type: build
    params:
      platform: ios
      profile: preview
      message: Try iOS preview build from GitHub
